// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_product_types.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogProductTypeByID = `-- name: CatalogProductTypeByID :one
SELECT type_id, code, name_ar, name_en, description_ar, description_en,
    is_active, position, type_revision,
    source_event_id, source_device_id, source_payload_hash, store_id
FROM catalog_product_types WHERE type_id = $1
`

type CatalogProductTypeByIDRow struct {
	TypeID            pgtype.UUID `json:"type_id"`
	Code              string      `json:"code"`
	NameAr            string      `json:"name_ar"`
	NameEn            string      `json:"name_en"`
	DescriptionAr     pgtype.Text `json:"description_ar"`
	DescriptionEn     pgtype.Text `json:"description_en"`
	IsActive          bool        `json:"is_active"`
	Position          int32       `json:"position"`
	TypeRevision      int64       `json:"type_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
	StoreID           pgtype.UUID `json:"store_id"`
}

func (q *Queries) CatalogProductTypeByID(ctx context.Context, typeID pgtype.UUID) (CatalogProductTypeByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogProductTypeByID, typeID)
	var i CatalogProductTypeByIDRow
	err := row.Scan(
		&i.TypeID,
		&i.Code,
		&i.NameAr,
		&i.NameEn,
		&i.DescriptionAr,
		&i.DescriptionEn,
		&i.IsActive,
		&i.Position,
		&i.TypeRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
		&i.StoreID,
	)
	return i, err
}

const catalogProductTypeCapabilities = `-- name: CatalogProductTypeCapabilities :many
SELECT capability_code FROM catalog_product_type_capabilities
WHERE type_id = $1 ORDER BY capability_code
`

func (q *Queries) CatalogProductTypeCapabilities(ctx context.Context, typeID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, catalogProductTypeCapabilities, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var capability_code string
		if err := rows.Scan(&capability_code); err != nil {
			return nil, err
		}
		items = append(items, capability_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductTypeDimensions = `-- name: CatalogProductTypeDimensions :many
SELECT definition_code FROM catalog_product_type_variant_dimensions
WHERE type_id = $1 ORDER BY position, definition_code
`

func (q *Queries) CatalogProductTypeDimensions(ctx context.Context, typeID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, catalogProductTypeDimensions, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var definition_code string
		if err := rows.Scan(&definition_code); err != nil {
			return nil, err
		}
		items = append(items, definition_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCatalogProductTypeCapabilities = `-- name: DeleteCatalogProductTypeCapabilities :exec
DELETE FROM catalog_product_type_capabilities WHERE type_id = $1
`

func (q *Queries) DeleteCatalogProductTypeCapabilities(ctx context.Context, typeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductTypeCapabilities, typeID)
	return err
}

const deleteCatalogProductTypeDimensions = `-- name: DeleteCatalogProductTypeDimensions :exec
DELETE FROM catalog_product_type_variant_dimensions WHERE type_id = $1
`

func (q *Queries) DeleteCatalogProductTypeDimensions(ctx context.Context, typeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductTypeDimensions, typeID)
	return err
}

const insertCatalogProductTypeCapability = `-- name: InsertCatalogProductTypeCapability :exec
INSERT INTO catalog_product_type_capabilities (type_id, capability_code)
VALUES ($1, $2)
`

type InsertCatalogProductTypeCapabilityParams struct {
	TypeID         pgtype.UUID `json:"type_id"`
	CapabilityCode string      `json:"capability_code"`
}

func (q *Queries) InsertCatalogProductTypeCapability(ctx context.Context, arg InsertCatalogProductTypeCapabilityParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductTypeCapability, arg.TypeID, arg.CapabilityCode)
	return err
}

const insertCatalogProductTypeDimension = `-- name: InsertCatalogProductTypeDimension :exec
INSERT INTO catalog_product_type_variant_dimensions (type_id, definition_code, position)
VALUES ($1, $2, $3)
`

type InsertCatalogProductTypeDimensionParams struct {
	TypeID         pgtype.UUID `json:"type_id"`
	DefinitionCode string      `json:"definition_code"`
	Position       int32       `json:"position"`
}

func (q *Queries) InsertCatalogProductTypeDimension(ctx context.Context, arg InsertCatalogProductTypeDimensionParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductTypeDimension, arg.TypeID, arg.DefinitionCode, arg.Position)
	return err
}

const listCatalogProductTypes = `-- name: ListCatalogProductTypes :many
SELECT type_id, code, name_ar, name_en, description_ar, description_en,
    is_active, position, type_revision,
    source_event_id, source_device_id, source_payload_hash, store_id
FROM catalog_product_types
WHERE (NULLIF($1::text, '') IS NULL OR store_id::text = $1 OR ($1 = 'null' AND store_id IS NULL))
ORDER BY position, code
`

type ListCatalogProductTypesRow struct {
	TypeID            pgtype.UUID `json:"type_id"`
	Code              string      `json:"code"`
	NameAr            string      `json:"name_ar"`
	NameEn            string      `json:"name_en"`
	DescriptionAr     pgtype.Text `json:"description_ar"`
	DescriptionEn     pgtype.Text `json:"description_en"`
	IsActive          bool        `json:"is_active"`
	Position          int32       `json:"position"`
	TypeRevision      int64       `json:"type_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
	StoreID           pgtype.UUID `json:"store_id"`
}

func (q *Queries) ListCatalogProductTypes(ctx context.Context, dollar_1 string) ([]ListCatalogProductTypesRow, error) {
	rows, err := q.db.Query(ctx, listCatalogProductTypes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogProductTypesRow{}
	for rows.Next() {
		var i ListCatalogProductTypesRow
		if err := rows.Scan(
			&i.TypeID,
			&i.Code,
			&i.NameAr,
			&i.NameEn,
			&i.DescriptionAr,
			&i.DescriptionEn,
			&i.IsActive,
			&i.Position,
			&i.TypeRevision,
			&i.SourceEventID,
			&i.SourceDeviceID,
			&i.SourcePayloadHash,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCatalogProductTypeID = `-- name: SetCatalogProductTypeID :exec
UPDATE catalog_products SET product_type_id = $2 WHERE product_id = $1
`

type SetCatalogProductTypeIDParams struct {
	ProductID     pgtype.UUID `json:"product_id"`
	ProductTypeID pgtype.UUID `json:"product_type_id"`
}

func (q *Queries) SetCatalogProductTypeID(ctx context.Context, arg SetCatalogProductTypeIDParams) error {
	_, err := q.db.Exec(ctx, setCatalogProductTypeID, arg.ProductID, arg.ProductTypeID)
	return err
}

const upsertCatalogProductType = `-- name: UpsertCatalogProductType :exec

INSERT INTO catalog_product_types (
    type_id, code, name_ar, name_en, description_ar, description_en,
    is_active, position, type_revision,
    source_event_id, source_device_id, source_payload_hash, source_received_at, store_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (type_id) DO UPDATE SET
    code = excluded.code,
    name_ar = excluded.name_ar, name_en = excluded.name_en,
    description_ar = excluded.description_ar, description_en = excluded.description_en,
    is_active = excluded.is_active, position = excluded.position,
    type_revision = excluded.type_revision,
    source_event_id = excluded.source_event_id, source_device_id = excluded.source_device_id,
    source_payload_hash = excluded.source_payload_hash, source_received_at = excluded.source_received_at,
    store_id = COALESCE(excluded.store_id, catalog_product_types.store_id),
    projected_at = now()
`

type UpsertCatalogProductTypeParams struct {
	TypeID            pgtype.UUID        `json:"type_id"`
	Code              string             `json:"code"`
	NameAr            string             `json:"name_ar"`
	NameEn            string             `json:"name_en"`
	DescriptionAr     pgtype.Text        `json:"description_ar"`
	DescriptionEn     pgtype.Text        `json:"description_en"`
	IsActive          bool               `json:"is_active"`
	Position          int32              `json:"position"`
	TypeRevision      int64              `json:"type_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
	StoreID           pgtype.UUID        `json:"store_id"`
}

// Phase 17-R2 ProductType projections (ADR-0050). Current-state replace
// semantics: one type row carrying the highest valid type_revision;
// dimensions and capabilities are replaced transactionally per type
// revision. Store ownership follows the 00023 model (see
// UpsertCatalogCategory): NULL = unscoped legacy, COALESCE preserves
// proven ownership, cross-Store writes are fenced in Go before any
// upsert runs.
func (q *Queries) UpsertCatalogProductType(ctx context.Context, arg UpsertCatalogProductTypeParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogProductType,
		arg.TypeID,
		arg.Code,
		arg.NameAr,
		arg.NameEn,
		arg.DescriptionAr,
		arg.DescriptionEn,
		arg.IsActive,
		arg.Position,
		arg.TypeRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
		arg.StoreID,
	)
	return err
}
