// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_projection.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allCatalogCategoryEdges = `-- name: AllCatalogCategoryEdges :many
SELECT parent_id, child_id FROM catalog_category_edges ORDER BY parent_id, child_id
`

type AllCatalogCategoryEdgesRow struct {
	ParentID pgtype.UUID `json:"parent_id"`
	ChildID  pgtype.UUID `json:"child_id"`
}

func (q *Queries) AllCatalogCategoryEdges(ctx context.Context) ([]AllCatalogCategoryEdgesRow, error) {
	rows, err := q.db.Query(ctx, allCatalogCategoryEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllCatalogCategoryEdgesRow{}
	for rows.Next() {
		var i AllCatalogCategoryEdgesRow
		if err := rows.Scan(&i.ParentID, &i.ChildID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogActiveProducts = `-- name: CatalogActiveProducts :many
SELECT product_id, sku, name, source_revision, source_event_id
FROM catalog_products
WHERE is_active ORDER BY sku, product_id
LIMIT $1
`

type CatalogActiveProductsRow struct {
	ProductID      pgtype.UUID `json:"product_id"`
	Sku            string      `json:"sku"`
	Name           string      `json:"name"`
	SourceRevision int64       `json:"source_revision"`
	SourceEventID  pgtype.UUID `json:"source_event_id"`
}

func (q *Queries) CatalogActiveProducts(ctx context.Context, limit int32) ([]CatalogActiveProductsRow, error) {
	rows, err := q.db.Query(ctx, catalogActiveProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogActiveProductsRow{}
	for rows.Next() {
		var i CatalogActiveProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.SourceRevision,
			&i.SourceEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogCategoryByID = `-- name: CatalogCategoryByID :one
SELECT category_id, status, name_ar, name_en, source_revision,
    source_event_id, source_device_id, source_payload_hash
FROM catalog_categories WHERE category_id = $1
`

type CatalogCategoryByIDRow struct {
	CategoryID        pgtype.UUID `json:"category_id"`
	Status            string      `json:"status"`
	NameAr            string      `json:"name_ar"`
	NameEn            pgtype.Text `json:"name_en"`
	SourceRevision    int64       `json:"source_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
}

func (q *Queries) CatalogCategoryByID(ctx context.Context, categoryID pgtype.UUID) (CatalogCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogCategoryByID, categoryID)
	var i CatalogCategoryByIDRow
	err := row.Scan(
		&i.CategoryID,
		&i.Status,
		&i.NameAr,
		&i.NameEn,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
	)
	return i, err
}

const catalogCategoryParents = `-- name: CatalogCategoryParents :many
SELECT parent_id FROM catalog_category_edges WHERE child_id = $1 ORDER BY position, parent_id
`

func (q *Queries) CatalogCategoryParents(ctx context.Context, childID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogCategoryParents, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var parent_id pgtype.UUID
		if err := rows.Scan(&parent_id); err != nil {
			return nil, err
		}
		items = append(items, parent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogEntityEventRevisions = `-- name: CatalogEntityEventRevisions :many

SELECT e.event_id,
    (e.payload->>'catalog_revision')::bigint AS revision,
    COALESCE(p.status, 'missing') AS processing_status,
    COALESCE(p.last_error_code, '') AS last_error_code
FROM sync_events e
LEFT JOIN sync_event_processing p
  ON p.event_id = e.event_id AND p.processor = $4
WHERE e.event_type = $1
  AND e.payload->>($2::text) = ($3::text)
`

type CatalogEntityEventRevisionsParams struct {
	EventType string `json:"event_type"`
	Column2   string `json:"column_2"`
	Column3   string `json:"column_3"`
	Processor string `json:"processor"`
}

type CatalogEntityEventRevisionsRow struct {
	EventID          pgtype.UUID `json:"event_id"`
	Revision         int64       `json:"revision"`
	ProcessingStatus string      `json:"processing_status"`
	LastErrorCode    string      `json:"last_error_code"`
}

// Phase 5A-R1 cross-aggregate convergence (ADR-0028): accepted catalog
// events per entity with their processing state, projected products
// referencing a category, and graph-change product resets. All bounded by
// entity ID (never full-table scans beyond the small catalog event set).
// Accepted events for one catalog entity (type + JSON identity key +
// identity value) with revision and processing state. Missing processing
// rows report 'missing'; callers treat missing/pending/retry as unsettled.
func (q *Queries) CatalogEntityEventRevisions(ctx context.Context, arg CatalogEntityEventRevisionsParams) ([]CatalogEntityEventRevisionsRow, error) {
	rows, err := q.db.Query(ctx, catalogEntityEventRevisions,
		arg.EventType,
		arg.Column2,
		arg.Column3,
		arg.Processor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogEntityEventRevisionsRow{}
	for rows.Next() {
		var i CatalogEntityEventRevisionsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Revision,
			&i.ProcessingStatus,
			&i.LastErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductByID = `-- name: CatalogProductByID :one
SELECT product_id, sku, name, description, top_category_id, width_cm, height_cm,
    is_active, source_revision, source_event_id, source_device_id, source_payload_hash
FROM catalog_products WHERE product_id = $1
`

type CatalogProductByIDRow struct {
	ProductID         pgtype.UUID `json:"product_id"`
	Sku               string      `json:"sku"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	TopCategoryID     pgtype.UUID `json:"top_category_id"`
	WidthCm           pgtype.Int4 `json:"width_cm"`
	HeightCm          pgtype.Int4 `json:"height_cm"`
	IsActive          bool        `json:"is_active"`
	SourceRevision    int64       `json:"source_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
}

func (q *Queries) CatalogProductByID(ctx context.Context, productID pgtype.UUID) (CatalogProductByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogProductByID, productID)
	var i CatalogProductByIDRow
	err := row.Scan(
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.TopCategoryID,
		&i.WidthCm,
		&i.HeightCm,
		&i.IsActive,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
	)
	return i, err
}

const catalogProductBySKU = `-- name: CatalogProductBySKU :one
SELECT product_id, sku, name, description, top_category_id, width_cm, height_cm,
    is_active, source_revision, source_event_id, source_device_id, source_payload_hash
FROM catalog_products WHERE sku = $1
`

type CatalogProductBySKURow struct {
	ProductID         pgtype.UUID `json:"product_id"`
	Sku               string      `json:"sku"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	TopCategoryID     pgtype.UUID `json:"top_category_id"`
	WidthCm           pgtype.Int4 `json:"width_cm"`
	HeightCm          pgtype.Int4 `json:"height_cm"`
	IsActive          bool        `json:"is_active"`
	SourceRevision    int64       `json:"source_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
}

func (q *Queries) CatalogProductBySKU(ctx context.Context, sku string) (CatalogProductBySKURow, error) {
	row := q.db.QueryRow(ctx, catalogProductBySKU, sku)
	var i CatalogProductBySKURow
	err := row.Scan(
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.TopCategoryID,
		&i.WidthCm,
		&i.HeightCm,
		&i.IsActive,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
	)
	return i, err
}

const catalogProductPrices = `-- name: CatalogProductPrices :many
SELECT currency, price_minor, cost_minor
FROM catalog_product_prices WHERE product_id = $1 ORDER BY currency
`

type CatalogProductPricesRow struct {
	Currency   string      `json:"currency"`
	PriceMinor int64       `json:"price_minor"`
	CostMinor  pgtype.Int8 `json:"cost_minor"`
}

func (q *Queries) CatalogProductPrices(ctx context.Context, productID pgtype.UUID) ([]CatalogProductPricesRow, error) {
	rows, err := q.db.Query(ctx, catalogProductPrices, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductPricesRow{}
	for rows.Next() {
		var i CatalogProductPricesRow
		if err := rows.Scan(&i.Currency, &i.PriceMinor, &i.CostMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductSubcategories = `-- name: CatalogProductSubcategories :many
SELECT category_id FROM catalog_product_subcategories
WHERE product_id = $1 ORDER BY position, category_id
`

func (q *Queries) CatalogProductSubcategories(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogProductSubcategories, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var category_id pgtype.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductTags = `-- name: CatalogProductTags :many
SELECT tag_id FROM catalog_product_tags WHERE product_id = $1 ORDER BY tag_id
`

func (q *Queries) CatalogProductTags(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogProductTags, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var tag_id pgtype.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductTranslations = `-- name: CatalogProductTranslations :many
SELECT locale, name, description
FROM catalog_product_translations WHERE product_id = $1 ORDER BY locale
`

type CatalogProductTranslationsRow struct {
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CatalogProductTranslations(ctx context.Context, productID pgtype.UUID) ([]CatalogProductTranslationsRow, error) {
	rows, err := q.db.Query(ctx, catalogProductTranslations, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductTranslationsRow{}
	for rows.Next() {
		var i CatalogProductTranslationsRow
		if err := rows.Scan(&i.Locale, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductsReferencingCategory = `-- name: CatalogProductsReferencingCategory :many
SELECT product_id FROM catalog_products WHERE top_category_id = $1
UNION
SELECT product_id FROM catalog_product_subcategories WHERE category_id = $1
`

// Projected products whose top or subcategory set references a category.
// Indexed both sides (top FK index is implicit via PK lookups; the
// subcategory side uses idx_catalog_product_subcategories_category).
func (q *Queries) CatalogProductsReferencingCategory(ctx context.Context, topCategoryID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogProductsReferencingCategory, topCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var product_id pgtype.UUID
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogTagByID = `-- name: CatalogTagByID :one
SELECT tag_id, slug, is_active, name_ar, name_en, source_revision,
    source_event_id, source_device_id, source_payload_hash
FROM catalog_tags WHERE tag_id = $1
`

type CatalogTagByIDRow struct {
	TagID             pgtype.UUID `json:"tag_id"`
	Slug              string      `json:"slug"`
	IsActive          bool        `json:"is_active"`
	NameAr            pgtype.Text `json:"name_ar"`
	NameEn            pgtype.Text `json:"name_en"`
	SourceRevision    int64       `json:"source_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
}

func (q *Queries) CatalogTagByID(ctx context.Context, tagID pgtype.UUID) (CatalogTagByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogTagByID, tagID)
	var i CatalogTagByIDRow
	err := row.Scan(
		&i.TagID,
		&i.Slug,
		&i.IsActive,
		&i.NameAr,
		&i.NameEn,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
	)
	return i, err
}

const deleteCatalogCategoryEdges = `-- name: DeleteCatalogCategoryEdges :exec
DELETE FROM catalog_category_edges WHERE child_id = $1
`

func (q *Queries) DeleteCatalogCategoryEdges(ctx context.Context, childID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogCategoryEdges, childID)
	return err
}

const deleteCatalogProductPrices = `-- name: DeleteCatalogProductPrices :exec
DELETE FROM catalog_product_prices WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductPrices(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductPrices, productID)
	return err
}

const deleteCatalogProductSubcategories = `-- name: DeleteCatalogProductSubcategories :exec
DELETE FROM catalog_product_subcategories WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductSubcategories(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductSubcategories, productID)
	return err
}

const deleteCatalogProductTags = `-- name: DeleteCatalogProductTags :exec
DELETE FROM catalog_product_tags WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductTags(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductTags, productID)
	return err
}

const deleteCatalogProductTranslations = `-- name: DeleteCatalogProductTranslations :exec
DELETE FROM catalog_product_translations WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductTranslations(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductTranslations, productID)
	return err
}

const insertCatalogCategoryEdge = `-- name: InsertCatalogCategoryEdge :exec
INSERT INTO catalog_category_edges (parent_id, child_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (parent_id, child_id) DO UPDATE SET position = excluded.position
`

type InsertCatalogCategoryEdgeParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	ChildID  pgtype.UUID `json:"child_id"`
	Position int32       `json:"position"`
}

func (q *Queries) InsertCatalogCategoryEdge(ctx context.Context, arg InsertCatalogCategoryEdgeParams) error {
	_, err := q.db.Exec(ctx, insertCatalogCategoryEdge, arg.ParentID, arg.ChildID, arg.Position)
	return err
}

const insertCatalogProductPrice = `-- name: InsertCatalogProductPrice :exec
INSERT INTO catalog_product_prices (product_id, currency, price_minor, cost_minor)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id, currency) DO UPDATE SET
    price_minor = excluded.price_minor, cost_minor = excluded.cost_minor
`

type InsertCatalogProductPriceParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	Currency   string      `json:"currency"`
	PriceMinor int64       `json:"price_minor"`
	CostMinor  pgtype.Int8 `json:"cost_minor"`
}

func (q *Queries) InsertCatalogProductPrice(ctx context.Context, arg InsertCatalogProductPriceParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductPrice,
		arg.ProductID,
		arg.Currency,
		arg.PriceMinor,
		arg.CostMinor,
	)
	return err
}

const insertCatalogProductSubcategory = `-- name: InsertCatalogProductSubcategory :exec
INSERT INTO catalog_product_subcategories (product_id, category_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (product_id, category_id) DO UPDATE SET position = excluded.position
`

type InsertCatalogProductSubcategoryParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	Position   int32       `json:"position"`
}

func (q *Queries) InsertCatalogProductSubcategory(ctx context.Context, arg InsertCatalogProductSubcategoryParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductSubcategory, arg.ProductID, arg.CategoryID, arg.Position)
	return err
}

const insertCatalogProductTag = `-- name: InsertCatalogProductTag :exec
INSERT INTO catalog_product_tags (product_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertCatalogProductTagParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

func (q *Queries) InsertCatalogProductTag(ctx context.Context, arg InsertCatalogProductTagParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductTag, arg.ProductID, arg.TagID)
	return err
}

const insertCatalogProductTranslation = `-- name: InsertCatalogProductTranslation :exec
INSERT INTO catalog_product_translations (product_id, locale, name, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id, locale) DO UPDATE SET
    name = excluded.name, description = excluded.description
`

type InsertCatalogProductTranslationParams struct {
	ProductID   pgtype.UUID `json:"product_id"`
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) InsertCatalogProductTranslation(ctx context.Context, arg InsertCatalogProductTranslationParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductTranslation,
		arg.ProductID,
		arg.Locale,
		arg.Name,
		arg.Description,
	)
	return err
}

const lockCatalogEntity = `-- name: LockCatalogEntity :exec
SELECT pg_advisory_xact_lock(hashtext('catalog:' || $1::text || ':' || $2::text))
`

type LockCatalogEntityParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

// PostgreSQL-enforced entity serialization (R04): one advisory
// transaction-scoped lock per (entity_type, entity_id), always acquired in
// globally sorted key order (see lockCatalogEntities). Concurrent
// revisions of the same entity serialize; different entities proceed in
// parallel. Released automatically at commit/rollback.
func (q *Queries) LockCatalogEntity(ctx context.Context, arg LockCatalogEntityParams) error {
	_, err := q.db.Exec(ctx, lockCatalogEntity, arg.Column1, arg.Column2)
	return err
}

const pendingCatalogEvents = `-- name: PendingCatalogEvents :many

SELECT e.event_id
FROM sync_events e
LEFT JOIN sync_event_processing p
  ON p.event_id = e.event_id AND p.processor = $1
WHERE e.event_type = $2
  AND (p.event_id IS NULL
       OR p.status = 'pending'
       OR (p.status = 'retry' AND (p.next_attempt_at IS NULL OR p.next_attempt_at <= now())))
ORDER BY e.received_at, e.event_id
LIMIT $3
`

type PendingCatalogEventsParams struct {
	Processor string `json:"processor"`
	EventType string `json:"event_type"`
	Limit     int32  `json:"limit"`
}

// Phase 5A catalog projection queries (ADR-0028). Current-state replace
// semantics: one entity row per business ID carrying its highest valid
// revision; relations replaced transactionally per revision.
// Lazy backfill discovery shared by the three catalog processors: accepted
// events with no processing row (missing), a pending row, or a due retry.
// Blocked and processed rows never return; ordering is deterministic.
func (q *Queries) PendingCatalogEvents(ctx context.Context, arg PendingCatalogEventsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, pendingCatalogEvents, arg.Processor, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var event_id pgtype.UUID
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rearmBlockedCatalogProducts = `-- name: RearmBlockedCatalogProducts :exec

UPDATE sync_event_processing AS p SET status = 'pending', next_attempt_at = NULL,
    processed_at = NULL, last_error_code = NULL, last_error_message = NULL
FROM sync_events e
WHERE p.event_id = e.event_id
  AND p.processor = 'catalog_product_projection.v1'
  AND p.status = 'blocked'
  AND p.last_error_code = 'CATALOG_INVALID_RELATION'
  AND e.event_type = 'catalog.product.snapshot.v1'
  AND NOT EXISTS (
    SELECT 1 FROM sync_events e2
    WHERE e2.event_type = 'catalog.product.snapshot.v1'
      AND e2.payload->>'product_id' = e.payload->>'product_id'
      AND (e2.payload->>'catalog_revision')::bigint > (e.payload->>'catalog_revision')::bigint
  )
  AND EXISTS (
    SELECT 1 FROM catalog_categories c
    WHERE (c.category_id::text = e.payload->>'top_category_id'
           OR c.category_id::text IN (SELECT jsonb_array_elements_text(e.payload->'subcategory_ids')))
      AND c.projected_at > p.updated_at
  )
`

// Phase 5A-R2 durable re-evaluation fallback (M01): graph-dependent
// blocked Product events become eligible again when the relevant graph
// has advanced since the block decision. The predicate is strictly
// monotonic (involved category projected_at strictly newer than the block
// updated_at), so a re-blocked event can never hot-loop: each re-arm
// requires strictly newer graph advancement. Superseded events (a newer
// accepted revision exists) are never re-armed. Terminally invalid events
// under a static graph stay blocked forever. This is the correctness path;
// the post-commit reset is only a fast wake-up.
func (q *Queries) RearmBlockedCatalogProducts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rearmBlockedCatalogProducts)
	return err
}

const resetCatalogProductRetriesForGraph = `-- name: ResetCatalogProductRetriesForGraph :exec
UPDATE sync_event_processing SET status = 'pending', next_attempt_at = NULL,
    processed_at = NULL, last_error_code = NULL, last_error_message = NULL
WHERE processor = 'catalog_product_projection.v1'
  AND status IN ('retry', 'blocked')
  AND last_error_code IN ('CATALOG_DEPENDENCY_WAIT', 'CATALOG_INVALID_RELATION')
  AND event_id IN (
    SELECT e.event_id FROM sync_events e
    WHERE e.event_type = 'catalog.product.snapshot.v1'
      AND (e.payload->>'top_category_id' = ($1::text)
           OR e.payload->'subcategory_ids' @> to_jsonb(($2::text)))
  )
`

type ResetCatalogProductRetriesForGraphParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

// Re-evaluation trigger: after a category graph commit, waiting or
// graph-blocked product events referencing the changed category become
// pending again so they re-validate against the new graph with no operator
// retry and no Retail resend. Other error codes are never touched.
func (q *Queries) ResetCatalogProductRetriesForGraph(ctx context.Context, arg ResetCatalogProductRetriesForGraphParams) error {
	_, err := q.db.Exec(ctx, resetCatalogProductRetriesForGraph, arg.Column1, arg.Column2)
	return err
}

const upsertCatalogCategory = `-- name: UpsertCatalogCategory :exec
INSERT INTO catalog_categories (
    category_id, status, name_ar, name_en,
    source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (category_id) DO UPDATE SET
    status = excluded.status, name_ar = excluded.name_ar, name_en = excluded.name_en,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at, projected_at = now()
`

type UpsertCatalogCategoryParams struct {
	CategoryID        pgtype.UUID        `json:"category_id"`
	Status            string             `json:"status"`
	NameAr            string             `json:"name_ar"`
	NameEn            pgtype.Text        `json:"name_en"`
	SourceRevision    int64              `json:"source_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
}

func (q *Queries) UpsertCatalogCategory(ctx context.Context, arg UpsertCatalogCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogCategory,
		arg.CategoryID,
		arg.Status,
		arg.NameAr,
		arg.NameEn,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
	)
	return err
}

const upsertCatalogProduct = `-- name: UpsertCatalogProduct :exec
INSERT INTO catalog_products (
    product_id, sku, name, description, top_category_id, width_cm, height_cm,
    is_active, source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (product_id) DO UPDATE SET
    sku = excluded.sku, name = excluded.name, description = excluded.description,
    top_category_id = excluded.top_category_id, width_cm = excluded.width_cm,
    height_cm = excluded.height_cm, is_active = excluded.is_active,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at, projected_at = now()
`

type UpsertCatalogProductParams struct {
	ProductID         pgtype.UUID        `json:"product_id"`
	Sku               string             `json:"sku"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	TopCategoryID     pgtype.UUID        `json:"top_category_id"`
	WidthCm           pgtype.Int4        `json:"width_cm"`
	HeightCm          pgtype.Int4        `json:"height_cm"`
	IsActive          bool               `json:"is_active"`
	SourceRevision    int64              `json:"source_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
}

func (q *Queries) UpsertCatalogProduct(ctx context.Context, arg UpsertCatalogProductParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogProduct,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.TopCategoryID,
		arg.WidthCm,
		arg.HeightCm,
		arg.IsActive,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
	)
	return err
}

const upsertCatalogTag = `-- name: UpsertCatalogTag :exec
INSERT INTO catalog_tags (
    tag_id, slug, is_active, name_ar, name_en,
    source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (tag_id) DO UPDATE SET
    slug = excluded.slug, is_active = excluded.is_active,
    name_ar = excluded.name_ar, name_en = excluded.name_en,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at, projected_at = now()
`

type UpsertCatalogTagParams struct {
	TagID             pgtype.UUID        `json:"tag_id"`
	Slug              string             `json:"slug"`
	IsActive          bool               `json:"is_active"`
	NameAr            pgtype.Text        `json:"name_ar"`
	NameEn            pgtype.Text        `json:"name_en"`
	SourceRevision    int64              `json:"source_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
}

func (q *Queries) UpsertCatalogTag(ctx context.Context, arg UpsertCatalogTagParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogTag,
		arg.TagID,
		arg.Slug,
		arg.IsActive,
		arg.NameAr,
		arg.NameEn,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
	)
	return err
}
