// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_projection.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allCatalogCategoryEdges = `-- name: AllCatalogCategoryEdges :many
SELECT parent_id, child_id FROM catalog_category_edges ORDER BY parent_id, child_id
`

type AllCatalogCategoryEdgesRow struct {
	ParentID pgtype.UUID `json:"parent_id"`
	ChildID  pgtype.UUID `json:"child_id"`
}

func (q *Queries) AllCatalogCategoryEdges(ctx context.Context) ([]AllCatalogCategoryEdgesRow, error) {
	rows, err := q.db.Query(ctx, allCatalogCategoryEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllCatalogCategoryEdgesRow{}
	for rows.Next() {
		var i AllCatalogCategoryEdgesRow
		if err := rows.Scan(&i.ParentID, &i.ChildID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogActiveProducts = `-- name: CatalogActiveProducts :many
SELECT product_id, sku, name, source_revision, source_event_id
FROM catalog_products
WHERE is_active ORDER BY sku, product_id
LIMIT $1
`

type CatalogActiveProductsRow struct {
	ProductID      pgtype.UUID `json:"product_id"`
	Sku            string      `json:"sku"`
	Name           string      `json:"name"`
	SourceRevision int64       `json:"source_revision"`
	SourceEventID  pgtype.UUID `json:"source_event_id"`
}

func (q *Queries) CatalogActiveProducts(ctx context.Context, limit int32) ([]CatalogActiveProductsRow, error) {
	rows, err := q.db.Query(ctx, catalogActiveProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogActiveProductsRow{}
	for rows.Next() {
		var i CatalogActiveProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.SourceRevision,
			&i.SourceEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogCategoryByID = `-- name: CatalogCategoryByID :one
SELECT category_id, status, name_ar, name_en, source_revision,
    source_event_id, source_device_id, source_payload_hash
FROM catalog_categories WHERE category_id = $1
`

type CatalogCategoryByIDRow struct {
	CategoryID        pgtype.UUID `json:"category_id"`
	Status            string      `json:"status"`
	NameAr            string      `json:"name_ar"`
	NameEn            pgtype.Text `json:"name_en"`
	SourceRevision    int64       `json:"source_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
}

func (q *Queries) CatalogCategoryByID(ctx context.Context, categoryID pgtype.UUID) (CatalogCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogCategoryByID, categoryID)
	var i CatalogCategoryByIDRow
	err := row.Scan(
		&i.CategoryID,
		&i.Status,
		&i.NameAr,
		&i.NameEn,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
	)
	return i, err
}

const catalogCategoryParents = `-- name: CatalogCategoryParents :many
SELECT parent_id FROM catalog_category_edges WHERE child_id = $1 ORDER BY position, parent_id
`

func (q *Queries) CatalogCategoryParents(ctx context.Context, childID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogCategoryParents, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var parent_id pgtype.UUID
		if err := rows.Scan(&parent_id); err != nil {
			return nil, err
		}
		items = append(items, parent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductByID = `-- name: CatalogProductByID :one
SELECT product_id, sku, name, description, top_category_id, width_cm, height_cm,
    is_active, source_revision, source_event_id, source_device_id, source_payload_hash
FROM catalog_products WHERE product_id = $1
`

type CatalogProductByIDRow struct {
	ProductID         pgtype.UUID `json:"product_id"`
	Sku               string      `json:"sku"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	TopCategoryID     pgtype.UUID `json:"top_category_id"`
	WidthCm           pgtype.Int4 `json:"width_cm"`
	HeightCm          pgtype.Int4 `json:"height_cm"`
	IsActive          bool        `json:"is_active"`
	SourceRevision    int64       `json:"source_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
}

func (q *Queries) CatalogProductByID(ctx context.Context, productID pgtype.UUID) (CatalogProductByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogProductByID, productID)
	var i CatalogProductByIDRow
	err := row.Scan(
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.TopCategoryID,
		&i.WidthCm,
		&i.HeightCm,
		&i.IsActive,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
	)
	return i, err
}

const catalogProductBySKU = `-- name: CatalogProductBySKU :one
SELECT product_id, sku, name, description, top_category_id, width_cm, height_cm,
    is_active, source_revision, source_event_id, source_device_id, source_payload_hash
FROM catalog_products WHERE sku = $1
`

type CatalogProductBySKURow struct {
	ProductID         pgtype.UUID `json:"product_id"`
	Sku               string      `json:"sku"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	TopCategoryID     pgtype.UUID `json:"top_category_id"`
	WidthCm           pgtype.Int4 `json:"width_cm"`
	HeightCm          pgtype.Int4 `json:"height_cm"`
	IsActive          bool        `json:"is_active"`
	SourceRevision    int64       `json:"source_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
}

func (q *Queries) CatalogProductBySKU(ctx context.Context, sku string) (CatalogProductBySKURow, error) {
	row := q.db.QueryRow(ctx, catalogProductBySKU, sku)
	var i CatalogProductBySKURow
	err := row.Scan(
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.TopCategoryID,
		&i.WidthCm,
		&i.HeightCm,
		&i.IsActive,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
	)
	return i, err
}

const catalogProductPrices = `-- name: CatalogProductPrices :many
SELECT currency, price_minor, cost_minor
FROM catalog_product_prices WHERE product_id = $1 ORDER BY currency
`

type CatalogProductPricesRow struct {
	Currency   string      `json:"currency"`
	PriceMinor int64       `json:"price_minor"`
	CostMinor  pgtype.Int8 `json:"cost_minor"`
}

func (q *Queries) CatalogProductPrices(ctx context.Context, productID pgtype.UUID) ([]CatalogProductPricesRow, error) {
	rows, err := q.db.Query(ctx, catalogProductPrices, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductPricesRow{}
	for rows.Next() {
		var i CatalogProductPricesRow
		if err := rows.Scan(&i.Currency, &i.PriceMinor, &i.CostMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductSubcategories = `-- name: CatalogProductSubcategories :many
SELECT category_id FROM catalog_product_subcategories
WHERE product_id = $1 ORDER BY position, category_id
`

func (q *Queries) CatalogProductSubcategories(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogProductSubcategories, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var category_id pgtype.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductTags = `-- name: CatalogProductTags :many
SELECT tag_id FROM catalog_product_tags WHERE product_id = $1 ORDER BY tag_id
`

func (q *Queries) CatalogProductTags(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogProductTags, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var tag_id pgtype.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductTranslations = `-- name: CatalogProductTranslations :many
SELECT locale, name, description
FROM catalog_product_translations WHERE product_id = $1 ORDER BY locale
`

type CatalogProductTranslationsRow struct {
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CatalogProductTranslations(ctx context.Context, productID pgtype.UUID) ([]CatalogProductTranslationsRow, error) {
	rows, err := q.db.Query(ctx, catalogProductTranslations, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductTranslationsRow{}
	for rows.Next() {
		var i CatalogProductTranslationsRow
		if err := rows.Scan(&i.Locale, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogTagByID = `-- name: CatalogTagByID :one
SELECT tag_id, slug, is_active, name_ar, name_en, source_revision,
    source_event_id, source_device_id, source_payload_hash
FROM catalog_tags WHERE tag_id = $1
`

type CatalogTagByIDRow struct {
	TagID             pgtype.UUID `json:"tag_id"`
	Slug              string      `json:"slug"`
	IsActive          bool        `json:"is_active"`
	NameAr            pgtype.Text `json:"name_ar"`
	NameEn            pgtype.Text `json:"name_en"`
	SourceRevision    int64       `json:"source_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
}

func (q *Queries) CatalogTagByID(ctx context.Context, tagID pgtype.UUID) (CatalogTagByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogTagByID, tagID)
	var i CatalogTagByIDRow
	err := row.Scan(
		&i.TagID,
		&i.Slug,
		&i.IsActive,
		&i.NameAr,
		&i.NameEn,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
	)
	return i, err
}

const deleteCatalogCategoryEdges = `-- name: DeleteCatalogCategoryEdges :exec
DELETE FROM catalog_category_edges WHERE child_id = $1
`

func (q *Queries) DeleteCatalogCategoryEdges(ctx context.Context, childID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogCategoryEdges, childID)
	return err
}

const deleteCatalogProductPrices = `-- name: DeleteCatalogProductPrices :exec
DELETE FROM catalog_product_prices WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductPrices(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductPrices, productID)
	return err
}

const deleteCatalogProductSubcategories = `-- name: DeleteCatalogProductSubcategories :exec
DELETE FROM catalog_product_subcategories WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductSubcategories(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductSubcategories, productID)
	return err
}

const deleteCatalogProductTags = `-- name: DeleteCatalogProductTags :exec
DELETE FROM catalog_product_tags WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductTags(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductTags, productID)
	return err
}

const deleteCatalogProductTranslations = `-- name: DeleteCatalogProductTranslations :exec
DELETE FROM catalog_product_translations WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductTranslations(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductTranslations, productID)
	return err
}

const insertCatalogCategoryEdge = `-- name: InsertCatalogCategoryEdge :exec
INSERT INTO catalog_category_edges (parent_id, child_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (parent_id, child_id) DO UPDATE SET position = excluded.position
`

type InsertCatalogCategoryEdgeParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	ChildID  pgtype.UUID `json:"child_id"`
	Position int32       `json:"position"`
}

func (q *Queries) InsertCatalogCategoryEdge(ctx context.Context, arg InsertCatalogCategoryEdgeParams) error {
	_, err := q.db.Exec(ctx, insertCatalogCategoryEdge, arg.ParentID, arg.ChildID, arg.Position)
	return err
}

const insertCatalogProductPrice = `-- name: InsertCatalogProductPrice :exec
INSERT INTO catalog_product_prices (product_id, currency, price_minor, cost_minor)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id, currency) DO UPDATE SET
    price_minor = excluded.price_minor, cost_minor = excluded.cost_minor
`

type InsertCatalogProductPriceParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	Currency   string      `json:"currency"`
	PriceMinor int64       `json:"price_minor"`
	CostMinor  pgtype.Int8 `json:"cost_minor"`
}

func (q *Queries) InsertCatalogProductPrice(ctx context.Context, arg InsertCatalogProductPriceParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductPrice,
		arg.ProductID,
		arg.Currency,
		arg.PriceMinor,
		arg.CostMinor,
	)
	return err
}

const insertCatalogProductSubcategory = `-- name: InsertCatalogProductSubcategory :exec
INSERT INTO catalog_product_subcategories (product_id, category_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (product_id, category_id) DO UPDATE SET position = excluded.position
`

type InsertCatalogProductSubcategoryParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	Position   int32       `json:"position"`
}

func (q *Queries) InsertCatalogProductSubcategory(ctx context.Context, arg InsertCatalogProductSubcategoryParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductSubcategory, arg.ProductID, arg.CategoryID, arg.Position)
	return err
}

const insertCatalogProductTag = `-- name: InsertCatalogProductTag :exec
INSERT INTO catalog_product_tags (product_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertCatalogProductTagParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

func (q *Queries) InsertCatalogProductTag(ctx context.Context, arg InsertCatalogProductTagParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductTag, arg.ProductID, arg.TagID)
	return err
}

const insertCatalogProductTranslation = `-- name: InsertCatalogProductTranslation :exec
INSERT INTO catalog_product_translations (product_id, locale, name, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id, locale) DO UPDATE SET
    name = excluded.name, description = excluded.description
`

type InsertCatalogProductTranslationParams struct {
	ProductID   pgtype.UUID `json:"product_id"`
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) InsertCatalogProductTranslation(ctx context.Context, arg InsertCatalogProductTranslationParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductTranslation,
		arg.ProductID,
		arg.Locale,
		arg.Name,
		arg.Description,
	)
	return err
}

const pendingCatalogEvents = `-- name: PendingCatalogEvents :many

SELECT e.event_id
FROM sync_events e
LEFT JOIN sync_event_processing p
  ON p.event_id = e.event_id AND p.processor = $1
WHERE e.event_type = $2
  AND (p.event_id IS NULL
       OR p.status = 'pending'
       OR (p.status = 'retry' AND (p.next_attempt_at IS NULL OR p.next_attempt_at <= now())))
ORDER BY e.received_at, e.event_id
LIMIT $3
`

type PendingCatalogEventsParams struct {
	Processor string `json:"processor"`
	EventType string `json:"event_type"`
	Limit     int32  `json:"limit"`
}

// Phase 5A catalog projection queries (ADR-0028). Current-state replace
// semantics: one entity row per business ID carrying its highest valid
// revision; relations replaced transactionally per revision.
// Lazy backfill discovery shared by the three catalog processors: accepted
// events with no processing row (missing), a pending row, or a due retry.
// Blocked and processed rows never return; ordering is deterministic.
func (q *Queries) PendingCatalogEvents(ctx context.Context, arg PendingCatalogEventsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, pendingCatalogEvents, arg.Processor, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var event_id pgtype.UUID
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCatalogCategory = `-- name: UpsertCatalogCategory :exec
INSERT INTO catalog_categories (
    category_id, status, name_ar, name_en,
    source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (category_id) DO UPDATE SET
    status = excluded.status, name_ar = excluded.name_ar, name_en = excluded.name_en,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at, projected_at = now()
`

type UpsertCatalogCategoryParams struct {
	CategoryID        pgtype.UUID        `json:"category_id"`
	Status            string             `json:"status"`
	NameAr            string             `json:"name_ar"`
	NameEn            pgtype.Text        `json:"name_en"`
	SourceRevision    int64              `json:"source_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
}

func (q *Queries) UpsertCatalogCategory(ctx context.Context, arg UpsertCatalogCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogCategory,
		arg.CategoryID,
		arg.Status,
		arg.NameAr,
		arg.NameEn,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
	)
	return err
}

const upsertCatalogProduct = `-- name: UpsertCatalogProduct :exec
INSERT INTO catalog_products (
    product_id, sku, name, description, top_category_id, width_cm, height_cm,
    is_active, source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (product_id) DO UPDATE SET
    sku = excluded.sku, name = excluded.name, description = excluded.description,
    top_category_id = excluded.top_category_id, width_cm = excluded.width_cm,
    height_cm = excluded.height_cm, is_active = excluded.is_active,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at, projected_at = now()
`

type UpsertCatalogProductParams struct {
	ProductID         pgtype.UUID        `json:"product_id"`
	Sku               string             `json:"sku"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	TopCategoryID     pgtype.UUID        `json:"top_category_id"`
	WidthCm           pgtype.Int4        `json:"width_cm"`
	HeightCm          pgtype.Int4        `json:"height_cm"`
	IsActive          bool               `json:"is_active"`
	SourceRevision    int64              `json:"source_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
}

func (q *Queries) UpsertCatalogProduct(ctx context.Context, arg UpsertCatalogProductParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogProduct,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.TopCategoryID,
		arg.WidthCm,
		arg.HeightCm,
		arg.IsActive,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
	)
	return err
}

const upsertCatalogTag = `-- name: UpsertCatalogTag :exec
INSERT INTO catalog_tags (
    tag_id, slug, is_active, name_ar, name_en,
    source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (tag_id) DO UPDATE SET
    slug = excluded.slug, is_active = excluded.is_active,
    name_ar = excluded.name_ar, name_en = excluded.name_en,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at, projected_at = now()
`

type UpsertCatalogTagParams struct {
	TagID             pgtype.UUID        `json:"tag_id"`
	Slug              string             `json:"slug"`
	IsActive          bool               `json:"is_active"`
	NameAr            pgtype.Text        `json:"name_ar"`
	NameEn            pgtype.Text        `json:"name_en"`
	SourceRevision    int64              `json:"source_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
}

func (q *Queries) UpsertCatalogTag(ctx context.Context, arg UpsertCatalogTagParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogTag,
		arg.TagID,
		arg.Slug,
		arg.IsActive,
		arg.NameAr,
		arg.NameEn,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
	)
	return err
}
