// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_projection.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allCatalogCategoryEdges = `-- name: AllCatalogCategoryEdges :many
SELECT parent_id, child_id FROM catalog_category_edges ORDER BY parent_id, child_id
`

type AllCatalogCategoryEdgesRow struct {
	ParentID pgtype.UUID `json:"parent_id"`
	ChildID  pgtype.UUID `json:"child_id"`
}

func (q *Queries) AllCatalogCategoryEdges(ctx context.Context) ([]AllCatalogCategoryEdgesRow, error) {
	rows, err := q.db.Query(ctx, allCatalogCategoryEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllCatalogCategoryEdgesRow{}
	for rows.Next() {
		var i AllCatalogCategoryEdgesRow
		if err := rows.Scan(&i.ParentID, &i.ChildID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogActiveProducts = `-- name: CatalogActiveProducts :many
SELECT product_id, name, source_revision, source_event_id
FROM catalog_products
WHERE is_active ORDER BY product_id
LIMIT $1
`

type CatalogActiveProductsRow struct {
	ProductID      pgtype.UUID `json:"product_id"`
	Name           string      `json:"name"`
	SourceRevision int64       `json:"source_revision"`
	SourceEventID  pgtype.UUID `json:"source_event_id"`
}

// Phase 17-R0: Product has no SKU (ADR-0049); deterministic product_id
// ordering replaces the retired SKU ordering.
func (q *Queries) CatalogActiveProducts(ctx context.Context, limit int32) ([]CatalogActiveProductsRow, error) {
	rows, err := q.db.Query(ctx, catalogActiveProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogActiveProductsRow{}
	for rows.Next() {
		var i CatalogActiveProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.SourceRevision,
			&i.SourceEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogCategoryByID = `-- name: CatalogCategoryByID :one
SELECT category_id, status, name_ar, name_en, online_enabled, source_revision,
    source_event_id, source_device_id, source_payload_hash, store_id
FROM catalog_categories WHERE category_id = $1
`

type CatalogCategoryByIDRow struct {
	CategoryID        pgtype.UUID `json:"category_id"`
	Status            string      `json:"status"`
	NameAr            string      `json:"name_ar"`
	NameEn            pgtype.Text `json:"name_en"`
	OnlineEnabled     bool        `json:"online_enabled"`
	SourceRevision    int64       `json:"source_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
	StoreID           pgtype.UUID `json:"store_id"`
}

func (q *Queries) CatalogCategoryByID(ctx context.Context, categoryID pgtype.UUID) (CatalogCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogCategoryByID, categoryID)
	var i CatalogCategoryByIDRow
	err := row.Scan(
		&i.CategoryID,
		&i.Status,
		&i.NameAr,
		&i.NameEn,
		&i.OnlineEnabled,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
		&i.StoreID,
	)
	return i, err
}

const catalogCategoryChildStores = `-- name: CatalogCategoryChildStores :many
SELECT c.store_id
FROM catalog_category_edges e
JOIN catalog_categories c ON c.category_id = e.child_id
WHERE e.parent_id = $1 AND c.store_id IS NOT NULL
`

// Proven Store ownership of a category's existing children edges.
func (q *Queries) CatalogCategoryChildStores(ctx context.Context, parentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogCategoryChildStores, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var store_id pgtype.UUID
		if err := rows.Scan(&store_id); err != nil {
			return nil, err
		}
		items = append(items, store_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogCategoryParents = `-- name: CatalogCategoryParents :many
SELECT parent_id FROM catalog_category_edges WHERE child_id = $1 ORDER BY position, parent_id
`

func (q *Queries) CatalogCategoryParents(ctx context.Context, childID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogCategoryParents, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var parent_id pgtype.UUID
		if err := rows.Scan(&parent_id); err != nil {
			return nil, err
		}
		items = append(items, parent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogCategoryProductStores = `-- name: CatalogCategoryProductStores :many
SELECT p.store_id FROM catalog_products p
WHERE p.top_category_id = $1 AND p.store_id IS NOT NULL
UNION
SELECT p.store_id
FROM catalog_product_subcategories s
JOIN catalog_products p ON p.product_id = s.product_id
WHERE s.category_id = $1 AND p.store_id IS NOT NULL
`

// Proven Store ownership of products referencing a category as top or
// subcategory.
func (q *Queries) CatalogCategoryProductStores(ctx context.Context, topCategoryID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogCategoryProductStores, topCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var store_id pgtype.UUID
		if err := rows.Scan(&store_id); err != nil {
			return nil, err
		}
		items = append(items, store_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogDefaultCategoryAlgorithm = `-- name: CatalogDefaultCategoryAlgorithm :one
SELECT COALESCE(default_algorithm, 0) FROM catalog_categories
WHERE category_id = $1 AND store_id = $2
`

type CatalogDefaultCategoryAlgorithmParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	StoreID    pgtype.UUID `json:"store_id"`
}

// Phase 9-R2 recovery: the canonical-identity algorithm version of a
// shared default category's existing row for one Store (0 = none).
func (q *Queries) CatalogDefaultCategoryAlgorithm(ctx context.Context, arg CatalogDefaultCategoryAlgorithmParams) (int16, error) {
	row := q.db.QueryRow(ctx, catalogDefaultCategoryAlgorithm, arg.CategoryID, arg.StoreID)
	var default_algorithm int16
	err := row.Scan(&default_algorithm)
	return default_algorithm, err
}

const catalogDefaultTagAlgorithm = `-- name: CatalogDefaultTagAlgorithm :one
SELECT COALESCE(default_algorithm, 0) FROM catalog_tags
WHERE tag_id = $1 AND store_id = $2
`

type CatalogDefaultTagAlgorithmParams struct {
	TagID   pgtype.UUID `json:"tag_id"`
	StoreID pgtype.UUID `json:"store_id"`
}

// Phase 9-R2 recovery: see CatalogDefaultCategoryAlgorithm.
func (q *Queries) CatalogDefaultTagAlgorithm(ctx context.Context, arg CatalogDefaultTagAlgorithmParams) (int16, error) {
	row := q.db.QueryRow(ctx, catalogDefaultTagAlgorithm, arg.TagID, arg.StoreID)
	var default_algorithm int16
	err := row.Scan(&default_algorithm)
	return default_algorithm, err
}

const catalogEntityEventRevisions = `-- name: CatalogEntityEventRevisions :many

SELECT e.event_id,
    (e.payload->>($5::text))::bigint AS revision,
    COALESCE(p.status, 'missing') AS processing_status,
    COALESCE(p.last_error_code, '') AS last_error_code
FROM sync_events e
LEFT JOIN sync_event_processing p
  ON p.event_id = e.event_id AND p.processor = $4
WHERE (e.event_type = $1
       OR ($1 IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2')
           AND e.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2'))
       OR ($1 IN ('catalog.product.snapshot.v1','catalog.product.snapshot.v2')
           AND e.event_type IN ('catalog.product.snapshot.v1','catalog.product.snapshot.v2')))
  AND e.payload->>($2::text) = ($3::text)
  AND (CASE WHEN $6::boolean
       THEN e.store_id IS NOT DISTINCT FROM $7::uuid
       ELSE $7::uuid IS NULL OR e.store_id IS NULL
            OR e.store_id = $7::uuid END)
`

type CatalogEntityEventRevisionsParams struct {
	EventType          string      `json:"event_type"`
	Column2            string      `json:"column_2"`
	Column3            string      `json:"column_3"`
	Processor          string      `json:"processor"`
	Column5            string      `json:"column_5"`
	StoreScopedDefault bool        `json:"store_scoped_default"`
	StoreID            pgtype.UUID `json:"store_id"`
}

type CatalogEntityEventRevisionsRow struct {
	EventID          pgtype.UUID `json:"event_id"`
	Revision         int64       `json:"revision"`
	ProcessingStatus string      `json:"processing_status"`
	LastErrorCode    string      `json:"last_error_code"`
}

// Phase 5A-R1 cross-aggregate convergence (ADR-0028): accepted catalog
// events per entity with their processing state, projected products
// referencing a category, and graph-change product resets. All bounded by
// entity ID (never full-table scans beyond the small catalog event set).
// Accepted events for one catalog entity (type + JSON identity key +
// identity value) with revision and processing state. Missing processing
// rows report 'missing'; callers treat missing/pending/retry as unsettled.
// The revision key is a parameter because the policy stream versions on
// sales_policy_revision while category/tag/product version on
// catalog_revision.
func (q *Queries) CatalogEntityEventRevisions(ctx context.Context, arg CatalogEntityEventRevisionsParams) ([]CatalogEntityEventRevisionsRow, error) {
	rows, err := q.db.Query(ctx, catalogEntityEventRevisions,
		arg.EventType,
		arg.Column2,
		arg.Column3,
		arg.Processor,
		arg.Column5,
		arg.StoreScopedDefault,
		arg.StoreID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogEntityEventRevisionsRow{}
	for rows.Next() {
		var i CatalogEntityEventRevisionsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Revision,
			&i.ProcessingStatus,
			&i.LastErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductByID = `-- name: CatalogProductByID :one
SELECT product_id, name, description, top_category_id, width_cm, height_cm,
    is_active, product_type_id, source_revision, source_event_id, source_device_id, source_payload_hash, store_id,
    configuration_revision
FROM catalog_products WHERE product_id = $1
`

type CatalogProductByIDRow struct {
	ProductID             pgtype.UUID `json:"product_id"`
	Name                  string      `json:"name"`
	Description           pgtype.Text `json:"description"`
	TopCategoryID         pgtype.UUID `json:"top_category_id"`
	WidthCm               pgtype.Int4 `json:"width_cm"`
	HeightCm              pgtype.Int4 `json:"height_cm"`
	IsActive              bool        `json:"is_active"`
	ProductTypeID         pgtype.UUID `json:"product_type_id"`
	SourceRevision        int64       `json:"source_revision"`
	SourceEventID         pgtype.UUID `json:"source_event_id"`
	SourceDeviceID        pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash     []byte      `json:"source_payload_hash"`
	StoreID               pgtype.UUID `json:"store_id"`
	ConfigurationRevision int64       `json:"configuration_revision"`
}

func (q *Queries) CatalogProductByID(ctx context.Context, productID pgtype.UUID) (CatalogProductByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogProductByID, productID)
	var i CatalogProductByIDRow
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.TopCategoryID,
		&i.WidthCm,
		&i.HeightCm,
		&i.IsActive,
		&i.ProductTypeID,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
		&i.StoreID,
		&i.ConfigurationRevision,
	)
	return i, err
}

const catalogProductDependentStores = `-- name: CatalogProductDependentStores :many

SELECT i.store_id FROM catalog_product_inventory i
WHERE i.product_id = $1 AND i.store_id IS NOT NULL
UNION
SELECT pol.store_id FROM catalog_product_sales_policies pol
WHERE pol.product_id = $1 AND pol.store_id IS NOT NULL
UNION
SELECT m.store_id FROM commerce_product_mappings m
WHERE m.product_id = $1 AND m.store_id IS NOT NULL
UNION
SELECT v.store_id FROM catalog_product_variants v
WHERE v.product_id = $1 AND v.store_id IS NOT NULL
UNION
SELECT vi.store_id FROM catalog_product_variant_inventory vi
WHERE vi.product_id = $1 AND vi.store_id IS NOT NULL
UNION
SELECT vm.store_id FROM commerce_product_variant_mappings vm
WHERE vm.product_id = $1 AND vm.store_id IS NOT NULL
`

// Phase 9-R1 F02: complete ownership-relationship validation before a
// current-state aggregate may adopt a Store. Each query returns the
// proven stores of the durable dependents/edges that must agree with the
// adopting Store; NULL (legacy) dependents are wildcards and omitted.
// Proven Store ownership of a product's inventory, sales policy, and
// provider mapping. Adopting a product into a Store that already has a
// dependent owned by another proven Store is rejected instead of
// committing a contradictory durable relationship.
// Phase 17: variant rows and their inventory/mappings are dependents of
// the product too (SKU/inventory ownership moved to variant).
func (q *Queries) CatalogProductDependentStores(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogProductDependentStores, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var store_id pgtype.UUID
		if err := rows.Scan(&store_id); err != nil {
			return nil, err
		}
		items = append(items, store_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductPrices = `-- name: CatalogProductPrices :many
SELECT currency, price_minor, cost_minor
FROM catalog_product_prices WHERE product_id = $1 ORDER BY currency
`

type CatalogProductPricesRow struct {
	Currency   string      `json:"currency"`
	PriceMinor int64       `json:"price_minor"`
	CostMinor  pgtype.Int8 `json:"cost_minor"`
}

func (q *Queries) CatalogProductPrices(ctx context.Context, productID pgtype.UUID) ([]CatalogProductPricesRow, error) {
	rows, err := q.db.Query(ctx, catalogProductPrices, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductPricesRow{}
	for rows.Next() {
		var i CatalogProductPricesRow
		if err := rows.Scan(&i.Currency, &i.PriceMinor, &i.CostMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductSubcategories = `-- name: CatalogProductSubcategories :many
SELECT category_id FROM catalog_product_subcategories
WHERE product_id = $1 ORDER BY position, category_id
`

func (q *Queries) CatalogProductSubcategories(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogProductSubcategories, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var category_id pgtype.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductTags = `-- name: CatalogProductTags :many
SELECT tag_id FROM catalog_product_tags WHERE product_id = $1 ORDER BY tag_id
`

func (q *Queries) CatalogProductTags(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogProductTags, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var tag_id pgtype.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductTranslations = `-- name: CatalogProductTranslations :many
SELECT locale, name, description
FROM catalog_product_translations WHERE product_id = $1 ORDER BY locale
`

type CatalogProductTranslationsRow struct {
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CatalogProductTranslations(ctx context.Context, productID pgtype.UUID) ([]CatalogProductTranslationsRow, error) {
	rows, err := q.db.Query(ctx, catalogProductTranslations, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductTranslationsRow{}
	for rows.Next() {
		var i CatalogProductTranslationsRow
		if err := rows.Scan(&i.Locale, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductsReferencingCategory = `-- name: CatalogProductsReferencingCategory :many
SELECT product_id FROM catalog_products WHERE top_category_id = $1
UNION
SELECT product_id FROM catalog_product_subcategories WHERE category_id = $1
`

// Projected products whose top or subcategory set references a category.
// Indexed both sides (top FK index is implicit via PK lookups; the
// subcategory side uses idx_catalog_product_subcategories_category).
func (q *Queries) CatalogProductsReferencingCategory(ctx context.Context, topCategoryID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogProductsReferencingCategory, topCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var product_id pgtype.UUID
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogTagByID = `-- name: CatalogTagByID :one
SELECT tag_id, slug, is_active, name_ar, name_en, source_revision,
    source_event_id, source_device_id, source_payload_hash, store_id
FROM catalog_tags WHERE tag_id = $1
`

type CatalogTagByIDRow struct {
	TagID             pgtype.UUID `json:"tag_id"`
	Slug              string      `json:"slug"`
	IsActive          bool        `json:"is_active"`
	NameAr            pgtype.Text `json:"name_ar"`
	NameEn            pgtype.Text `json:"name_en"`
	SourceRevision    int64       `json:"source_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
	StoreID           pgtype.UUID `json:"store_id"`
}

func (q *Queries) CatalogTagByID(ctx context.Context, tagID pgtype.UUID) (CatalogTagByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogTagByID, tagID)
	var i CatalogTagByIDRow
	err := row.Scan(
		&i.TagID,
		&i.Slug,
		&i.IsActive,
		&i.NameAr,
		&i.NameEn,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
		&i.StoreID,
	)
	return i, err
}

const catalogTagProductStores = `-- name: CatalogTagProductStores :many
SELECT p.store_id
FROM catalog_product_tags t
JOIN catalog_products p ON p.product_id = t.product_id
WHERE t.tag_id = $1 AND p.store_id IS NOT NULL
`

// Proven Store ownership of products attached to a tag.
func (q *Queries) CatalogTagProductStores(ctx context.Context, tagID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogTagProductStores, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var store_id pgtype.UUID
		if err := rows.Scan(&store_id); err != nil {
			return nil, err
		}
		items = append(items, store_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const defaultCatalogRecoveryCandidates = `-- name: DefaultCatalogRecoveryCandidates :many
WITH defaults AS (
 SELECT DISTINCT ON (e.store_id,CASE WHEN e.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2') THEN 'catalog.category.snapshot' ELSE e.event_type END,COALESCE(e.payload->>'category_id',e.payload->>'tag_id'))
        e.event_id,e.event_type,e.store_id,e.payload,p.processor,e.received_at
 FROM sync_events e JOIN sync_event_processing p ON p.event_id=e.event_id
 WHERE e.store_id IS NOT NULL AND (
  (e.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2') AND p.processor='catalog_category_projection.v1'
   AND e.payload->>'category_id'=ANY($1::text[])) OR
  (e.event_type='catalog.tag.snapshot.v1' AND p.processor='catalog_tag_projection.v1'
   AND e.payload->>'tag_id'=ANY($2::text[])))
 AND (p.status='processed' OR (p.status='blocked'
  AND p.last_error_code IN ('STORE_SCOPE_CONFLICT','CATALOG_REVISION_CONFLICT')
  AND p.last_error_message IN ('category owned by another store','tag owned by another store','equal revision with conflicting state')
  AND NOT EXISTS (SELECT 1 FROM sync_events own JOIN sync_event_processing settled
       ON settled.event_id=own.event_id AND settled.processor=p.processor AND settled.status='processed'
       WHERE own.store_id=e.store_id AND (own.event_type=e.event_type OR (e.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2') AND own.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2')))
         AND COALESCE(own.payload->>'category_id',own.payload->>'tag_id')=COALESCE(e.payload->>'category_id',e.payload->>'tag_id')
         AND (own.payload->>'catalog_revision')::bigint >= (e.payload->>'catalog_revision')::bigint)
  AND (EXISTS(SELECT 1 FROM catalog_categories c JOIN sync_events s ON s.event_id=c.source_event_id
        WHERE c.category_id::text=e.payload->>'category_id' AND s.store_id IS NOT NULL AND s.store_id<>e.store_id)
    OR EXISTS(SELECT 1 FROM catalog_tags t JOIN sync_events s ON s.event_id=t.source_event_id
        WHERE t.tag_id::text=e.payload->>'tag_id' AND s.store_id IS NOT NULL AND s.store_id<>e.store_id))
  AND NOT EXISTS(SELECT 1 FROM catalog_categories c JOIN sync_events s ON s.event_id=c.source_event_id
        WHERE c.default_algorithm=1 AND c.store_id=e.store_id AND s.payload->>'category_id'=e.payload->>'category_id')
  AND NOT EXISTS(SELECT 1 FROM catalog_tags t JOIN sync_events s ON s.event_id=t.source_event_id
        WHERE t.default_algorithm=1 AND t.store_id=e.store_id AND s.payload->>'tag_id'=e.payload->>'tag_id')))
 ORDER BY e.store_id,CASE WHEN e.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2') THEN 'catalog.category.snapshot' ELSE e.event_type END,COALESCE(e.payload->>'category_id',e.payload->>'tag_id'),
          (e.payload->>'catalog_revision')::bigint DESC,e.received_at DESC,e.event_id DESC
), candidates AS (
 SELECT d.event_id,d.processor,d.received_at FROM defaults d WHERE
  (d.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2') AND (
   NOT EXISTS(SELECT 1 FROM catalog_categories c JOIN sync_events s ON s.event_id=c.source_event_id
     WHERE c.default_algorithm=1 AND c.store_id=d.store_id AND s.payload->>'category_id'=d.payload->>'category_id'
       AND c.source_revision >= (d.payload->>'catalog_revision')::bigint)
   OR EXISTS(SELECT 1 FROM catalog_categories c WHERE c.category_id::text=d.payload->>'category_id' AND c.store_id=d.store_id AND c.default_algorithm=0)))
  OR (d.event_type='catalog.tag.snapshot.v1' AND (
   NOT EXISTS(SELECT 1 FROM catalog_tags t JOIN sync_events s ON s.event_id=t.source_event_id
     WHERE t.default_algorithm=1 AND t.store_id=d.store_id AND s.payload->>'tag_id'=d.payload->>'tag_id'
       AND t.source_revision >= (d.payload->>'catalog_revision')::bigint)
   OR EXISTS(SELECT 1 FROM catalog_tags t WHERE t.tag_id::text=d.payload->>'tag_id' AND t.store_id=d.store_id AND t.default_algorithm=0)))
 UNION
 -- R2 tried to insert the canonical Tag while the same Store's older raw
 -- default still occupied its slug. The retained raw source proves the
 -- obsolete collision even after retirement (algorithm 2). Other slug
 -- owners, equal revisions and unbound/custom identities never qualify.
 SELECT e.event_id,p.processor,e.received_at
 FROM sync_events e JOIN sync_event_processing p ON p.event_id=e.event_id
 JOIN catalog_tags raw ON raw.tag_id::text=e.payload->>'tag_id'
 JOIN sync_events source ON source.event_id=raw.source_event_id
 JOIN sync_event_processing settled ON settled.event_id=source.event_id
   AND settled.processor='catalog_tag_projection.v1' AND settled.status='processed'
 WHERE e.event_type='catalog.tag.snapshot.v1' AND e.store_id IS NOT NULL
 AND p.processor='catalog_tag_projection.v1' AND p.status='blocked'
 AND p.last_error_code='CATALOG_REVISION_CONFLICT' AND p.last_error_message='tag identity collision'
 AND e.payload->>'tag_id'=ANY($2::text[])
 AND source.event_type=e.event_type AND source.store_id=e.store_id
 AND source.payload->>'tag_id'=e.payload->>'tag_id'
 AND raw.default_algorithm IN (0,2)
 AND ((raw.default_algorithm=0 AND raw.store_id=e.store_id)
   OR (raw.default_algorithm=2 AND raw.store_id IS NULL))
 AND raw.slug=e.payload->>'slug' AND source.payload->>'slug'=raw.slug
 AND raw.source_revision=(source.payload->>'catalog_revision')::bigint
 AND raw.source_revision < (e.payload->>'catalog_revision')::bigint
 AND NOT EXISTS (
  SELECT 1 FROM catalog_tags other WHERE other.store_id=e.store_id AND other.slug=raw.slug
    AND other.tag_id<>raw.tag_id AND NOT (other.default_algorithm=1 AND EXISTS (
      SELECT 1 FROM sync_events canonical WHERE canonical.event_id=other.source_event_id
      AND canonical.store_id=e.store_id AND canonical.event_type=e.event_type
      AND canonical.payload->>'tag_id'=e.payload->>'tag_id')))
 AND NOT EXISTS (
  SELECT 1 FROM sync_events own JOIN sync_event_processing terminal ON terminal.event_id=own.event_id
  AND terminal.processor=p.processor AND terminal.status='processed'
  WHERE own.store_id=e.store_id AND (own.event_type=e.event_type OR (e.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2') AND own.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2')))
  AND own.payload->>'tag_id'=e.payload->>'tag_id'
  AND own.payload->>'catalog_revision'=e.payload->>'catalog_revision'
  AND own.payload<>e.payload)
 UNION
 SELECT e.event_id,p.processor,e.received_at FROM catalog_categories c
 JOIN sync_events e ON e.event_id=c.source_event_id AND e.store_id=c.store_id
 JOIN sync_event_processing p ON p.event_id=e.event_id AND p.processor='catalog_category_projection.v1'
 WHERE p.status='processed' AND EXISTS(SELECT 1 FROM catalog_category_edges edge
   WHERE edge.child_id=c.category_id AND edge.parent_id::text=ANY($1::text[]))
 UNION
 SELECT e.event_id,p.processor,e.received_at FROM catalog_products product
 JOIN sync_events e ON e.event_id=product.source_event_id AND e.store_id=product.store_id
 JOIN sync_event_processing p ON p.event_id=e.event_id AND p.processor='catalog_product_projection.v1'
 WHERE p.status='processed' AND (product.top_category_id::text=ANY($1::text[])
   OR EXISTS(SELECT 1 FROM catalog_product_subcategories sub WHERE sub.product_id=product.product_id AND sub.category_id::text=ANY($1::text[]))
   OR EXISTS(SELECT 1 FROM catalog_product_tags tag WHERE tag.product_id=product.product_id AND tag.tag_id::text=ANY($2::text[])))
)
SELECT event_id,processor FROM candidates ORDER BY received_at,event_id LIMIT 100
`

type DefaultCatalogRecoveryCandidatesParams struct {
	CategoryIds []string `json:"category_ids"`
	TagIds      []string `json:"tag_ids"`
}

type DefaultCatalogRecoveryCandidatesRow struct {
	EventID   pgtype.UUID `json:"event_id"`
	Processor string      `json:"processor"`
}

// Only authoritative scoped events are replayed. Never reset genuine
// equal-revision/ownership conflicts, or unbound historical processing.
func (q *Queries) DefaultCatalogRecoveryCandidates(ctx context.Context, arg DefaultCatalogRecoveryCandidatesParams) ([]DefaultCatalogRecoveryCandidatesRow, error) {
	rows, err := q.db.Query(ctx, defaultCatalogRecoveryCandidates, arg.CategoryIds, arg.TagIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DefaultCatalogRecoveryCandidatesRow{}
	for rows.Next() {
		var i DefaultCatalogRecoveryCandidatesRow
		if err := rows.Scan(&i.EventID, &i.Processor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCatalogCategoryEdges = `-- name: DeleteCatalogCategoryEdges :exec
DELETE FROM catalog_category_edges WHERE child_id = $1
`

func (q *Queries) DeleteCatalogCategoryEdges(ctx context.Context, childID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogCategoryEdges, childID)
	return err
}

const deleteCatalogProductPrices = `-- name: DeleteCatalogProductPrices :exec
DELETE FROM catalog_product_prices WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductPrices(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductPrices, productID)
	return err
}

const deleteCatalogProductSubcategories = `-- name: DeleteCatalogProductSubcategories :exec
DELETE FROM catalog_product_subcategories WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductSubcategories(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductSubcategories, productID)
	return err
}

const deleteCatalogProductTags = `-- name: DeleteCatalogProductTags :exec
DELETE FROM catalog_product_tags WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductTags(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductTags, productID)
	return err
}

const deleteCatalogProductTranslations = `-- name: DeleteCatalogProductTranslations :exec
DELETE FROM catalog_product_translations WHERE product_id = $1
`

func (q *Queries) DeleteCatalogProductTranslations(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductTranslations, productID)
	return err
}

const establishedDefaultCatalog = `-- name: EstablishedDefaultCatalog :one
SELECT EXISTS (
 SELECT 1 FROM catalog_categories c JOIN sync_events e ON e.event_id=c.source_event_id
 WHERE $1::text='category' AND c.category_id=$2::uuid
 AND c.store_id=$3::uuid AND e.store_id=c.store_id
 AND c.default_algorithm=1 AND e.payload->>'category_id'=$4::text
) OR EXISTS (
 SELECT 1 FROM catalog_tags t JOIN sync_events e ON e.event_id=t.source_event_id
 WHERE $1::text='tag' AND t.tag_id=$2::uuid
 AND t.store_id=$3::uuid AND e.store_id=t.store_id
 AND t.default_algorithm=1 AND e.payload->>'tag_id'=$4::text
) AS established
`

type EstablishedDefaultCatalogParams struct {
	Kind        string      `json:"kind"`
	CanonicalID pgtype.UUID `json:"canonical_id"`
	StoreID     pgtype.UUID `json:"store_id"`
	RawID       string      `json:"raw_id"`
}

// A no-op may retire compatibility state only for a proven canonical row.
func (q *Queries) EstablishedDefaultCatalog(ctx context.Context, arg EstablishedDefaultCatalogParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, establishedDefaultCatalog,
		arg.Kind,
		arg.CanonicalID,
		arg.StoreID,
		arg.RawID,
	)
	var established pgtype.Bool
	err := row.Scan(&established)
	return established, err
}

const insertCatalogCategoryEdge = `-- name: InsertCatalogCategoryEdge :exec
INSERT INTO catalog_category_edges (parent_id, child_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (parent_id, child_id) DO UPDATE SET position = excluded.position
`

type InsertCatalogCategoryEdgeParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	ChildID  pgtype.UUID `json:"child_id"`
	Position int32       `json:"position"`
}

func (q *Queries) InsertCatalogCategoryEdge(ctx context.Context, arg InsertCatalogCategoryEdgeParams) error {
	_, err := q.db.Exec(ctx, insertCatalogCategoryEdge, arg.ParentID, arg.ChildID, arg.Position)
	return err
}

const insertCatalogProductPrice = `-- name: InsertCatalogProductPrice :exec
INSERT INTO catalog_product_prices (product_id, currency, price_minor, cost_minor)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id, currency) DO UPDATE SET
    price_minor = excluded.price_minor, cost_minor = excluded.cost_minor
`

type InsertCatalogProductPriceParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	Currency   string      `json:"currency"`
	PriceMinor int64       `json:"price_minor"`
	CostMinor  pgtype.Int8 `json:"cost_minor"`
}

func (q *Queries) InsertCatalogProductPrice(ctx context.Context, arg InsertCatalogProductPriceParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductPrice,
		arg.ProductID,
		arg.Currency,
		arg.PriceMinor,
		arg.CostMinor,
	)
	return err
}

const insertCatalogProductSubcategory = `-- name: InsertCatalogProductSubcategory :exec
INSERT INTO catalog_product_subcategories (product_id, category_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (product_id, category_id) DO UPDATE SET position = excluded.position
`

type InsertCatalogProductSubcategoryParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	Position   int32       `json:"position"`
}

func (q *Queries) InsertCatalogProductSubcategory(ctx context.Context, arg InsertCatalogProductSubcategoryParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductSubcategory, arg.ProductID, arg.CategoryID, arg.Position)
	return err
}

const insertCatalogProductTag = `-- name: InsertCatalogProductTag :exec
INSERT INTO catalog_product_tags (product_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertCatalogProductTagParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

func (q *Queries) InsertCatalogProductTag(ctx context.Context, arg InsertCatalogProductTagParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductTag, arg.ProductID, arg.TagID)
	return err
}

const insertCatalogProductTranslation = `-- name: InsertCatalogProductTranslation :exec
INSERT INTO catalog_product_translations (product_id, locale, name, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id, locale) DO UPDATE SET
    name = excluded.name, description = excluded.description
`

type InsertCatalogProductTranslationParams struct {
	ProductID   pgtype.UUID `json:"product_id"`
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) InsertCatalogProductTranslation(ctx context.Context, arg InsertCatalogProductTranslationParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductTranslation,
		arg.ProductID,
		arg.Locale,
		arg.Name,
		arg.Description,
	)
	return err
}

const lockCatalogEntity = `-- name: LockCatalogEntity :exec
SELECT pg_advisory_xact_lock(hashtext('catalog:' || $1::text || ':' || $2::text))
`

type LockCatalogEntityParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

// PostgreSQL-enforced entity serialization (R04): one advisory
// transaction-scoped lock per (entity_type, entity_id), always acquired in
// globally sorted key order (see lockCatalogEntities). Concurrent
// revisions of the same entity serialize; different entities proceed in
// parallel. Released automatically at commit/rollback.
func (q *Queries) LockCatalogEntity(ctx context.Context, arg LockCatalogEntityParams) error {
	_, err := q.db.Exec(ctx, lockCatalogEntity, arg.Column1, arg.Column2)
	return err
}

const nextCatalogRetryAt = `-- name: NextCatalogRetryAt :one
SELECT min(p.next_attempt_at)::timestamptz AS next_attempt_at
FROM sync_event_processing p
JOIN sync_events e ON e.event_id = p.event_id
WHERE p.processor = $1
  AND p.status = 'retry'
  AND p.next_attempt_at > $3::timestamptz
  AND (e.event_type = $2
       OR ($2 IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2')
           AND e.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2'))
       OR ($2 IN ('catalog.product.snapshot.v1','catalog.product.snapshot.v2')
           AND e.event_type IN ('catalog.product.snapshot.v1','catalog.product.snapshot.v2')))
`

type NextCatalogRetryAtParams struct {
	Processor string             `json:"processor"`
	EventType string             `json:"event_type"`
	AsOf      pgtype.Timestamptz `json:"as_of"`
}

// Earliest future retry for one processor (same event-type matching as
// PendingCatalogEvents). Lets the in-process projector wake exactly when
// durable retry work falls due instead of waiting for the safety scan.
// A wake hint only: claiming and revision fencing stay authoritative.
func (q *Queries) NextCatalogRetryAt(ctx context.Context, arg NextCatalogRetryAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, nextCatalogRetryAt, arg.Processor, arg.EventType, arg.AsOf)
	var next_attempt_at pgtype.Timestamptz
	err := row.Scan(&next_attempt_at)
	return next_attempt_at, err
}

const pendingCatalogEvents = `-- name: PendingCatalogEvents :many

SELECT e.event_id
FROM sync_events e
LEFT JOIN sync_event_processing p
  ON p.event_id = e.event_id AND p.processor = $1
WHERE (e.event_type = $2
       OR ($2 IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2')
           AND e.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2'))
       OR ($2 IN ('catalog.product.snapshot.v1','catalog.product.snapshot.v2')
           AND e.event_type IN ('catalog.product.snapshot.v1','catalog.product.snapshot.v2')))
  AND (p.event_id IS NULL
       OR p.status = 'pending'
       OR (p.status = 'retry' AND (p.next_attempt_at IS NULL OR p.next_attempt_at <= $4::timestamptz)))
ORDER BY e.received_at, e.event_id
LIMIT $3
`

type PendingCatalogEventsParams struct {
	Processor string             `json:"processor"`
	EventType string             `json:"event_type"`
	Limit     int32              `json:"limit"`
	AsOf      pgtype.Timestamptz `json:"as_of"`
}

// Phase 5A catalog projection queries (ADR-0028). Current-state replace
// semantics: one entity row per business ID carrying its highest valid
// revision; relations replaced transactionally per revision.
// Lazy backfill discovery shared by the three catalog processors: accepted
// events with no processing row (missing), a pending row, or a due retry.
// Blocked and processed rows never return; ordering is deterministic.
// as_of comes from the same application clock used to claim/schedule retries.
func (q *Queries) PendingCatalogEvents(ctx context.Context, arg PendingCatalogEventsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, pendingCatalogEvents,
		arg.Processor,
		arg.EventType,
		arg.Limit,
		arg.AsOf,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var event_id pgtype.UUID
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rearmBlockedCatalogProducts = `-- name: RearmBlockedCatalogProducts :exec

UPDATE sync_event_processing AS p SET status = 'pending', next_attempt_at = NULL,
    processed_at = NULL, last_error_code = NULL, last_error_message = NULL
FROM sync_events e
WHERE p.event_id = e.event_id
  AND p.processor = 'catalog_product_projection.v1'
  AND p.status = 'blocked'
  AND p.last_error_code = 'CATALOG_INVALID_RELATION'
  AND e.event_type IN ('catalog.product.snapshot.v1','catalog.product.snapshot.v2')
  AND NOT EXISTS (
    SELECT 1 FROM sync_events e2
    WHERE e2.event_type IN ('catalog.product.snapshot.v1','catalog.product.snapshot.v2')
      AND e2.payload->>'product_id' = e.payload->>'product_id'
      AND (e.store_id IS NULL OR e2.store_id IS NULL OR e2.store_id = e.store_id)
      AND (e2.payload->>'catalog_revision')::bigint > (e.payload->>'catalog_revision')::bigint
  )
  AND EXISTS (
    SELECT 1 FROM catalog_categories c JOIN sync_events source ON source.event_id = c.source_event_id
    WHERE ((c.default_algorithm = 1 AND e.store_id = c.store_id)
       OR (c.default_algorithm <> 1 AND (e.store_id IS NULL OR c.store_id IS NULL OR e.store_id = c.store_id)))
      AND (c.category_id::text = e.payload->>'top_category_id'
           OR source.payload->>'category_id' = e.payload->>'top_category_id'
           OR c.category_id::text IN (SELECT jsonb_array_elements_text(e.payload->'subcategory_ids'))
           OR source.payload->>'category_id' IN (SELECT jsonb_array_elements_text(e.payload->'subcategory_ids')))
      AND c.projected_at > p.updated_at
  )
`

// Phase 5A-R2 durable re-evaluation fallback (M01): graph-dependent
// blocked Product events become eligible again when the relevant graph
// has advanced since the block decision. The predicate is strictly
// monotonic (involved category projected_at strictly newer than the block
// updated_at), so a re-blocked event can never hot-loop: each re-arm
// requires strictly newer graph advancement. Superseded events (a newer
// accepted revision exists) are never re-armed. Terminally invalid events
// under a static graph stay blocked forever. This is the correctness path;
// the post-commit reset is only a fast wake-up.
func (q *Queries) RearmBlockedCatalogProducts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rearmBlockedCatalogProducts)
	return err
}

const rearmDefaultCatalogRecovery = `-- name: RearmDefaultCatalogRecovery :execrows
UPDATE sync_event_processing SET status='pending',next_attempt_at=NULL,processed_at=NULL,
       last_error_code=NULL,last_error_message=NULL
WHERE event_id=$1 AND processor=$2 AND status IN ('processed','blocked')
`

type RearmDefaultCatalogRecoveryParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	Processor string      `json:"processor"`
}

func (q *Queries) RearmDefaultCatalogRecovery(ctx context.Context, arg RearmDefaultCatalogRecoveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, rearmDefaultCatalogRecovery, arg.EventID, arg.Processor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetCatalogProductRetriesForGraph = `-- name: ResetCatalogProductRetriesForGraph :exec
UPDATE sync_event_processing SET status = 'pending', next_attempt_at = NULL,
    processed_at = NULL, last_error_code = NULL, last_error_message = NULL
WHERE processor = 'catalog_product_projection.v1'
  AND status IN ('retry', 'blocked')
  AND last_error_code IN ('CATALOG_DEPENDENCY_WAIT', 'CATALOG_INVALID_RELATION')
  AND event_id IN (
    SELECT e.event_id FROM sync_events e
    JOIN catalog_categories c ON c.category_id = $1::uuid
    JOIN sync_events source ON source.event_id = c.source_event_id
    WHERE e.event_type IN ('catalog.product.snapshot.v1','catalog.product.snapshot.v2')
      AND ((c.default_algorithm = 1 AND e.store_id = c.store_id)
        OR (c.default_algorithm <> 1 AND (e.store_id IS NULL OR c.store_id IS NULL OR e.store_id = c.store_id)))
      AND (e.payload->>'top_category_id' IN (c.category_id::text, source.payload->>'category_id')
           OR e.payload->'subcategory_ids' @> to_jsonb(c.category_id::text)
           OR e.payload->'subcategory_ids' @> to_jsonb(source.payload->>'category_id'))
  )
`

// Re-evaluation trigger: after a category graph commit, waiting or
// graph-blocked product events referencing the changed category become
// pending again so they re-validate against the new graph with no operator
// retry and no Retail resend. Other error codes are never touched.
func (q *Queries) ResetCatalogProductRetriesForGraph(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetCatalogProductRetriesForGraph, dollar_1)
	return err
}

const retireRawDefaultCategory = `-- name: RetireRawDefaultCategory :execrows
UPDATE catalog_categories c SET store_id = NULL, default_algorithm = 2
WHERE c.category_id = $1 AND c.default_algorithm = 0
  AND (c.store_id = $2 OR c.store_id IS NULL)
  AND EXISTS (SELECT 1 FROM sync_events e WHERE e.event_id=c.source_event_id
    AND e.store_id=$2 AND e.event_type IN ('catalog.category.snapshot.v1','catalog.category.snapshot.v2')
    AND e.payload->>'category_id'=c.category_id::text)
`

type RetireRawDefaultCategoryParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	StoreID    pgtype.UUID `json:"store_id"`
}

// Keep the raw compatibility snapshot and its source provenance. It no
// longer claims a Store once that Store transitions to a canonical row.
func (q *Queries) RetireRawDefaultCategory(ctx context.Context, arg RetireRawDefaultCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireRawDefaultCategory, arg.CategoryID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireRawDefaultTag = `-- name: RetireRawDefaultTag :execrows
UPDATE catalog_tags t SET store_id = NULL, default_algorithm = 2
WHERE t.tag_id = $1 AND t.default_algorithm = 0
  AND (t.store_id = $2 OR t.store_id IS NULL)
  AND EXISTS (SELECT 1 FROM sync_events e WHERE e.event_id=t.source_event_id
    AND e.store_id=$2 AND e.event_type='catalog.tag.snapshot.v1'
    AND e.payload->>'tag_id'=t.tag_id::text)
`

type RetireRawDefaultTagParams struct {
	TagID   pgtype.UUID `json:"tag_id"`
	StoreID pgtype.UUID `json:"store_id"`
}

// Also releases the obsolete (Store, slug) claim before canonical replay.
func (q *Queries) RetireRawDefaultTag(ctx context.Context, arg RetireRawDefaultTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireRawDefaultTag, arg.TagID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCatalogCategory = `-- name: UpsertCatalogCategory :exec
INSERT INTO catalog_categories (
    category_id, status, name_ar, name_en,
    source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at, store_id, default_algorithm,
    online_enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (category_id) DO UPDATE SET
    status = excluded.status, name_ar = excluded.name_ar, name_en = excluded.name_en,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at,
    store_id = COALESCE(excluded.store_id, catalog_categories.store_id),
    default_algorithm = excluded.default_algorithm,
    online_enabled = excluded.online_enabled,
    projected_at = now()
`

type UpsertCatalogCategoryParams struct {
	CategoryID        pgtype.UUID        `json:"category_id"`
	Status            string             `json:"status"`
	NameAr            string             `json:"name_ar"`
	NameEn            pgtype.Text        `json:"name_en"`
	SourceRevision    int64              `json:"source_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
	StoreID           pgtype.UUID        `json:"store_id"`
	DefaultAlgorithm  int16              `json:"default_algorithm"`
	OnlineEnabled     bool               `json:"online_enabled"`
}

// Phase 9B: store_id carries the event's own ingress Store context
// (NULL for legacy events). COALESCE preserves proven ownership: a
// legacy event never wipes an adopted Store, and a scoped event adopts
// a NULL row or reaffirms its own Store (cross-Store writes are fenced
// in Go before this upsert runs).
// Phase 9-R2: default_algorithm records which identity scheme wrote the
// row (0 = raw seeded ID, 1 = Store-scoped canonical ID) so an existing
// pre-R2 annotation can be detected and recovered.
func (q *Queries) UpsertCatalogCategory(ctx context.Context, arg UpsertCatalogCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogCategory,
		arg.CategoryID,
		arg.Status,
		arg.NameAr,
		arg.NameEn,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
		arg.StoreID,
		arg.DefaultAlgorithm,
		arg.OnlineEnabled,
	)
	return err
}

const upsertCatalogProduct = `-- name: UpsertCatalogProduct :exec
INSERT INTO catalog_products (
    product_id, name, description, top_category_id, width_cm, height_cm,
    is_active, product_type_id,
    source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at, store_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (product_id) DO UPDATE SET
    name = excluded.name, description = excluded.description,
    top_category_id = excluded.top_category_id, width_cm = excluded.width_cm,
    height_cm = excluded.height_cm, is_active = excluded.is_active,
    product_type_id = excluded.product_type_id,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at,
    store_id = COALESCE(excluded.store_id, catalog_products.store_id),
    projected_at = now()
`

type UpsertCatalogProductParams struct {
	ProductID         pgtype.UUID        `json:"product_id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	TopCategoryID     pgtype.UUID        `json:"top_category_id"`
	WidthCm           pgtype.Int4        `json:"width_cm"`
	HeightCm          pgtype.Int4        `json:"height_cm"`
	IsActive          bool               `json:"is_active"`
	ProductTypeID     pgtype.UUID        `json:"product_type_id"`
	SourceRevision    int64              `json:"source_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
	StoreID           pgtype.UUID        `json:"store_id"`
}

// Phase 9B store ownership: see UpsertCatalogCategory.
// Phase 17-R0 (ADR-0049): Product carries NO SKU — SKU/stock identity
// lives on ProductVariant; the column was retired by 00035.
func (q *Queries) UpsertCatalogProduct(ctx context.Context, arg UpsertCatalogProductParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogProduct,
		arg.ProductID,
		arg.Name,
		arg.Description,
		arg.TopCategoryID,
		arg.WidthCm,
		arg.HeightCm,
		arg.IsActive,
		arg.ProductTypeID,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
		arg.StoreID,
	)
	return err
}

const upsertCatalogTag = `-- name: UpsertCatalogTag :exec
INSERT INTO catalog_tags (
    tag_id, slug, is_active, name_ar, name_en,
    source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at, store_id, default_algorithm
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (tag_id) DO UPDATE SET
    slug = excluded.slug, is_active = excluded.is_active,
    name_ar = excluded.name_ar, name_en = excluded.name_en,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at,
    store_id = COALESCE(excluded.store_id, catalog_tags.store_id),
    default_algorithm = excluded.default_algorithm,
    projected_at = now()
`

type UpsertCatalogTagParams struct {
	TagID             pgtype.UUID        `json:"tag_id"`
	Slug              string             `json:"slug"`
	IsActive          bool               `json:"is_active"`
	NameAr            pgtype.Text        `json:"name_ar"`
	NameEn            pgtype.Text        `json:"name_en"`
	SourceRevision    int64              `json:"source_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
	StoreID           pgtype.UUID        `json:"store_id"`
	DefaultAlgorithm  int16              `json:"default_algorithm"`
}

// Phase 9B store ownership: see UpsertCatalogCategory.
func (q *Queries) UpsertCatalogTag(ctx context.Context, arg UpsertCatalogTagParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogTag,
		arg.TagID,
		arg.Slug,
		arg.IsActive,
		arg.NameAr,
		arg.NameEn,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
		arg.StoreID,
		arg.DefaultAlgorithm,
	)
	return err
}
