// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_health.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogHealthDetail = `-- name: CatalogHealthDetail :many
SELECT reason_code, provider_key, product_id, sku, name, store_id
FROM (
    SELECT 'CATALOG_MISSING_SKU' AS reason_code, ''::text AS provider_key,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    WHERE (p.sku IS NULL OR btrim(p.sku) = '')
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'CATALOG_MISSING_CATEGORY', ''::text,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    WHERE (p.top_category_id IS NULL OR
           NOT EXISTS (SELECT 1 FROM catalog_categories c WHERE c.category_id = p.top_category_id))
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'AVAILABILITY_NOT_READY', ''::text,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online
      AND NOT EXISTS (SELECT 1 FROM catalog_product_inventory i WHERE i.product_id = p.product_id)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'COMMERCE_MAPPING_MISSING', u.provider_key,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN (
        SELECT DISTINCT provider_key FROM commerce_product_mappings
        UNION
        SELECT DISTINCT provider_key FROM commerce_product_mutation_barriers
    ) u ON ($2::text = '' OR u.provider_key = $2::text)
    WHERE p.is_active AND pol.sell_online
      AND ($1::text = '' OR p.store_id = $1::uuid)
      AND NOT EXISTS (SELECT 1 FROM commerce_product_mappings m
                      WHERE m.provider_key = u.provider_key AND m.product_id = p.product_id)
    UNION ALL
    SELECT 'COMMERCE_SYNC_AMBIGUOUS', b.provider_key,
           p.product_id, p.sku, p.name, p.store_id
    FROM commerce_product_mutation_barriers b
    JOIN catalog_products p ON p.product_id = b.product_id
    WHERE b.state IN ('in_flight', 'uncertain')
      AND ($2::text = '' OR b.provider_key = $2::text)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'COMMERCE_STORE_CONFLICT', m.provider_key,
           p.product_id, p.sku, p.name, p.store_id
    FROM commerce_product_mappings m
    JOIN catalog_products p ON p.product_id = m.product_id
    WHERE m.store_id IS NOT NULL AND p.store_id IS NOT NULL
      AND m.store_id <> p.store_id
      AND ($2::text = '' OR m.provider_key = $2::text)
      AND ($1::text = '' OR p.store_id = $1::uuid)
) details
WHERE ($3::text = '' OR reason_code = $3::text)
ORDER BY reason_code, provider_key, sku, product_id
LIMIT $4::int
`

type CatalogHealthDetailParams struct {
	StoreID     string `json:"store_id"`
	ProviderKey string `json:"provider_key"`
	Reason      string `json:"reason"`
	LimitN      int32  `json:"limit_n"`
}

type CatalogHealthDetailRow struct {
	ReasonCode  string      `json:"reason_code"`
	ProviderKey string      `json:"provider_key"`
	ProductID   pgtype.UUID `json:"product_id"`
	Sku         string      `json:"sku"`
	Name        string      `json:"name"`
	StoreID     pgtype.UUID `json:"store_id"`
}

// Bounded diagnostic detail rows for one stable reason code (or all).
// Row identity only: no raw provider errors, no credentials, no SQL.
func (q *Queries) CatalogHealthDetail(ctx context.Context, arg CatalogHealthDetailParams) ([]CatalogHealthDetailRow, error) {
	rows, err := q.db.Query(ctx, catalogHealthDetail,
		arg.StoreID,
		arg.ProviderKey,
		arg.Reason,
		arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogHealthDetailRow{}
	for rows.Next() {
		var i CatalogHealthDetailRow
		if err := rows.Scan(
			&i.ReasonCode,
			&i.ProviderKey,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogHealthSummary = `-- name: CatalogHealthSummary :many
SELECT reason_code, count(*)::bigint AS products
FROM (
    SELECT 'CATALOG_MISSING_SKU' AS reason_code
    FROM catalog_products p
    WHERE (p.sku IS NULL OR btrim(p.sku) = '')
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'CATALOG_MISSING_CATEGORY'
    FROM catalog_products p
    WHERE (p.top_category_id IS NULL OR
           NOT EXISTS (SELECT 1 FROM catalog_categories c WHERE c.category_id = p.top_category_id))
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'AVAILABILITY_NOT_READY'
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online
      AND NOT EXISTS (SELECT 1 FROM catalog_product_inventory i WHERE i.product_id = p.product_id)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'COMMERCE_MAPPING_MISSING'
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN (
        SELECT DISTINCT provider_key FROM commerce_product_mappings
        UNION
        SELECT DISTINCT provider_key FROM commerce_product_mutation_barriers
    ) u ON ($2::text = '' OR u.provider_key = $2::text)
    WHERE p.is_active AND pol.sell_online
      AND ($1::text = '' OR p.store_id = $1::uuid)
      AND NOT EXISTS (SELECT 1 FROM commerce_product_mappings m
                      WHERE m.provider_key = u.provider_key AND m.product_id = p.product_id)
    UNION ALL
    SELECT 'COMMERCE_SYNC_AMBIGUOUS'
    FROM commerce_product_mutation_barriers b
    JOIN catalog_products p ON p.product_id = b.product_id
    WHERE b.state IN ('in_flight', 'uncertain')
      AND ($2::text = '' OR b.provider_key = $2::text)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'COMMERCE_STORE_CONFLICT'
    FROM commerce_product_mappings m
    JOIN catalog_products p ON p.product_id = m.product_id
    WHERE m.store_id IS NOT NULL AND p.store_id IS NOT NULL
      AND m.store_id <> p.store_id
      AND ($2::text = '' OR m.provider_key = $2::text)
      AND ($1::text = '' OR p.store_id = $1::uuid)
) reasons
GROUP BY reason_code
`

type CatalogHealthSummaryParams struct {
	StoreID     string `json:"store_id"`
	ProviderKey string `json:"provider_key"`
}

type CatalogHealthSummaryRow struct {
	ReasonCode string `json:"reason_code"`
	Products   int64  `json:"products"`
}

// Bounded summary counts per stable health reason code. Exact predicates
// (documented in docs/decisions/0045 and tested):
//
//	CATALOG_MISSING_SKU       — projected SKU absent/blank (missing only;
//	                            legacy stored SKUs are preserved, never
//	                            regex-rejected).
//	CATALOG_MISSING_CATEGORY  — required root/top category absent or
//	                            unresolved (optional subcategories and
//	                            hidden categories are NOT failures).
//	AVAILABILITY_NOT_READY    — online-eligible product (active +
//	                            sell_online) with no projected inventory
//	                            row (frozen readiness: product + policy
//	                            + inventory).
//	COMMERCE_MAPPING_MISSING  — online-eligible product with no mapping
//	                            for a known provider (intentionally
//	                            offline/inactive products are never
//	                            flagged).
//	COMMERCE_SYNC_AMBIGUOUS   — an unresolved mutation barrier exists for
//	                            the product (needs operator settlement;
//	                            read-only, never settled here).
//	COMMERCE_STORE_CONFLICT   — durable mapping Store ownership differs
//	                            from the catalog product's Store.
//
// Provider-scoped reasons are computed against the durable provider
// universe (provider keys observed in mappings or barriers).
func (q *Queries) CatalogHealthSummary(ctx context.Context, arg CatalogHealthSummaryParams) ([]CatalogHealthSummaryRow, error) {
	rows, err := q.db.Query(ctx, catalogHealthSummary, arg.StoreID, arg.ProviderKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogHealthSummaryRow{}
	for rows.Next() {
		var i CatalogHealthSummaryRow
		if err := rows.Scan(&i.ReasonCode, &i.Products); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardOrderAnalytics = `-- name: DashboardOrderAnalytics :many

SELECT
    provider_key,
    canonical_status,
    currency,
    count(*)::bigint AS orders_count,
    COALESCE(sum(total_minor), 0)::bigint AS value_minor
FROM commerce_online_orders
WHERE created_at >= $1
  AND created_at < $2
  AND ($3::text = '' OR provider_key = $3::text)
  AND ($4::text = '' OR store_id = $4::uuid)
GROUP BY provider_key, canonical_status, currency
`

type DashboardOrderAnalyticsParams struct {
	StartUtc    pgtype.Timestamptz `json:"start_utc"`
	EndUtc      pgtype.Timestamptz `json:"end_utc"`
	ProviderKey string             `json:"provider_key"`
	StoreID     string             `json:"store_id"`
}

type DashboardOrderAnalyticsRow struct {
	ProviderKey     string `json:"provider_key"`
	CanonicalStatus string `json:"canonical_status"`
	Currency        string `json:"currency"`
	OrdersCount     int64  `json:"orders_count"`
	ValueMinor      int64  `json:"value_minor"`
}

// Phase 12 — Catalog Health + online-order operational analytics.
//
// Everything here is READ-ONLY durable MoonLight state. No provider is
// contacted live; no barrier is settled, cleared or modified; no Store
// adoption or reconciliation ever runs from these reads.
// Operational provider-order aggregation (Phase 12). This is NOT
// financial revenue: provider online orders are operational commerce
// truth and are never added to canonical finalized Retail Sales. Groups
// durable online-order rows by provider, canonical status and currency
// over the report window; currencies are never summed together. The
// optional provider filter (” = all providers) is a narrowing filter
// only — historical rows stay queryable when a provider is disabled.
func (q *Queries) DashboardOrderAnalytics(ctx context.Context, arg DashboardOrderAnalyticsParams) ([]DashboardOrderAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, dashboardOrderAnalytics,
		arg.StartUtc,
		arg.EndUtc,
		arg.ProviderKey,
		arg.StoreID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardOrderAnalyticsRow{}
	for rows.Next() {
		var i DashboardOrderAnalyticsRow
		if err := rows.Scan(
			&i.ProviderKey,
			&i.CanonicalStatus,
			&i.Currency,
			&i.OrdersCount,
			&i.ValueMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
