// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_health.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogHealthDetail = `-- name: CatalogHealthDetail :many
SELECT reason_code, provider_key, product_id, sku, name, store_id
FROM (
    SELECT 'CATALOG_MISSING_SKU' AS reason_code, ''::text AS provider_key,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    WHERE (p.sku IS NULL OR btrim(p.sku) = '')
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'CATALOG_MISSING_CATEGORY', ''::text,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    WHERE (p.top_category_id IS NULL OR
           NOT EXISTS (SELECT 1 FROM catalog_categories c WHERE c.category_id = p.top_category_id))
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'AVAILABILITY_NOT_READY', ''::text,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online
      AND s.block_reason <> 'CATEGORY_ONLINE_DISABLED'
      AND NOT EXISTS (SELECT 1 FROM catalog_product_inventory i WHERE i.product_id = p.product_id)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'COMMERCE_MAPPING_MISSING', u.provider_key,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN (
        SELECT DISTINCT provider_key FROM commerce_product_mappings
        UNION
        SELECT DISTINCT provider_key FROM commerce_product_mutation_barriers
    ) u ON ($2::text = '' OR u.provider_key = $2::text)
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online AND s.category_allows_online
      AND ($1::text = '' OR p.store_id = $1::uuid)
      AND NOT EXISTS (SELECT 1 FROM commerce_product_mappings m
                      WHERE m.provider_key = u.provider_key AND m.product_id = p.product_id)
    UNION ALL
    SELECT 'CATEGORY_ONLINE_DISABLED', ''::text,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online
      AND NOT s.category_allows_online AND s.block_reason = 'CATEGORY_ONLINE_DISABLED'
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'COMMERCE_SYNC_AMBIGUOUS', b.provider_key,
           p.product_id, p.sku, p.name, p.store_id
    FROM commerce_product_mutation_barriers b
    JOIN catalog_products p ON p.product_id = b.product_id
    WHERE b.state IN ('in_flight', 'uncertain')
      AND ($2::text = '' OR b.provider_key = $2::text)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'COMMERCE_STORE_CONFLICT', m.provider_key,
           p.product_id, p.sku, p.name, p.store_id
    FROM commerce_product_mappings m
    JOIN catalog_products p ON p.product_id = m.product_id
    WHERE m.store_id IS NOT NULL AND p.store_id IS NOT NULL
      AND m.store_id <> p.store_id
      AND ($2::text = '' OR m.provider_key = $2::text)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    -- Phase 17 variant detail: row identity per variant (its SKU) or per
    -- product (its SKU) for product-level codes; no raw provider errors.
    SELECT 'PRODUCT_NO_ACTIVE_VARIANTS', ''::text,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    WHERE p.is_active
      AND NOT EXISTS (SELECT 1 FROM catalog_product_variants v
                      WHERE v.product_id = p.product_id AND v.is_active AND NOT v.deleted)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'PRODUCT_NO_SELLABLE_VARIANT', ''::text,
           p.product_id, p.sku, p.name, p.store_id
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online AND s.category_allows_online
      AND NOT EXISTS (
        SELECT 1 FROM catalog_product_variants v
        LEFT JOIN catalog_product_variant_inventory vi ON vi.variant_id = v.variant_id
        WHERE v.product_id = p.product_id AND v.is_active AND NOT v.deleted
          AND COALESCE(vi.stock_quantity, 0) > 0)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'VARIANT_DUPLICATE_COMBINATION', ''::text,
           v.product_id, v.sku, p.name, v.store_id
    FROM catalog_product_variants v
    JOIN catalog_products p ON p.product_id = v.product_id
    WHERE NOT v.deleted
      AND EXISTS (SELECT 1 FROM catalog_product_variants o
                  WHERE o.product_id = v.product_id
                    AND o.combination_key = v.combination_key
                    AND o.variant_id <> v.variant_id
                    AND o.store_id IS NOT DISTINCT FROM v.store_id
                    AND NOT o.deleted)
      AND ($1::text = '' OR v.store_id = $1::uuid)
    UNION ALL
    SELECT 'VARIANT_MISSING_SKU', ''::text,
           v.product_id, v.sku, p.name, v.store_id
    FROM catalog_product_variants v
    JOIN catalog_products p ON p.product_id = v.product_id
    WHERE (v.sku IS NULL OR btrim(v.sku) = '')
      AND ($1::text = '' OR v.store_id = $1::uuid)
    UNION ALL
    SELECT 'VARIANT_MAPPING_MISSING', u.provider_key,
           v.product_id, v.sku, p.name, v.store_id
    FROM catalog_product_variants v
    JOIN catalog_products p ON p.product_id = v.product_id
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN (
        SELECT DISTINCT provider_key FROM commerce_product_mappings
        UNION
        SELECT DISTINCT provider_key FROM commerce_product_mutation_barriers
    ) u ON ($2::text = '' OR u.provider_key = $2::text)
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online AND s.category_allows_online
      AND v.is_active AND NOT v.deleted
      AND ($1::text = '' OR p.store_id = $1::uuid)
      AND NOT EXISTS (SELECT 1 FROM commerce_product_variant_mappings m
                      WHERE m.provider_key = u.provider_key AND m.variant_id = v.variant_id)
    UNION ALL
    SELECT 'VARIANT_INTENTIONALLY_OFFLINE', ''::text,
           v.product_id, v.sku, p.name, v.store_id
    FROM catalog_product_variants v
    JOIN catalog_products p ON p.product_id = v.product_id
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online AND s.category_allows_online
      AND (NOT v.is_active OR v.deleted)
      AND ($1::text = '' OR p.store_id = $1::uuid)
) details
WHERE ($3::text = '' OR reason_code = $3::text)
ORDER BY reason_code, provider_key, sku, product_id
LIMIT $4::int
`

type CatalogHealthDetailParams struct {
	StoreID     string `json:"store_id"`
	ProviderKey string `json:"provider_key"`
	Reason      string `json:"reason"`
	LimitN      int32  `json:"limit_n"`
}

type CatalogHealthDetailRow struct {
	ReasonCode  string      `json:"reason_code"`
	ProviderKey string      `json:"provider_key"`
	ProductID   pgtype.UUID `json:"product_id"`
	Sku         string      `json:"sku"`
	Name        string      `json:"name"`
	StoreID     pgtype.UUID `json:"store_id"`
}

// Bounded diagnostic detail rows for one stable reason code (or all).
// Row identity only: no raw provider errors, no credentials, no SQL.
func (q *Queries) CatalogHealthDetail(ctx context.Context, arg CatalogHealthDetailParams) ([]CatalogHealthDetailRow, error) {
	rows, err := q.db.Query(ctx, catalogHealthDetail,
		arg.StoreID,
		arg.ProviderKey,
		arg.Reason,
		arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogHealthDetailRow{}
	for rows.Next() {
		var i CatalogHealthDetailRow
		if err := rows.Scan(
			&i.ReasonCode,
			&i.ProviderKey,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogHealthProviders = `-- name: CatalogHealthProviders :many
SELECT provider_key FROM (
 SELECT provider_key FROM commerce_product_mappings
 UNION
 SELECT provider_key FROM commerce_product_mutation_barriers
) providers
WHERE ($1::text = '' OR EXISTS (
 SELECT 1 FROM catalog_products p WHERE p.store_id = $1::uuid
))
ORDER BY provider_key
`

// Same complete durable provider universe as mapping-health predicates.
// A specific Store must have projected Products; unknown Store never falls
// back to a global list. Choices ignore provider selection/detail truncation.
func (q *Queries) CatalogHealthProviders(ctx context.Context, storeID string) ([]string, error) {
	rows, err := q.db.Query(ctx, catalogHealthProviders, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var provider_key string
		if err := rows.Scan(&provider_key); err != nil {
			return nil, err
		}
		items = append(items, provider_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogHealthSummary = `-- name: CatalogHealthSummary :many
SELECT reason_code, count(*)::bigint AS products
FROM (
    SELECT 'CATALOG_MISSING_SKU' AS reason_code
    FROM catalog_products p
    WHERE (p.sku IS NULL OR btrim(p.sku) = '')
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'CATALOG_MISSING_CATEGORY'
    FROM catalog_products p
    WHERE (p.top_category_id IS NULL OR
           NOT EXISTS (SELECT 1 FROM catalog_categories c WHERE c.category_id = p.top_category_id))
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'AVAILABILITY_NOT_READY'
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online
      AND s.block_reason <> 'CATEGORY_ONLINE_DISABLED'
      AND NOT EXISTS (SELECT 1 FROM catalog_product_inventory i WHERE i.product_id = p.product_id)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'COMMERCE_MAPPING_MISSING'
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN (
        SELECT DISTINCT provider_key FROM commerce_product_mappings
        UNION
        SELECT DISTINCT provider_key FROM commerce_product_mutation_barriers
    ) u ON ($2::text = '' OR u.provider_key = $2::text)
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online AND s.category_allows_online
      AND ($1::text = '' OR p.store_id = $1::uuid)
      AND NOT EXISTS (SELECT 1 FROM commerce_product_mappings m
                      WHERE m.provider_key = u.provider_key AND m.product_id = p.product_id)
    UNION ALL
    SELECT 'CATEGORY_ONLINE_DISABLED'
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online
      AND NOT s.category_allows_online AND s.block_reason = 'CATEGORY_ONLINE_DISABLED'
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'COMMERCE_SYNC_AMBIGUOUS'
    FROM commerce_product_mutation_barriers b
    JOIN catalog_products p ON p.product_id = b.product_id
    WHERE b.state IN ('in_flight', 'uncertain')
      AND ($2::text = '' OR b.provider_key = $2::text)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'COMMERCE_STORE_CONFLICT'
    FROM commerce_product_mappings m
    JOIN catalog_products p ON p.product_id = m.product_id
    WHERE m.store_id IS NOT NULL AND p.store_id IS NOT NULL
      AND m.store_id <> p.store_id
      AND ($2::text = '' OR m.provider_key = $2::text)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    -- Phase 17 variant health (SKU/inventory ownership on ProductVariant):
    --   PRODUCT_NO_ACTIVE_VARIANTS   — active product with zero active
    --                               non-tombstoned variants: nothing to
    --                               sell under the variant model.
    --   PRODUCT_NO_SELLABLE_VARIANT  — EFFECTIVELY online-eligible product
    --                               (same canonical rule as commerce
    --                               publication) with no variant that is
    --                               active, non-tombstoned and stocked.
    --   VARIANT_DUPLICATE_COMBINATION— same (Store, product,
    --                               combination_key) on two live variant
    --                               rows (possible for unscoped legacy
    --                               rows only: Store-scoped rows collide
    --                               in the unique constraint). Data-level
    --                               duplicates are tolerated at
    --                               projection and surfaced here.
    --   VARIANT_MISSING_SKU          — projected variant SKU absent/blank
    --                               (defensive mirror of
    --                               CATALOG_MISSING_SKU).
    --   VARIANT_MAPPING_MISSING      — EFFECTIVELY online-eligible live
    --                               variant with no mapping for a known
    --                               provider (variant-granularity mirror
    --                               of COMMERCE_MAPPING_MISSING).
    --   VARIANT_INTENTIONALLY_OFFLINE— INFORMATIONAL (never a defect):
    --                               variant of an online-eligible product
    --                               deliberately inactive or tombstoned.
    SELECT 'PRODUCT_NO_ACTIVE_VARIANTS'
    FROM catalog_products p
    WHERE p.is_active
      AND NOT EXISTS (SELECT 1 FROM catalog_product_variants v
                      WHERE v.product_id = p.product_id AND v.is_active AND NOT v.deleted)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'PRODUCT_NO_SELLABLE_VARIANT'
    FROM catalog_products p
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online AND s.category_allows_online
      AND NOT EXISTS (
        SELECT 1 FROM catalog_product_variants v
        LEFT JOIN catalog_product_variant_inventory vi ON vi.variant_id = v.variant_id
        WHERE v.product_id = p.product_id AND v.is_active AND NOT v.deleted
          AND COALESCE(vi.stock_quantity, 0) > 0)
      AND ($1::text = '' OR p.store_id = $1::uuid)
    UNION ALL
    SELECT 'VARIANT_DUPLICATE_COMBINATION'
    FROM catalog_product_variants v
    WHERE NOT v.deleted
      AND EXISTS (SELECT 1 FROM catalog_product_variants o
                  WHERE o.product_id = v.product_id
                    AND o.combination_key = v.combination_key
                    AND o.variant_id <> v.variant_id
                    AND o.store_id IS NOT DISTINCT FROM v.store_id
                    AND NOT o.deleted)
      AND ($1::text = '' OR v.store_id = $1::uuid)
    UNION ALL
    SELECT 'VARIANT_MISSING_SKU'
    FROM catalog_product_variants v
    WHERE (v.sku IS NULL OR btrim(v.sku) = '')
      AND ($1::text = '' OR v.store_id = $1::uuid)
    UNION ALL
    SELECT 'VARIANT_MAPPING_MISSING'
    FROM catalog_product_variants v
    JOIN catalog_products p ON p.product_id = v.product_id
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN (
        SELECT DISTINCT provider_key FROM commerce_product_mappings
        UNION
        SELECT DISTINCT provider_key FROM commerce_product_mutation_barriers
    ) u ON ($2::text = '' OR u.provider_key = $2::text)
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online AND s.category_allows_online
      AND v.is_active AND NOT v.deleted
      AND ($1::text = '' OR p.store_id = $1::uuid)
      AND NOT EXISTS (SELECT 1 FROM commerce_product_variant_mappings m
                      WHERE m.provider_key = u.provider_key AND m.variant_id = v.variant_id)
    UNION ALL
    SELECT 'VARIANT_INTENTIONALLY_OFFLINE'
    FROM catalog_product_variants v
    JOIN catalog_products p ON p.product_id = v.product_id
    JOIN catalog_product_sales_policies pol ON pol.product_id = p.product_id
    JOIN catalog_product_online_state s ON s.product_id = p.product_id
    WHERE p.is_active AND pol.sell_online AND s.category_allows_online
      AND (NOT v.is_active OR v.deleted)
      AND ($1::text = '' OR p.store_id = $1::uuid)
) reasons
GROUP BY reason_code
`

type CatalogHealthSummaryParams struct {
	StoreID     string `json:"store_id"`
	ProviderKey string `json:"provider_key"`
}

type CatalogHealthSummaryRow struct {
	ReasonCode string `json:"reason_code"`
	Products   int64  `json:"products"`
}

// Bounded summary counts per stable health reason code. Exact predicates
// (documented in docs/decisions/0045 and tested):
//
//	CATALOG_MISSING_SKU       — projected SKU absent/blank (missing only;
//	                            legacy stored SKUs are preserved, never
//	                            regex-rejected).
//	CATALOG_MISSING_CATEGORY  — required root/top category absent or
//	                            unresolved (optional subcategories and
//	                            hidden categories are NOT failures).
//	AVAILABILITY_NOT_READY    — online-eligible product (active +
//	                            sell_online) with no projected inventory
//	                            row (frozen readiness: product + policy
//	                            + inventory), excluding products
//	                            INTENTIONALLY Category-suppressed
//	                            (Phase 13 §169: deliberate suppression is
//	                            never fabricated as not-ready; missing
//	                            hierarchy state still reports not-ready
//	                            alongside CATALOG_MISSING_CATEGORY).
//	COMMERCE_MAPPING_MISSING  — EFFECTIVELY online-eligible product with
//	                            no mapping for a known provider. Uses
//	                            the same canonical eligibility rule as
//	                            commerce publication (the
//	                            catalog_product_online_state view):
//	                            intentionally offline/inactive AND
//	                            Category-suppressed products are never
//	                            flagged (Phase 13 §113/§114).
//	CATEGORY_ONLINE_DISABLED  — INFORMATIONAL (Phase 13 §116): active +
//	                            sell_online Product intentionally
//	                            suppressed by Category policy. Not a
//	                            catalog-health failure — it is deliberate
//	                            configuration.
//	COMMERCE_SYNC_AMBIGUOUS   — an unresolved mutation barrier exists for
//	                            the product (needs operator settlement;
//	                            read-only, never settled here).
//	COMMERCE_STORE_CONFLICT   — durable mapping Store ownership differs
//	                            from the catalog product's Store.
//
// Provider-scoped reasons are computed against the durable provider
// universe (provider keys observed in mappings or barriers).
func (q *Queries) CatalogHealthSummary(ctx context.Context, arg CatalogHealthSummaryParams) ([]CatalogHealthSummaryRow, error) {
	rows, err := q.db.Query(ctx, catalogHealthSummary, arg.StoreID, arg.ProviderKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogHealthSummaryRow{}
	for rows.Next() {
		var i CatalogHealthSummaryRow
		if err := rows.Scan(&i.ReasonCode, &i.Products); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardOrderAnalytics = `-- name: DashboardOrderAnalytics :many

SELECT
    provider_key,
    canonical_status,
    currency,
    count(*)::bigint AS orders_count,
    COALESCE(sum(total_minor), 0)::bigint AS value_minor
FROM commerce_online_orders
WHERE created_at >= $1
  AND created_at < $2
  AND ($3::text = '' OR provider_key = $3::text)
  AND ($4::text = '' OR store_id = $4::uuid)
  AND ($5::text = '' OR currency = $5::text)
GROUP BY provider_key, canonical_status, currency
`

type DashboardOrderAnalyticsParams struct {
	StartUtc    pgtype.Timestamptz `json:"start_utc"`
	EndUtc      pgtype.Timestamptz `json:"end_utc"`
	ProviderKey string             `json:"provider_key"`
	StoreID     string             `json:"store_id"`
	Currency    string             `json:"currency"`
}

type DashboardOrderAnalyticsRow struct {
	ProviderKey     string `json:"provider_key"`
	CanonicalStatus string `json:"canonical_status"`
	Currency        string `json:"currency"`
	OrdersCount     int64  `json:"orders_count"`
	ValueMinor      int64  `json:"value_minor"`
}

// Phase 12 — Catalog Health + online-order operational analytics.
//
// Everything here is READ-ONLY durable MoonLight state. No provider is
// contacted live; no barrier is settled, cleared or modified; no Store
// adoption or reconciliation ever runs from these reads.
// Operational provider-order aggregation (Phase 12). This is NOT
// financial revenue: provider online orders are operational commerce
// truth and are never added to canonical finalized Retail Sales. Groups
// durable online-order rows by provider, canonical status and currency
// over the report window; currencies are never summed together. The
// optional provider filter (” = all providers) is a narrowing filter
// only — historical rows stay queryable when a provider is disabled.
func (q *Queries) DashboardOrderAnalytics(ctx context.Context, arg DashboardOrderAnalyticsParams) ([]DashboardOrderAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, dashboardOrderAnalytics,
		arg.StartUtc,
		arg.EndUtc,
		arg.ProviderKey,
		arg.StoreID,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardOrderAnalyticsRow{}
	for rows.Next() {
		var i DashboardOrderAnalyticsRow
		if err := rows.Scan(
			&i.ProviderKey,
			&i.CanonicalStatus,
			&i.Currency,
			&i.OrdersCount,
			&i.ValueMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
