// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_policy.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogOnlineConfiguredProducts = `-- name: CatalogOnlineConfiguredProducts :many
SELECT product_id, sell_offline, sell_online, online_allocation_limit, source_revision
FROM catalog_product_sales_policies
WHERE sell_online ORDER BY product_id
LIMIT $1
`

type CatalogOnlineConfiguredProductsRow struct {
	ProductID             pgtype.UUID `json:"product_id"`
	SellOffline           bool        `json:"sell_offline"`
	SellOnline            bool        `json:"sell_online"`
	OnlineAllocationLimit pgtype.Int8 `json:"online_allocation_limit"`
	SourceRevision        int64       `json:"source_revision"`
}

func (q *Queries) CatalogOnlineConfiguredProducts(ctx context.Context, limit int32) ([]CatalogOnlineConfiguredProductsRow, error) {
	rows, err := q.db.Query(ctx, catalogOnlineConfiguredProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogOnlineConfiguredProductsRow{}
	for rows.Next() {
		var i CatalogOnlineConfiguredProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.SellOffline,
			&i.SellOnline,
			&i.OnlineAllocationLimit,
			&i.SourceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogOnlineConfiguredProductsForStore = `-- name: CatalogOnlineConfiguredProductsForStore :many
SELECT pol.product_id, pol.sell_offline, pol.sell_online, pol.online_allocation_limit, pol.source_revision
FROM catalog_product_sales_policies pol
JOIN catalog_products p ON p.product_id = pol.product_id
WHERE pol.sell_online AND pol.store_id = $1
  AND p.store_id = pol.store_id
ORDER BY pol.product_id
LIMIT $2
`

type CatalogOnlineConfiguredProductsForStoreParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Limit   int32       `json:"limit"`
}

type CatalogOnlineConfiguredProductsForStoreRow struct {
	ProductID             pgtype.UUID `json:"product_id"`
	SellOffline           bool        `json:"sell_offline"`
	SellOnline            bool        `json:"sell_online"`
	OnlineAllocationLimit pgtype.Int8 `json:"online_allocation_limit"`
	SourceRevision        int64       `json:"source_revision"`
}

// Phase 9C Store-aware publication enumeration: online-configured
// products of exactly one proven Store through canonical projected
// state. Legacy NULL rows never match. The global variant above stays
// for administration/diagnostics and must not feed Store-specific
// provider writes.
// Phase 9-R1 F02: the policy's Store must also be the owning product's
// Store, so a contradictory product/policy pair can never be enumerated
// (and published) as another Store's resource.
func (q *Queries) CatalogOnlineConfiguredProductsForStore(ctx context.Context, arg CatalogOnlineConfiguredProductsForStoreParams) ([]CatalogOnlineConfiguredProductsForStoreRow, error) {
	rows, err := q.db.Query(ctx, catalogOnlineConfiguredProductsForStore, arg.StoreID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogOnlineConfiguredProductsForStoreRow{}
	for rows.Next() {
		var i CatalogOnlineConfiguredProductsForStoreRow
		if err := rows.Scan(
			&i.ProductID,
			&i.SellOffline,
			&i.SellOnline,
			&i.OnlineAllocationLimit,
			&i.SourceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductOnlineState = `-- name: CatalogProductOnlineState :one

SELECT product_id, store_id, category_allows_online, block_reason, blocking_category_id, policy_fingerprint, policy_version
FROM catalog_product_online_state
WHERE product_id = $1
`

// Phase 13 §62: canonical effective-online policy reads. The eligibility
// rule lives in ONE place — the catalog_product_online_state view
// (migration 00028) — and is consumed by commerce publication and
// Catalog Health alike; no provider adapter ever traverses the DAG.
func (q *Queries) CatalogProductOnlineState(ctx context.Context, productID pgtype.UUID) (CatalogProductOnlineState, error) {
	row := q.db.QueryRow(ctx, catalogProductOnlineState, productID)
	var i CatalogProductOnlineState
	err := row.Scan(
		&i.ProductID,
		&i.StoreID,
		&i.CategoryAllowsOnline,
		&i.BlockReason,
		&i.BlockingCategoryID,
		&i.PolicyFingerprint,
		&i.PolicyVersion,
	)
	return i, err
}

const catalogProductSalesPolicyByID = `-- name: CatalogProductSalesPolicyByID :one
SELECT product_id, sell_offline, sell_online, online_allocation_limit,
    source_revision, source_event_id, source_device_id, source_payload_hash, store_id
FROM catalog_product_sales_policies WHERE product_id = $1
`

type CatalogProductSalesPolicyByIDRow struct {
	ProductID             pgtype.UUID `json:"product_id"`
	SellOffline           bool        `json:"sell_offline"`
	SellOnline            bool        `json:"sell_online"`
	OnlineAllocationLimit pgtype.Int8 `json:"online_allocation_limit"`
	SourceRevision        int64       `json:"source_revision"`
	SourceEventID         pgtype.UUID `json:"source_event_id"`
	SourceDeviceID        pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash     []byte      `json:"source_payload_hash"`
	StoreID               pgtype.UUID `json:"store_id"`
}

func (q *Queries) CatalogProductSalesPolicyByID(ctx context.Context, productID pgtype.UUID) (CatalogProductSalesPolicyByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogProductSalesPolicyByID, productID)
	var i CatalogProductSalesPolicyByIDRow
	err := row.Scan(
		&i.ProductID,
		&i.SellOffline,
		&i.SellOnline,
		&i.OnlineAllocationLimit,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
		&i.StoreID,
	)
	return i, err
}

const catalogProductsOnlineState = `-- name: CatalogProductsOnlineState :many
SELECT product_id, store_id, category_allows_online, block_reason, blocking_category_id, policy_fingerprint, policy_version
FROM catalog_product_online_state
WHERE product_id = ANY($1::uuid[])
`

func (q *Queries) CatalogProductsOnlineState(ctx context.Context, dollar_1 []pgtype.UUID) ([]CatalogProductOnlineState, error) {
	rows, err := q.db.Query(ctx, catalogProductsOnlineState, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductOnlineState{}
	for rows.Next() {
		var i CatalogProductOnlineState
		if err := rows.Scan(
			&i.ProductID,
			&i.StoreID,
			&i.CategoryAllowsOnline,
			&i.BlockReason,
			&i.BlockingCategoryID,
			&i.PolicyFingerprint,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCatalogProductSalesPolicy = `-- name: UpsertCatalogProductSalesPolicy :exec

INSERT INTO catalog_product_sales_policies (
    product_id, sell_offline, sell_online, online_allocation_limit,
    source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at, store_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (product_id) DO UPDATE SET
    sell_offline = excluded.sell_offline, sell_online = excluded.sell_online,
    online_allocation_limit = excluded.online_allocation_limit,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at,
    store_id = COALESCE(excluded.store_id, catalog_product_sales_policies.store_id),
    projected_at = now()
`

type UpsertCatalogProductSalesPolicyParams struct {
	ProductID             pgtype.UUID        `json:"product_id"`
	SellOffline           bool               `json:"sell_offline"`
	SellOnline            bool               `json:"sell_online"`
	OnlineAllocationLimit pgtype.Int8        `json:"online_allocation_limit"`
	SourceRevision        int64              `json:"source_revision"`
	SourceEventID         pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID        pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash     []byte             `json:"source_payload_hash"`
	SourceReceivedAt      pgtype.Timestamptz `json:"source_received_at"`
	StoreID               pgtype.UUID        `json:"store_id"`
}

// Phase 5B product sales-policy projection. Current-state replace
// semantics per product: one row carrying the highest valid revision.
// Depends on the core product projection (dependency wait, never terminal
// for missing products); inactive products still project policy rows.
// Phase 9B store ownership: see UpsertCatalogCategory.
func (q *Queries) UpsertCatalogProductSalesPolicy(ctx context.Context, arg UpsertCatalogProductSalesPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogProductSalesPolicy,
		arg.ProductID,
		arg.SellOffline,
		arg.SellOnline,
		arg.OnlineAllocationLimit,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
		arg.StoreID,
	)
	return err
}
