// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_variants.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogProductVariantAttributes = `-- name: CatalogProductVariantAttributes :many
SELECT definition_code, value_code, name_ar, name_en, definition_name_ar, definition_name_en, position
FROM catalog_product_variant_attribute_values WHERE variant_id = $1
ORDER BY position, definition_code
`

type CatalogProductVariantAttributesRow struct {
	DefinitionCode   string      `json:"definition_code"`
	ValueCode        string      `json:"value_code"`
	NameAr           string      `json:"name_ar"`
	NameEn           pgtype.Text `json:"name_en"`
	DefinitionNameAr string      `json:"definition_name_ar"`
	DefinitionNameEn pgtype.Text `json:"definition_name_en"`
	Position         int32       `json:"position"`
}

func (q *Queries) CatalogProductVariantAttributes(ctx context.Context, variantID pgtype.UUID) ([]CatalogProductVariantAttributesRow, error) {
	rows, err := q.db.Query(ctx, catalogProductVariantAttributes, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductVariantAttributesRow{}
	for rows.Next() {
		var i CatalogProductVariantAttributesRow
		if err := rows.Scan(
			&i.DefinitionCode,
			&i.ValueCode,
			&i.NameAr,
			&i.NameEn,
			&i.DefinitionNameAr,
			&i.DefinitionNameEn,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductVariantByID = `-- name: CatalogProductVariantByID :one
SELECT variant_id, product_id, sku, is_active, deleted,
    price_egp_cents, price_usd_cents, position, combination_key,
    variant_revision, catalog_revision,
    source_event_id, source_device_id, source_payload_hash, store_id
FROM catalog_product_variants WHERE variant_id = $1
`

type CatalogProductVariantByIDRow struct {
	VariantID         pgtype.UUID `json:"variant_id"`
	ProductID         pgtype.UUID `json:"product_id"`
	Sku               string      `json:"sku"`
	IsActive          bool        `json:"is_active"`
	Deleted           bool        `json:"deleted"`
	PriceEgpCents     pgtype.Int8 `json:"price_egp_cents"`
	PriceUsdCents     pgtype.Int8 `json:"price_usd_cents"`
	Position          int32       `json:"position"`
	CombinationKey    string      `json:"combination_key"`
	VariantRevision   int64       `json:"variant_revision"`
	CatalogRevision   int64       `json:"catalog_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
	StoreID           pgtype.UUID `json:"store_id"`
}

func (q *Queries) CatalogProductVariantByID(ctx context.Context, variantID pgtype.UUID) (CatalogProductVariantByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogProductVariantByID, variantID)
	var i CatalogProductVariantByIDRow
	err := row.Scan(
		&i.VariantID,
		&i.ProductID,
		&i.Sku,
		&i.IsActive,
		&i.Deleted,
		&i.PriceEgpCents,
		&i.PriceUsdCents,
		&i.Position,
		&i.CombinationKey,
		&i.VariantRevision,
		&i.CatalogRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
		&i.StoreID,
	)
	return i, err
}

const catalogProductVariantDependentStores = `-- name: CatalogProductVariantDependentStores :many

SELECT i.store_id FROM catalog_product_variant_inventory i
WHERE i.variant_id = $1 AND i.store_id IS NOT NULL
UNION
SELECT m.store_id FROM commerce_product_variant_mappings m
WHERE m.variant_id = $1 AND m.store_id IS NOT NULL
`

// Phase 9-R1 F02 mirror: proven Store ownership of a variant's durable
// dependents (inventory + provider mappings). Adopting a variant into a
// Store must never leave a dependent owned by another proven Store.
func (q *Queries) CatalogProductVariantDependentStores(ctx context.Context, variantID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, catalogProductVariantDependentStores, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var store_id pgtype.UUID
		if err := rows.Scan(&store_id); err != nil {
			return nil, err
		}
		items = append(items, store_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductVariantInventoryByID = `-- name: CatalogProductVariantInventoryByID :one
SELECT variant_id, product_id, sku, stock_quantity,
    ready, sell_online, online_allocation_limit,
    policy_revision, catalog_revision, source_revision,
    source_event_id, source_device_id, source_payload_hash,
    source_received_at, projected_at, store_id
FROM catalog_product_variant_inventory WHERE variant_id = $1
`

func (q *Queries) CatalogProductVariantInventoryByID(ctx context.Context, variantID pgtype.UUID) (CatalogProductVariantInventory, error) {
	row := q.db.QueryRow(ctx, catalogProductVariantInventoryByID, variantID)
	var i CatalogProductVariantInventory
	err := row.Scan(
		&i.VariantID,
		&i.ProductID,
		&i.Sku,
		&i.StockQuantity,
		&i.Ready,
		&i.SellOnline,
		&i.OnlineAllocationLimit,
		&i.PolicyRevision,
		&i.CatalogRevision,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
		&i.SourceReceivedAt,
		&i.ProjectedAt,
		&i.StoreID,
	)
	return i, err
}

const catalogProductVariantsByProduct = `-- name: CatalogProductVariantsByProduct :many
SELECT variant_id, product_id, sku, is_active, deleted,
    price_egp_cents, price_usd_cents, position, combination_key,
    variant_revision, catalog_revision,
    source_event_id, source_device_id, source_payload_hash, store_id
FROM catalog_product_variants WHERE product_id = $1
ORDER BY position, variant_id
`

type CatalogProductVariantsByProductRow struct {
	VariantID         pgtype.UUID `json:"variant_id"`
	ProductID         pgtype.UUID `json:"product_id"`
	Sku               string      `json:"sku"`
	IsActive          bool        `json:"is_active"`
	Deleted           bool        `json:"deleted"`
	PriceEgpCents     pgtype.Int8 `json:"price_egp_cents"`
	PriceUsdCents     pgtype.Int8 `json:"price_usd_cents"`
	Position          int32       `json:"position"`
	CombinationKey    string      `json:"combination_key"`
	VariantRevision   int64       `json:"variant_revision"`
	CatalogRevision   int64       `json:"catalog_revision"`
	SourceEventID     pgtype.UUID `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash []byte      `json:"source_payload_hash"`
	StoreID           pgtype.UUID `json:"store_id"`
}

// Tombstones stay queryable for historical safety (callers decide).
func (q *Queries) CatalogProductVariantsByProduct(ctx context.Context, productID pgtype.UUID) ([]CatalogProductVariantsByProductRow, error) {
	rows, err := q.db.Query(ctx, catalogProductVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductVariantsByProductRow{}
	for rows.Next() {
		var i CatalogProductVariantsByProductRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ProductID,
			&i.Sku,
			&i.IsActive,
			&i.Deleted,
			&i.PriceEgpCents,
			&i.PriceUsdCents,
			&i.Position,
			&i.CombinationKey,
			&i.VariantRevision,
			&i.CatalogRevision,
			&i.SourceEventID,
			&i.SourceDeviceID,
			&i.SourcePayloadHash,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogVariantAvailabilityByVariantID = `-- name: CatalogVariantAvailabilityByVariantID :one
SELECT
    v.variant_id AS variant_id,
    v.product_id AS product_id,
    v.is_active AS variant_active,
    v.deleted AS variant_deleted,
    v.variant_revision AS variant_revision,
    v.sku AS variant_sku,
    p.is_active AS product_active,
    p.source_revision AS product_revision,
    pol.sell_online AS sell_online,
    pol.online_allocation_limit AS online_allocation_limit,
    pol.source_revision AS policy_revision,
    inv.stock_quantity AS stock_quantity,
    inv.sell_online AS variant_sell_online,
    inv.online_allocation_limit AS variant_allocation_limit,
    inv.ready AS variant_ready,
    inv.source_revision AS inventory_revision,
    inv.source_event_id AS inventory_event_id,
    inv.projected_at AS inventory_projected_at
FROM catalog_product_variants v
LEFT JOIN catalog_products p
  ON p.product_id = v.product_id
 AND (p.store_id IS NULL OR p.store_id = v.store_id)
LEFT JOIN catalog_product_sales_policies pol
  ON pol.product_id = v.product_id
 AND (pol.store_id IS NULL OR pol.store_id = v.store_id)
LEFT JOIN catalog_product_variant_inventory inv
  ON inv.variant_id = v.variant_id
 AND (inv.store_id IS NULL OR inv.store_id = v.store_id)
WHERE v.variant_id = $1
`

type CatalogVariantAvailabilityByVariantIDRow struct {
	VariantID              pgtype.UUID        `json:"variant_id"`
	ProductID              pgtype.UUID        `json:"product_id"`
	VariantActive          bool               `json:"variant_active"`
	VariantDeleted         bool               `json:"variant_deleted"`
	VariantRevision        int64              `json:"variant_revision"`
	VariantSku             string             `json:"variant_sku"`
	ProductActive          pgtype.Bool        `json:"product_active"`
	ProductRevision        pgtype.Int8        `json:"product_revision"`
	SellOnline             pgtype.Bool        `json:"sell_online"`
	OnlineAllocationLimit  pgtype.Int8        `json:"online_allocation_limit"`
	PolicyRevision         pgtype.Int8        `json:"policy_revision"`
	StockQuantity          pgtype.Int8        `json:"stock_quantity"`
	VariantSellOnline      pgtype.Bool        `json:"variant_sell_online"`
	VariantAllocationLimit pgtype.Int8        `json:"variant_allocation_limit"`
	VariantReady           pgtype.Bool        `json:"variant_ready"`
	InventoryRevision      pgtype.Int8        `json:"inventory_revision"`
	InventoryEventID       pgtype.UUID        `json:"inventory_event_id"`
	InventoryProjectedAt   pgtype.Timestamptz `json:"inventory_projected_at"`
}

// Per-variant ONLINE availability inputs (Phase 17). Centered on the
// variant: a dependency may back the variant only when it is unscoped
// legacy (NULL) or owned by the variant's exact proven Store, mirroring
// CatalogAvailabilityByProductID (a contradictory durable relationship
// can never expose foreign stock or policy as positive availability).
func (q *Queries) CatalogVariantAvailabilityByVariantID(ctx context.Context, variantID pgtype.UUID) (CatalogVariantAvailabilityByVariantIDRow, error) {
	row := q.db.QueryRow(ctx, catalogVariantAvailabilityByVariantID, variantID)
	var i CatalogVariantAvailabilityByVariantIDRow
	err := row.Scan(
		&i.VariantID,
		&i.ProductID,
		&i.VariantActive,
		&i.VariantDeleted,
		&i.VariantRevision,
		&i.VariantSku,
		&i.ProductActive,
		&i.ProductRevision,
		&i.SellOnline,
		&i.OnlineAllocationLimit,
		&i.PolicyRevision,
		&i.StockQuantity,
		&i.VariantSellOnline,
		&i.VariantAllocationLimit,
		&i.VariantReady,
		&i.InventoryRevision,
		&i.InventoryEventID,
		&i.InventoryProjectedAt,
	)
	return i, err
}

const deleteCatalogProductVariantAttributes = `-- name: DeleteCatalogProductVariantAttributes :exec
DELETE FROM catalog_product_variant_attribute_values WHERE variant_id = $1
`

func (q *Queries) DeleteCatalogProductVariantAttributes(ctx context.Context, variantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogProductVariantAttributes, variantID)
	return err
}

const insertCatalogProductVariantAttribute = `-- name: InsertCatalogProductVariantAttribute :exec
INSERT INTO catalog_product_variant_attribute_values (
    variant_id, definition_code, value_code,
    name_ar, name_en, definition_name_ar, definition_name_en, position
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (variant_id, definition_code) DO UPDATE SET
    value_code = excluded.value_code, name_ar = excluded.name_ar, name_en = excluded.name_en,
    definition_name_ar = excluded.definition_name_ar, definition_name_en = excluded.definition_name_en,
    position = excluded.position
`

type InsertCatalogProductVariantAttributeParams struct {
	VariantID        pgtype.UUID `json:"variant_id"`
	DefinitionCode   string      `json:"definition_code"`
	ValueCode        string      `json:"value_code"`
	NameAr           string      `json:"name_ar"`
	NameEn           pgtype.Text `json:"name_en"`
	DefinitionNameAr string      `json:"definition_name_ar"`
	DefinitionNameEn pgtype.Text `json:"definition_name_en"`
	Position         int32       `json:"position"`
}

func (q *Queries) InsertCatalogProductVariantAttribute(ctx context.Context, arg InsertCatalogProductVariantAttributeParams) error {
	_, err := q.db.Exec(ctx, insertCatalogProductVariantAttribute,
		arg.VariantID,
		arg.DefinitionCode,
		arg.ValueCode,
		arg.NameAr,
		arg.NameEn,
		arg.DefinitionNameAr,
		arg.DefinitionNameEn,
		arg.Position,
	)
	return err
}

const upsertCatalogProductVariant = `-- name: UpsertCatalogProductVariant :exec

INSERT INTO catalog_product_variants (
    variant_id, product_id, sku, is_active, deleted,
    price_egp_cents, price_usd_cents, position, combination_key,
    variant_revision, catalog_revision,
    source_event_id, source_device_id, source_payload_hash, source_received_at, store_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (variant_id) DO UPDATE SET
    product_id = excluded.product_id, sku = excluded.sku,
    is_active = excluded.is_active, deleted = excluded.deleted,
    price_egp_cents = excluded.price_egp_cents, price_usd_cents = excluded.price_usd_cents,
    position = excluded.position, combination_key = excluded.combination_key,
    variant_revision = excluded.variant_revision, catalog_revision = excluded.catalog_revision,
    source_event_id = excluded.source_event_id, source_device_id = excluded.source_device_id,
    source_payload_hash = excluded.source_payload_hash, source_received_at = excluded.source_received_at,
    store_id = COALESCE(excluded.store_id, catalog_product_variants.store_id),
    projected_at = now()
`

type UpsertCatalogProductVariantParams struct {
	VariantID         pgtype.UUID        `json:"variant_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	Sku               string             `json:"sku"`
	IsActive          bool               `json:"is_active"`
	Deleted           bool               `json:"deleted"`
	PriceEgpCents     pgtype.Int8        `json:"price_egp_cents"`
	PriceUsdCents     pgtype.Int8        `json:"price_usd_cents"`
	Position          int32              `json:"position"`
	CombinationKey    string             `json:"combination_key"`
	VariantRevision   int64              `json:"variant_revision"`
	CatalogRevision   int64              `json:"catalog_revision"`
	SourceEventID     pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID    pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash []byte             `json:"source_payload_hash"`
	SourceReceivedAt  pgtype.Timestamptz `json:"source_received_at"`
	StoreID           pgtype.UUID        `json:"store_id"`
}

// Phase 17 product & physical variant projections (SKU/inventory
// ownership on ProductVariant). Current-state replace semantics per
// stream: one variant row carrying the highest valid variant_revision
// (catalog stream), one inventory row carrying the highest valid
// inventory_revision (inventory stream); attribute values are replaced
// transactionally per variant revision. Store ownership follows the 00023
// model (see UpsertCatalogCategory): NULL = unscoped legacy, COALESCE
// preserves proven ownership, cross-Store writes are fenced in Go before
// any upsert runs.
// Phase 9B store ownership semantics: see UpsertCatalogCategory.
func (q *Queries) UpsertCatalogProductVariant(ctx context.Context, arg UpsertCatalogProductVariantParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogProductVariant,
		arg.VariantID,
		arg.ProductID,
		arg.Sku,
		arg.IsActive,
		arg.Deleted,
		arg.PriceEgpCents,
		arg.PriceUsdCents,
		arg.Position,
		arg.CombinationKey,
		arg.VariantRevision,
		arg.CatalogRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
		arg.StoreID,
	)
	return err
}

const upsertCatalogProductVariantInventory = `-- name: UpsertCatalogProductVariantInventory :exec
INSERT INTO catalog_product_variant_inventory (
    variant_id, product_id, sku, stock_quantity,
    ready, sell_online, online_allocation_limit,
    policy_revision, catalog_revision, source_revision,
    source_event_id, source_device_id, source_payload_hash, source_received_at, store_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (variant_id) DO UPDATE SET
    product_id = excluded.product_id, sku = excluded.sku,
    stock_quantity = excluded.stock_quantity,
    ready = excluded.ready, sell_online = excluded.sell_online,
    online_allocation_limit = excluded.online_allocation_limit,
    policy_revision = excluded.policy_revision, catalog_revision = excluded.catalog_revision,
    source_revision = excluded.source_revision,
    source_event_id = excluded.source_event_id, source_device_id = excluded.source_device_id,
    source_payload_hash = excluded.source_payload_hash, source_received_at = excluded.source_received_at,
    store_id = COALESCE(excluded.store_id, catalog_product_variant_inventory.store_id),
    projected_at = now()
`

type UpsertCatalogProductVariantInventoryParams struct {
	VariantID             pgtype.UUID        `json:"variant_id"`
	ProductID             pgtype.UUID        `json:"product_id"`
	Sku                   string             `json:"sku"`
	StockQuantity         int64              `json:"stock_quantity"`
	Ready                 bool               `json:"ready"`
	SellOnline            bool               `json:"sell_online"`
	OnlineAllocationLimit pgtype.Int8        `json:"online_allocation_limit"`
	PolicyRevision        int64              `json:"policy_revision"`
	CatalogRevision       int64              `json:"catalog_revision"`
	SourceRevision        int64              `json:"source_revision"`
	SourceEventID         pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID        pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash     []byte             `json:"source_payload_hash"`
	SourceReceivedAt      pgtype.Timestamptz `json:"source_received_at"`
	StoreID               pgtype.UUID        `json:"store_id"`
}

// Phase 9B store ownership semantics: see UpsertCatalogCategory. The
// policy/catalog mirror columns are display + effective-cap context
// only; source_revision is this stream's inventory_revision gate.
func (q *Queries) UpsertCatalogProductVariantInventory(ctx context.Context, arg UpsertCatalogProductVariantInventoryParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogProductVariantInventory,
		arg.VariantID,
		arg.ProductID,
		arg.Sku,
		arg.StockQuantity,
		arg.Ready,
		arg.SellOnline,
		arg.OnlineAllocationLimit,
		arg.PolicyRevision,
		arg.CatalogRevision,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
		arg.StoreID,
	)
	return err
}
