// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_policy.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogOnlineConfiguredProducts = `-- name: CatalogOnlineConfiguredProducts :many
SELECT product_id, sell_offline, sell_online, online_allocation_limit, source_revision
FROM catalog_product_sales_policies
WHERE sell_online ORDER BY product_id
LIMIT $1
`

type CatalogOnlineConfiguredProductsRow struct {
	ProductID             pgtype.UUID `json:"product_id"`
	SellOffline           bool        `json:"sell_offline"`
	SellOnline            bool        `json:"sell_online"`
	OnlineAllocationLimit pgtype.Int8 `json:"online_allocation_limit"`
	SourceRevision        int64       `json:"source_revision"`
}

func (q *Queries) CatalogOnlineConfiguredProducts(ctx context.Context, limit int32) ([]CatalogOnlineConfiguredProductsRow, error) {
	rows, err := q.db.Query(ctx, catalogOnlineConfiguredProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogOnlineConfiguredProductsRow{}
	for rows.Next() {
		var i CatalogOnlineConfiguredProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.SellOffline,
			&i.SellOnline,
			&i.OnlineAllocationLimit,
			&i.SourceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogProductSalesPolicyByID = `-- name: CatalogProductSalesPolicyByID :one
SELECT product_id, sell_offline, sell_online, online_allocation_limit,
    source_revision, source_event_id, source_device_id, source_payload_hash, store_id
FROM catalog_product_sales_policies WHERE product_id = $1
`

type CatalogProductSalesPolicyByIDRow struct {
	ProductID             pgtype.UUID `json:"product_id"`
	SellOffline           bool        `json:"sell_offline"`
	SellOnline            bool        `json:"sell_online"`
	OnlineAllocationLimit pgtype.Int8 `json:"online_allocation_limit"`
	SourceRevision        int64       `json:"source_revision"`
	SourceEventID         pgtype.UUID `json:"source_event_id"`
	SourceDeviceID        pgtype.UUID `json:"source_device_id"`
	SourcePayloadHash     []byte      `json:"source_payload_hash"`
	StoreID               pgtype.UUID `json:"store_id"`
}

func (q *Queries) CatalogProductSalesPolicyByID(ctx context.Context, productID pgtype.UUID) (CatalogProductSalesPolicyByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogProductSalesPolicyByID, productID)
	var i CatalogProductSalesPolicyByIDRow
	err := row.Scan(
		&i.ProductID,
		&i.SellOffline,
		&i.SellOnline,
		&i.OnlineAllocationLimit,
		&i.SourceRevision,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SourcePayloadHash,
		&i.StoreID,
	)
	return i, err
}

const upsertCatalogProductSalesPolicy = `-- name: UpsertCatalogProductSalesPolicy :exec

INSERT INTO catalog_product_sales_policies (
    product_id, sell_offline, sell_online, online_allocation_limit,
    source_revision, source_event_id, source_device_id,
    source_payload_hash, source_received_at, store_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (product_id) DO UPDATE SET
    sell_offline = excluded.sell_offline, sell_online = excluded.sell_online,
    online_allocation_limit = excluded.online_allocation_limit,
    source_revision = excluded.source_revision, source_event_id = excluded.source_event_id,
    source_device_id = excluded.source_device_id, source_payload_hash = excluded.source_payload_hash,
    source_received_at = excluded.source_received_at,
    store_id = COALESCE(excluded.store_id, catalog_product_sales_policies.store_id),
    projected_at = now()
`

type UpsertCatalogProductSalesPolicyParams struct {
	ProductID             pgtype.UUID        `json:"product_id"`
	SellOffline           bool               `json:"sell_offline"`
	SellOnline            bool               `json:"sell_online"`
	OnlineAllocationLimit pgtype.Int8        `json:"online_allocation_limit"`
	SourceRevision        int64              `json:"source_revision"`
	SourceEventID         pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID        pgtype.UUID        `json:"source_device_id"`
	SourcePayloadHash     []byte             `json:"source_payload_hash"`
	SourceReceivedAt      pgtype.Timestamptz `json:"source_received_at"`
	StoreID               pgtype.UUID        `json:"store_id"`
}

// Phase 5B product sales-policy projection. Current-state replace
// semantics per product: one row carrying the highest valid revision.
// Depends on the core product projection (dependency wait, never terminal
// for missing products); inactive products still project policy rows.
// Phase 9B store ownership: see UpsertCatalogCategory.
func (q *Queries) UpsertCatalogProductSalesPolicy(ctx context.Context, arg UpsertCatalogProductSalesPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogProductSalesPolicy,
		arg.ProductID,
		arg.SellOffline,
		arg.SellOnline,
		arg.OnlineAllocationLimit,
		arg.SourceRevision,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SourcePayloadHash,
		arg.SourceReceivedAt,
		arg.StoreID,
	)
	return err
}
