// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commerce_mapping.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptCommerceProductMappingStore = `-- name: AdoptCommerceProductMappingStore :one
UPDATE commerce_product_mappings SET store_id = $3, updated_at = now()
WHERE provider_key = $1 AND product_id = $2 AND store_id IS NULL
RETURNING provider_key, product_id, external_product_id, store_id, created_at, updated_at
`

type AdoptCommerceProductMappingStoreParams struct {
	ProviderKey string      `json:"provider_key"`
	ProductID   pgtype.UUID `json:"product_id"`
	StoreID     pgtype.UUID `json:"store_id"`
}

type AdoptCommerceProductMappingStoreRow struct {
	ProviderKey       string             `json:"provider_key"`
	ProductID         pgtype.UUID        `json:"product_id"`
	ExternalProductID string             `json:"external_product_id"`
	StoreID           pgtype.UUID        `json:"store_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Phase 9C one-time legacy adoption: a NULL mapping adopts the proven
// Store of its own product. The WHERE clause makes concurrent adoption
// deterministic (same product implies same Store); a lost race reads
// back the winner instead of overwriting.
func (q *Queries) AdoptCommerceProductMappingStore(ctx context.Context, arg AdoptCommerceProductMappingStoreParams) (AdoptCommerceProductMappingStoreRow, error) {
	row := q.db.QueryRow(ctx, adoptCommerceProductMappingStore, arg.ProviderKey, arg.ProductID, arg.StoreID)
	var i AdoptCommerceProductMappingStoreRow
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.ExternalProductID,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommerceProductMapping = `-- name: CreateCommerceProductMapping :one
INSERT INTO commerce_product_mappings (provider_key, product_id, external_product_id, store_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING provider_key, product_id, external_product_id, store_id, created_at, updated_at
`

type CreateCommerceProductMappingParams struct {
	ProviderKey       string      `json:"provider_key"`
	ProductID         pgtype.UUID `json:"product_id"`
	ExternalProductID string      `json:"external_product_id"`
	StoreID           pgtype.UUID `json:"store_id"`
}

type CreateCommerceProductMappingRow struct {
	ProviderKey       string             `json:"provider_key"`
	ProductID         pgtype.UUID        `json:"product_id"`
	ExternalProductID string             `json:"external_product_id"`
	StoreID           pgtype.UUID        `json:"store_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Phase 9C: store_id mirrors the authoritative catalog product at
// creation (NULL for legacy products). ON CONFLICT DO NOTHING keeps the
// frozen same-pair idempotency; adoption and cross-Store conflicts are
// decided in Go before insert.
func (q *Queries) CreateCommerceProductMapping(ctx context.Context, arg CreateCommerceProductMappingParams) (CreateCommerceProductMappingRow, error) {
	row := q.db.QueryRow(ctx, createCommerceProductMapping,
		arg.ProviderKey,
		arg.ProductID,
		arg.ExternalProductID,
		arg.StoreID,
	)
	var i CreateCommerceProductMappingRow
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.ExternalProductID,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommerceProductVariantMapping = `-- name: CreateCommerceProductVariantMapping :one
INSERT INTO commerce_product_variant_mappings (provider_key, product_id, variant_id, external_product_id, external_variant_id, store_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
RETURNING provider_key, product_id, variant_id, external_product_id, external_variant_id, store_id, created_at, updated_at
`

type CreateCommerceProductVariantMappingParams struct {
	ProviderKey       string      `json:"provider_key"`
	ProductID         pgtype.UUID `json:"product_id"`
	VariantID         pgtype.UUID `json:"variant_id"`
	ExternalProductID string      `json:"external_product_id"`
	ExternalVariantID string      `json:"external_variant_id"`
	StoreID           pgtype.UUID `json:"store_id"`
}

// store_id mirrors the authoritative catalog product at creation (NULL
// for legacy/unprojected products). ON CONFLICT DO NOTHING keeps
// same-pair idempotency; remaps and cross-variant external reuse are
// classified in Go before insert.
func (q *Queries) CreateCommerceProductVariantMapping(ctx context.Context, arg CreateCommerceProductVariantMappingParams) (CommerceProductVariantMapping, error) {
	row := q.db.QueryRow(ctx, createCommerceProductVariantMapping,
		arg.ProviderKey,
		arg.ProductID,
		arg.VariantID,
		arg.ExternalProductID,
		arg.ExternalVariantID,
		arg.StoreID,
	)
	var i CommerceProductVariantMapping
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.VariantID,
		&i.ExternalProductID,
		&i.ExternalVariantID,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCommerceProductMappingByExternal = `-- name: FindCommerceProductMappingByExternal :one
SELECT provider_key, product_id, external_product_id, store_id, created_at, updated_at
FROM commerce_product_mappings
WHERE provider_key = $1 AND external_product_id = $2
`

type FindCommerceProductMappingByExternalParams struct {
	ProviderKey       string `json:"provider_key"`
	ExternalProductID string `json:"external_product_id"`
}

type FindCommerceProductMappingByExternalRow struct {
	ProviderKey       string             `json:"provider_key"`
	ProductID         pgtype.UUID        `json:"product_id"`
	ExternalProductID string             `json:"external_product_id"`
	StoreID           pgtype.UUID        `json:"store_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindCommerceProductMappingByExternal(ctx context.Context, arg FindCommerceProductMappingByExternalParams) (FindCommerceProductMappingByExternalRow, error) {
	row := q.db.QueryRow(ctx, findCommerceProductMappingByExternal, arg.ProviderKey, arg.ExternalProductID)
	var i FindCommerceProductMappingByExternalRow
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.ExternalProductID,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCommerceProductVariantMappingByExternal = `-- name: FindCommerceProductVariantMappingByExternal :one
SELECT provider_key, product_id, variant_id, external_product_id, external_variant_id, store_id, created_at, updated_at
FROM commerce_product_variant_mappings
WHERE provider_key = $1 AND external_product_id = $2 AND external_variant_id = $3
`

type FindCommerceProductVariantMappingByExternalParams struct {
	ProviderKey       string `json:"provider_key"`
	ExternalProductID string `json:"external_product_id"`
	ExternalVariantID string `json:"external_variant_id"`
}

func (q *Queries) FindCommerceProductVariantMappingByExternal(ctx context.Context, arg FindCommerceProductVariantMappingByExternalParams) (CommerceProductVariantMapping, error) {
	row := q.db.QueryRow(ctx, findCommerceProductVariantMappingByExternal, arg.ProviderKey, arg.ExternalProductID, arg.ExternalVariantID)
	var i CommerceProductVariantMapping
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.VariantID,
		&i.ExternalProductID,
		&i.ExternalVariantID,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommerceProductMapping = `-- name: GetCommerceProductMapping :one

SELECT provider_key, product_id, external_product_id, store_id, created_at, updated_at
FROM commerce_product_mappings
WHERE provider_key = $1 AND product_id = $2
`

type GetCommerceProductMappingParams struct {
	ProviderKey string      `json:"provider_key"`
	ProductID   pgtype.UUID `json:"product_id"`
}

type GetCommerceProductMappingRow struct {
	ProviderKey       string             `json:"provider_key"`
	ProductID         pgtype.UUID        `json:"product_id"`
	ExternalProductID string             `json:"external_product_id"`
	StoreID           pgtype.UUID        `json:"store_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Phase 6A durable provider product mappings. Integration state, not a
// projection: never cleared by catalog/policy/inventory rebuilds.
func (q *Queries) GetCommerceProductMapping(ctx context.Context, arg GetCommerceProductMappingParams) (GetCommerceProductMappingRow, error) {
	row := q.db.QueryRow(ctx, getCommerceProductMapping, arg.ProviderKey, arg.ProductID)
	var i GetCommerceProductMappingRow
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.ExternalProductID,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommerceProductVariantMapping = `-- name: GetCommerceProductVariantMapping :one

SELECT provider_key, product_id, variant_id, external_product_id, external_variant_id, store_id, created_at, updated_at
FROM commerce_product_variant_mappings
WHERE provider_key = $1 AND variant_id = $2
`

type GetCommerceProductVariantMappingParams struct {
	ProviderKey string      `json:"provider_key"`
	VariantID   pgtype.UUID `json:"variant_id"`
}

// Phase 17 durable ProductVariant mappings (00033): one MoonLight
// variant ↔ one provider variation per provider instance. Integration
// state, not a projection: never cleared by rebuilds, no FK to
// rebuildable projections.
func (q *Queries) GetCommerceProductVariantMapping(ctx context.Context, arg GetCommerceProductVariantMappingParams) (CommerceProductVariantMapping, error) {
	row := q.db.QueryRow(ctx, getCommerceProductVariantMapping, arg.ProviderKey, arg.VariantID)
	var i CommerceProductVariantMapping
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.VariantID,
		&i.ExternalProductID,
		&i.ExternalVariantID,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommerceProductMappingsForStore = `-- name: ListCommerceProductMappingsForStore :many
SELECT provider_key, product_id, external_product_id, store_id, created_at, updated_at
FROM commerce_product_mappings
WHERE provider_key = $1 AND store_id = $2
ORDER BY product_id
`

type ListCommerceProductMappingsForStoreParams struct {
	ProviderKey string      `json:"provider_key"`
	StoreID     pgtype.UUID `json:"store_id"`
}

type ListCommerceProductMappingsForStoreRow struct {
	ProviderKey       string             `json:"provider_key"`
	ProductID         pgtype.UUID        `json:"product_id"`
	ExternalProductID string             `json:"external_product_id"`
	StoreID           pgtype.UUID        `json:"store_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Phase 9C Store-scoped mapping enumeration. No global list exists, so
// there is no legacy behavior to preserve: scoped reads only.
func (q *Queries) ListCommerceProductMappingsForStore(ctx context.Context, arg ListCommerceProductMappingsForStoreParams) ([]ListCommerceProductMappingsForStoreRow, error) {
	rows, err := q.db.Query(ctx, listCommerceProductMappingsForStore, arg.ProviderKey, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommerceProductMappingsForStoreRow{}
	for rows.Next() {
		var i ListCommerceProductMappingsForStoreRow
		if err := rows.Scan(
			&i.ProviderKey,
			&i.ProductID,
			&i.ExternalProductID,
			&i.StoreID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommerceProductVariantMappings = `-- name: ListCommerceProductVariantMappings :many
SELECT provider_key, product_id, variant_id, external_product_id, external_variant_id, store_id, created_at, updated_at
FROM commerce_product_variant_mappings
WHERE provider_key = $1 AND product_id = $2
ORDER BY variant_id
`

type ListCommerceProductVariantMappingsParams struct {
	ProviderKey string      `json:"provider_key"`
	ProductID   pgtype.UUID `json:"product_id"`
}

func (q *Queries) ListCommerceProductVariantMappings(ctx context.Context, arg ListCommerceProductVariantMappingsParams) ([]CommerceProductVariantMapping, error) {
	rows, err := q.db.Query(ctx, listCommerceProductVariantMappings, arg.ProviderKey, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommerceProductVariantMapping{}
	for rows.Next() {
		var i CommerceProductVariantMapping
		if err := rows.Scan(
			&i.ProviderKey,
			&i.ProductID,
			&i.VariantID,
			&i.ExternalProductID,
			&i.ExternalVariantID,
			&i.StoreID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommerceProductMappingExternal = `-- name: UpdateCommerceProductMappingExternal :one
UPDATE commerce_product_mappings
SET external_product_id = $4, updated_at = now()
WHERE provider_key = $1 AND product_id = $2 AND external_product_id = $3
RETURNING provider_key, product_id, external_product_id, store_id, created_at, updated_at
`

type UpdateCommerceProductMappingExternalParams struct {
	ProviderKey         string      `json:"provider_key"`
	ProductID           pgtype.UUID `json:"product_id"`
	ExternalProductID   string      `json:"external_product_id"`
	ExternalProductID_2 string      `json:"external_product_id_2"`
}

type UpdateCommerceProductMappingExternalRow struct {
	ProviderKey       string             `json:"provider_key"`
	ProductID         pgtype.UUID        `json:"product_id"`
	ExternalProductID string             `json:"external_product_id"`
	StoreID           pgtype.UUID        `json:"store_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Phase 15-R1 F07 (§116): compare-and-set sellable-identity transition.
// Only the currently recorded external identity may be replaced; a
// concurrent different mapping is never clobbered.
func (q *Queries) UpdateCommerceProductMappingExternal(ctx context.Context, arg UpdateCommerceProductMappingExternalParams) (UpdateCommerceProductMappingExternalRow, error) {
	row := q.db.QueryRow(ctx, updateCommerceProductMappingExternal,
		arg.ProviderKey,
		arg.ProductID,
		arg.ExternalProductID,
		arg.ExternalProductID_2,
	)
	var i UpdateCommerceProductMappingExternalRow
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.ExternalProductID,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCommerceProductVariantMappingExternal = `-- name: UpdateCommerceProductVariantMappingExternal :one
UPDATE commerce_product_variant_mappings m
SET external_variant_id = $1, updated_at = now()
WHERE m.provider_key = $2 AND m.product_id = $3
 AND m.variant_id = $4 AND m.external_product_id = $5
 AND m.external_variant_id = $6
 AND m.store_id IS NOT NULL
 AND EXISTS (SELECT 1 FROM catalog_products p WHERE p.product_id=m.product_id AND p.store_id=m.store_id)
RETURNING m.provider_key, m.product_id, m.variant_id, m.external_product_id, m.external_variant_id, m.store_id, m.created_at, m.updated_at
`

type UpdateCommerceProductVariantMappingExternalParams struct {
	NewExternalVariantID      string      `json:"new_external_variant_id"`
	ProviderKey               string      `json:"provider_key"`
	ProductID                 pgtype.UUID `json:"product_id"`
	VariantID                 pgtype.UUID `json:"variant_id"`
	ExternalProductID         string      `json:"external_product_id"`
	ExpectedExternalVariantID string      `json:"expected_external_variant_id"`
}

func (q *Queries) UpdateCommerceProductVariantMappingExternal(ctx context.Context, arg UpdateCommerceProductVariantMappingExternalParams) (CommerceProductVariantMapping, error) {
	row := q.db.QueryRow(ctx, updateCommerceProductVariantMappingExternal,
		arg.NewExternalVariantID,
		arg.ProviderKey,
		arg.ProductID,
		arg.VariantID,
		arg.ExternalProductID,
		arg.ExpectedExternalVariantID,
	)
	var i CommerceProductVariantMapping
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.VariantID,
		&i.ExternalProductID,
		&i.ExternalVariantID,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
