// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commerce_mapping.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommerceProductMapping = `-- name: CreateCommerceProductMapping :one
INSERT INTO commerce_product_mappings (provider_key, product_id, external_product_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING provider_key, product_id, external_product_id, created_at, updated_at
`

type CreateCommerceProductMappingParams struct {
	ProviderKey       string      `json:"provider_key"`
	ProductID         pgtype.UUID `json:"product_id"`
	ExternalProductID string      `json:"external_product_id"`
}

func (q *Queries) CreateCommerceProductMapping(ctx context.Context, arg CreateCommerceProductMappingParams) (CommerceProductMapping, error) {
	row := q.db.QueryRow(ctx, createCommerceProductMapping, arg.ProviderKey, arg.ProductID, arg.ExternalProductID)
	var i CommerceProductMapping
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.ExternalProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCommerceProductMappingByExternal = `-- name: FindCommerceProductMappingByExternal :one
SELECT provider_key, product_id, external_product_id, created_at, updated_at
FROM commerce_product_mappings
WHERE provider_key = $1 AND external_product_id = $2
`

type FindCommerceProductMappingByExternalParams struct {
	ProviderKey       string `json:"provider_key"`
	ExternalProductID string `json:"external_product_id"`
}

func (q *Queries) FindCommerceProductMappingByExternal(ctx context.Context, arg FindCommerceProductMappingByExternalParams) (CommerceProductMapping, error) {
	row := q.db.QueryRow(ctx, findCommerceProductMappingByExternal, arg.ProviderKey, arg.ExternalProductID)
	var i CommerceProductMapping
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.ExternalProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommerceProductMapping = `-- name: GetCommerceProductMapping :one

SELECT provider_key, product_id, external_product_id, created_at, updated_at
FROM commerce_product_mappings
WHERE provider_key = $1 AND product_id = $2
`

type GetCommerceProductMappingParams struct {
	ProviderKey string      `json:"provider_key"`
	ProductID   pgtype.UUID `json:"product_id"`
}

// Phase 6A durable provider product mappings. Integration state, not a
// projection: never cleared by catalog/policy/inventory rebuilds.
func (q *Queries) GetCommerceProductMapping(ctx context.Context, arg GetCommerceProductMappingParams) (CommerceProductMapping, error) {
	row := q.db.QueryRow(ctx, getCommerceProductMapping, arg.ProviderKey, arg.ProductID)
	var i CommerceProductMapping
	err := row.Scan(
		&i.ProviderKey,
		&i.ProductID,
		&i.ExternalProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
