// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commerce_reevaluation.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimProductReevaluations = `-- name: ClaimProductReevaluations :many
WITH due AS (
 SELECT product_id FROM commerce_product_reevaluations
 WHERE next_attempt_at <= now() AND (lease_until IS NULL OR lease_until <= now())
 ORDER BY next_attempt_at, product_id
 LIMIT $3::int FOR UPDATE SKIP LOCKED
)
UPDATE commerce_product_reevaluations q
SET lease_until = $1::timestamptz, lease_token = $2::uuid,
    lease_generation = lease_generation + 1, claimed_generation = requested_generation
FROM due WHERE q.product_id = due.product_id
RETURNING q.product_id, q.store_id, q.reason, q.attempts,
 q.claimed_generation, q.lease_generation, q.lease_token, q.lease_until
`

type ClaimProductReevaluationsParams struct {
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	LeaseToken pgtype.UUID        `json:"lease_token"`
	BatchSize  int32              `json:"batch_size"`
}

type ClaimProductReevaluationsRow struct {
	ProductID         pgtype.UUID        `json:"product_id"`
	StoreID           pgtype.UUID        `json:"store_id"`
	Reason            string             `json:"reason"`
	Attempts          int32              `json:"attempts"`
	ClaimedGeneration pgtype.Int8        `json:"claimed_generation"`
	LeaseGeneration   int64              `json:"lease_generation"`
	LeaseToken        pgtype.UUID        `json:"lease_token"`
	LeaseUntil        pgtype.Timestamptz `json:"lease_until"`
}

// Scheduling never changes an active lease. A fresh opaque token also fences
// deletion/reinsertion (generation counters alone could suffer an ABA race).
func (q *Queries) ClaimProductReevaluations(ctx context.Context, arg ClaimProductReevaluationsParams) ([]ClaimProductReevaluationsRow, error) {
	rows, err := q.db.Query(ctx, claimProductReevaluations, arg.LeaseUntil, arg.LeaseToken, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimProductReevaluationsRow{}
	for rows.Next() {
		var i ClaimProductReevaluationsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.StoreID,
			&i.Reason,
			&i.Attempts,
			&i.ClaimedGeneration,
			&i.LeaseGeneration,
			&i.LeaseToken,
			&i.LeaseUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeProductReevaluation = `-- name: CompleteProductReevaluation :one
WITH finished AS (
 DELETE FROM commerce_product_reevaluations
 WHERE product_id = $1::uuid AND lease_token = $2::uuid
 AND lease_generation = $3::bigint AND claimed_generation = $4::bigint
 AND lease_until > now() AND requested_generation = claimed_generation
 RETURNING product_id
), newer AS (
 UPDATE commerce_product_reevaluations SET lease_token=NULL, lease_until=NULL,
 claimed_generation=NULL, next_attempt_at=now()
 WHERE product_id = $1::uuid AND lease_token = $2::uuid
 AND lease_generation = $3::bigint AND claimed_generation = $4::bigint
 AND lease_until > now() AND requested_generation > claimed_generation
 RETURNING product_id
)
SELECT EXISTS(SELECT 1 FROM finished) OR EXISTS(SELECT 1 FROM newer) AS acknowledged
`

type CompleteProductReevaluationParams struct {
	ProductID         pgtype.UUID `json:"product_id"`
	LeaseToken        pgtype.UUID `json:"lease_token"`
	LeaseGeneration   int64       `json:"lease_generation"`
	ClaimedGeneration int64       `json:"claimed_generation"`
}

// Only this live claim can acknowledge its captured intent. Newer intent is
// released for another pass, rather than being deleted by an older send.
func (q *Queries) CompleteProductReevaluation(ctx context.Context, arg CompleteProductReevaluationParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, completeProductReevaluation,
		arg.ProductID,
		arg.LeaseToken,
		arg.LeaseGeneration,
		arg.ClaimedGeneration,
	)
	var acknowledged pgtype.Bool
	err := row.Scan(&acknowledged)
	return acknowledged, err
}

const countProductReevaluations = `-- name: CountProductReevaluations :one
SELECT count(*) FROM commerce_product_reevaluations
`

func (q *Queries) CountProductReevaluations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductReevaluations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueCategoryAffectedReevaluations = `-- name: EnqueueCategoryAffectedReevaluations :execrows
WITH RECURSIVE descendants (category_id) AS (
    SELECT $1::uuid
    UNION
    SELECT e.child_id
    FROM catalog_category_edges e
    JOIN descendants d ON e.parent_id = d.category_id
)
INSERT INTO commerce_product_reevaluations (product_id, store_id, reason, requested_at, next_attempt_at)
SELECT DISTINCT p.product_id, p.store_id, $2::text, now(), now()
FROM catalog_products p
WHERE p.store_id IS NOT DISTINCT FROM $3::uuid
  AND (
    p.top_category_id = $1::uuid
    OR EXISTS (
      SELECT 1
      FROM catalog_product_subcategories ps
      JOIN descendants reachable ON reachable.category_id = ps.category_id
      WHERE ps.product_id = p.product_id
    )
  )
ON CONFLICT (product_id) DO UPDATE SET
    requested_at = now(),
    requested_generation = commerce_product_reevaluations.requested_generation + 1,
    reason = EXCLUDED.reason,
    next_attempt_at = now(),
    attempts = 0,
    last_error_code = NULL
`

type EnqueueCategoryAffectedReevaluationsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 pgtype.UUID `json:"column_3"`
}

// Set-based descendant fan-out (§85): every Product whose classification
// reaches the Category or any DAG descendant of it. UNION deduplicates
// multi-parent paths (§86/§182); Store scope matches proven ownership
// only (legacy NULL never fans out Store-owned Products, §107).
func (q *Queries) EnqueueCategoryAffectedReevaluations(ctx context.Context, arg EnqueueCategoryAffectedReevaluationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueCategoryAffectedReevaluations, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueProductReevaluation = `-- name: EnqueueProductReevaluation :exec

INSERT INTO commerce_product_reevaluations (product_id, store_id, reason, requested_at, next_attempt_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (product_id) DO UPDATE SET
    requested_at = now(),
    requested_generation = commerce_product_reevaluations.requested_generation + 1,
    reason = EXCLUDED.reason,
    next_attempt_at = now(),
    attempts = 0,
    last_error_code = NULL
`

type EnqueueProductReevaluationParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	StoreID   pgtype.UUID `json:"store_id"`
	Reason    string      `json:"reason"`
}

// Phase 13 §83: generic durable commerce re-evaluation. Provider-neutral
// and Product-keyed: the category/product projectors enqueue affected
// Products atomically with their projection commit; a worker later runs
// the existing generic CommerceService.SyncProduct per registered
// provider. No provider I/O ever happens inside projection transactions.
//
// Dedupe/coalescing is the primary key: repeated requests for one
// Product collapse into one row (shared-DAG paths never fan out twice),
// and the worker always re-reads CURRENT desired state, so rapid
// on/off/on toggles converge to the latest committed policy.
func (q *Queries) EnqueueProductReevaluation(ctx context.Context, arg EnqueueProductReevaluationParams) error {
	_, err := q.db.Exec(ctx, enqueueProductReevaluation, arg.ProductID, arg.StoreID, arg.Reason)
	return err
}

const retryProductReevaluation = `-- name: RetryProductReevaluation :execrows
UPDATE commerce_product_reevaluations
SET attempts = CASE WHEN requested_generation > claimed_generation THEN attempts ELSE attempts+1 END,
 next_attempt_at = CASE WHEN requested_generation > claimed_generation THEN next_attempt_at ELSE $1::timestamptz END,
 last_error_code = CASE WHEN requested_generation > claimed_generation THEN last_error_code ELSE $2::text END,
 lease_token=NULL, lease_until=NULL, claimed_generation=NULL
WHERE product_id = $3::uuid AND lease_token = $4::uuid
 AND lease_generation = $5::bigint AND claimed_generation = $6::bigint
 AND lease_until > now()
`

type RetryProductReevaluationParams struct {
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	LastErrorCode     string             `json:"last_error_code"`
	ProductID         pgtype.UUID        `json:"product_id"`
	LeaseToken        pgtype.UUID        `json:"lease_token"`
	LeaseGeneration   int64              `json:"lease_generation"`
	ClaimedGeneration int64              `json:"claimed_generation"`
}

func (q *Queries) RetryProductReevaluation(ctx context.Context, arg RetryProductReevaluationParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryProductReevaluation,
		arg.NextAttemptAt,
		arg.LastErrorCode,
		arg.ProductID,
		arg.LeaseToken,
		arg.LeaseGeneration,
		arg.ClaimedGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
