// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (id, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateDeviceParams struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.Exec(ctx, createDevice,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deviceByID = `-- name: DeviceByID :one
SELECT id, name, status, created_at, updated_at, last_seen_at, revoked_at
FROM devices WHERE id = $1
`

func (q *Queries) DeviceByID(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, deviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, status, created_at, updated_at, last_seen_at, revoked_at
FROM devices ORDER BY created_at
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDeviceRow = `-- name: RevokeDeviceRow :exec
UPDATE devices SET status = 'revoked', revoked_at = $2, updated_at = $2 WHERE id = $1
`

type RevokeDeviceRowParams struct {
	ID        pgtype.UUID        `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeDeviceRow(ctx context.Context, arg RevokeDeviceRowParams) error {
	_, err := q.db.Exec(ctx, revokeDeviceRow, arg.ID, arg.RevokedAt)
	return err
}

const touchDeviceLastSeen = `-- name: TouchDeviceLastSeen :exec
UPDATE devices SET last_seen_at = $2, updated_at = $2 WHERE id = $1
`

type TouchDeviceLastSeenParams struct {
	ID         pgtype.UUID        `json:"id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) TouchDeviceLastSeen(ctx context.Context, arg TouchDeviceLastSeenParams) error {
	_, err := q.db.Exec(ctx, touchDeviceLastSeen, arg.ID, arg.LastSeenAt)
	return err
}
