// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_control.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptControlCommand = `-- name: AcceptControlCommand :one
UPDATE device_control_commands
SET status = 'accepted', accepted_at = COALESCE(accepted_at, $3), updated_at = $3
WHERE id = $1 AND device_id = $2
  AND status IN ('pending','leased','accepted')
RETURNING id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
`

type AcceptControlCommandParams struct {
	ID        pgtype.UUID        `json:"id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AcceptControlCommand(ctx context.Context, arg AcceptControlCommandParams) (DeviceControlCommand, error) {
	row := q.db.QueryRow(ctx, acceptControlCommand, arg.ID, arg.DeviceID, arg.UpdatedAt)
	var i DeviceControlCommand
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CommandType,
		&i.CommandVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.RequestedAt,
		&i.LeasedAt,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.AcceptedAt,
		&i.RunningAt,
		&i.FinishedAt,
		&i.ResultCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimControlCommand = `-- name: ClaimControlCommand :one
SELECT id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
FROM device_control_commands
WHERE device_id = $1
  AND (status = 'pending' OR (status = 'leased' AND lease_until <= $2))
ORDER BY requested_at, id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type ClaimControlCommandParams struct {
	DeviceID   pgtype.UUID        `json:"device_id"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
}

func (q *Queries) ClaimControlCommand(ctx context.Context, arg ClaimControlCommandParams) (DeviceControlCommand, error) {
	row := q.db.QueryRow(ctx, claimControlCommand, arg.DeviceID, arg.LeaseUntil)
	var i DeviceControlCommand
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CommandType,
		&i.CommandVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.RequestedAt,
		&i.LeasedAt,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.AcceptedAt,
		&i.RunningAt,
		&i.FinishedAt,
		&i.ResultCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createControlCommand = `-- name: CreateControlCommand :one
INSERT INTO device_control_commands (id, device_id, command_type, command_version, idempotency_key, status, requested_at, created_at, updated_at)
VALUES ($1, $2, 'sync_now', 1, $3, 'pending', $4, $4, $4)
RETURNING id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
`

type CreateControlCommandParams struct {
	ID             pgtype.UUID        `json:"id"`
	DeviceID       pgtype.UUID        `json:"device_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestedAt    pgtype.Timestamptz `json:"requested_at"`
}

func (q *Queries) CreateControlCommand(ctx context.Context, arg CreateControlCommandParams) (DeviceControlCommand, error) {
	row := q.db.QueryRow(ctx, createControlCommand,
		arg.ID,
		arg.DeviceID,
		arg.IdempotencyKey,
		arg.RequestedAt,
	)
	var i DeviceControlCommand
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CommandType,
		&i.CommandVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.RequestedAt,
		&i.LeasedAt,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.AcceptedAt,
		&i.RunningAt,
		&i.FinishedAt,
		&i.ResultCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishControlCommand = `-- name: FinishControlCommand :one
UPDATE device_control_commands
SET status = $3, finished_at = $4, result_code = $5, updated_at = $4
WHERE id = $1 AND device_id = $2
  AND status IN ('pending','leased','accepted','running')
RETURNING id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
`

type FinishControlCommandParams struct {
	ID         pgtype.UUID        `json:"id"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	Status     string             `json:"status"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ResultCode pgtype.Text        `json:"result_code"`
}

func (q *Queries) FinishControlCommand(ctx context.Context, arg FinishControlCommandParams) (DeviceControlCommand, error) {
	row := q.db.QueryRow(ctx, finishControlCommand,
		arg.ID,
		arg.DeviceID,
		arg.Status,
		arg.FinishedAt,
		arg.ResultCode,
	)
	var i DeviceControlCommand
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CommandType,
		&i.CommandVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.RequestedAt,
		&i.LeasedAt,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.AcceptedAt,
		&i.RunningAt,
		&i.FinishedAt,
		&i.ResultCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveControlCommand = `-- name: GetActiveControlCommand :one
SELECT id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
FROM device_control_commands
WHERE device_id = $1 AND status IN ('pending','leased','accepted','running')
ORDER BY requested_at, id
LIMIT 1
`

func (q *Queries) GetActiveControlCommand(ctx context.Context, deviceID pgtype.UUID) (DeviceControlCommand, error) {
	row := q.db.QueryRow(ctx, getActiveControlCommand, deviceID)
	var i DeviceControlCommand
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CommandType,
		&i.CommandVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.RequestedAt,
		&i.LeasedAt,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.AcceptedAt,
		&i.RunningAt,
		&i.FinishedAt,
		&i.ResultCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommandByIdempotency = `-- name: GetCommandByIdempotency :one
SELECT id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
FROM device_control_commands
WHERE device_id = $1 AND idempotency_key = $2
`

type GetCommandByIdempotencyParams struct {
	DeviceID       pgtype.UUID `json:"device_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetCommandByIdempotency(ctx context.Context, arg GetCommandByIdempotencyParams) (DeviceControlCommand, error) {
	row := q.db.QueryRow(ctx, getCommandByIdempotency, arg.DeviceID, arg.IdempotencyKey)
	var i DeviceControlCommand
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CommandType,
		&i.CommandVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.RequestedAt,
		&i.LeasedAt,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.AcceptedAt,
		&i.RunningAt,
		&i.FinishedAt,
		&i.ResultCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getControlCommand = `-- name: GetControlCommand :one
SELECT id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
FROM device_control_commands
WHERE id = $1
`

func (q *Queries) GetControlCommand(ctx context.Context, id pgtype.UUID) (DeviceControlCommand, error) {
	row := q.db.QueryRow(ctx, getControlCommand, id)
	var i DeviceControlCommand
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CommandType,
		&i.CommandVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.RequestedAt,
		&i.LeasedAt,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.AcceptedAt,
		&i.RunningAt,
		&i.FinishedAt,
		&i.ResultCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getControlCommandForDevice = `-- name: GetControlCommandForDevice :one
SELECT id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
FROM device_control_commands
WHERE id = $1 AND device_id = $2
`

type GetControlCommandForDeviceParams struct {
	ID       pgtype.UUID `json:"id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) GetControlCommandForDevice(ctx context.Context, arg GetControlCommandForDeviceParams) (DeviceControlCommand, error) {
	row := q.db.QueryRow(ctx, getControlCommandForDevice, arg.ID, arg.DeviceID)
	var i DeviceControlCommand
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CommandType,
		&i.CommandVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.RequestedAt,
		&i.LeasedAt,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.AcceptedAt,
		&i.RunningAt,
		&i.FinishedAt,
		&i.ResultCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPresence = `-- name: GetPresence :one
SELECT device_id, last_seen_at, last_poll_at, last_command_accepted_at,
    last_command_finished_at, created_at, updated_at
FROM device_control_presence
WHERE device_id = $1
`

func (q *Queries) GetPresence(ctx context.Context, deviceID pgtype.UUID) (DeviceControlPresence, error) {
	row := q.db.QueryRow(ctx, getPresence, deviceID)
	var i DeviceControlPresence
	err := row.Scan(
		&i.DeviceID,
		&i.LastSeenAt,
		&i.LastPollAt,
		&i.LastCommandAcceptedAt,
		&i.LastCommandFinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leaseControlCommand = `-- name: LeaseControlCommand :one
UPDATE device_control_commands
SET status = 'leased', leased_at = $3, lease_until = $4,
    lease_generation = lease_generation + 1, updated_at = $3
WHERE id = $1 AND device_id = $2
  AND (status = 'pending' OR (status = 'leased' AND lease_until <= $3))
RETURNING id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
`

type LeaseControlCommandParams struct {
	ID         pgtype.UUID        `json:"id"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	LeasedAt   pgtype.Timestamptz `json:"leased_at"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
}

func (q *Queries) LeaseControlCommand(ctx context.Context, arg LeaseControlCommandParams) (DeviceControlCommand, error) {
	row := q.db.QueryRow(ctx, leaseControlCommand,
		arg.ID,
		arg.DeviceID,
		arg.LeasedAt,
		arg.LeaseUntil,
	)
	var i DeviceControlCommand
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CommandType,
		&i.CommandVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.RequestedAt,
		&i.LeasedAt,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.AcceptedAt,
		&i.RunningAt,
		&i.FinishedAt,
		&i.ResultCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPresence = `-- name: ListPresence :many
SELECT device_id, last_seen_at, last_poll_at, last_command_accepted_at,
    last_command_finished_at, created_at, updated_at
FROM device_control_presence
ORDER BY device_id
`

func (q *Queries) ListPresence(ctx context.Context) ([]DeviceControlPresence, error) {
	rows, err := q.db.Query(ctx, listPresence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceControlPresence{}
	for rows.Next() {
		var i DeviceControlPresence
		if err := rows.Scan(
			&i.DeviceID,
			&i.LastSeenAt,
			&i.LastPollAt,
			&i.LastCommandAcceptedAt,
			&i.LastCommandFinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentControlCommands = `-- name: ListRecentControlCommands :many
SELECT id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
FROM device_control_commands
WHERE device_id = $1
ORDER BY requested_at DESC, id DESC
LIMIT $2
`

type ListRecentControlCommandsParams struct {
	DeviceID pgtype.UUID `json:"device_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListRecentControlCommands(ctx context.Context, arg ListRecentControlCommandsParams) ([]DeviceControlCommand, error) {
	rows, err := q.db.Query(ctx, listRecentControlCommands, arg.DeviceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceControlCommand{}
	for rows.Next() {
		var i DeviceControlCommand
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.CommandType,
			&i.CommandVersion,
			&i.IdempotencyKey,
			&i.Status,
			&i.RequestedAt,
			&i.LeasedAt,
			&i.LeaseUntil,
			&i.LeaseGeneration,
			&i.AcceptedAt,
			&i.RunningAt,
			&i.FinishedAt,
			&i.ResultCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markControlRunning = `-- name: MarkControlRunning :one
UPDATE device_control_commands
SET status = 'running', running_at = COALESCE(running_at, $3), updated_at = $3
WHERE id = $1 AND device_id = $2
  AND status IN ('pending','leased','accepted','running')
RETURNING id, device_id, command_type, command_version, idempotency_key, status,
    requested_at, leased_at, lease_until, lease_generation,
    accepted_at, running_at, finished_at, result_code, created_at, updated_at
`

type MarkControlRunningParams struct {
	ID        pgtype.UUID        `json:"id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkControlRunning(ctx context.Context, arg MarkControlRunningParams) (DeviceControlCommand, error) {
	row := q.db.QueryRow(ctx, markControlRunning, arg.ID, arg.DeviceID, arg.UpdatedAt)
	var i DeviceControlCommand
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CommandType,
		&i.CommandVersion,
		&i.IdempotencyKey,
		&i.Status,
		&i.RequestedAt,
		&i.LeasedAt,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.AcceptedAt,
		&i.RunningAt,
		&i.FinishedAt,
		&i.ResultCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchPresenceAccepted = `-- name: TouchPresenceAccepted :exec
UPDATE device_control_presence
SET last_seen_at = GREATEST(last_seen_at, $2),
    last_command_accepted_at = $2,
    updated_at = $2
WHERE device_id = $1
`

type TouchPresenceAcceptedParams struct {
	DeviceID              pgtype.UUID        `json:"device_id"`
	LastCommandAcceptedAt pgtype.Timestamptz `json:"last_command_accepted_at"`
}

func (q *Queries) TouchPresenceAccepted(ctx context.Context, arg TouchPresenceAcceptedParams) error {
	_, err := q.db.Exec(ctx, touchPresenceAccepted, arg.DeviceID, arg.LastCommandAcceptedAt)
	return err
}

const touchPresenceFinished = `-- name: TouchPresenceFinished :exec
UPDATE device_control_presence
SET last_seen_at = GREATEST(last_seen_at, $2),
    last_command_finished_at = $2,
    updated_at = $2
WHERE device_id = $1
`

type TouchPresenceFinishedParams struct {
	DeviceID              pgtype.UUID        `json:"device_id"`
	LastCommandFinishedAt pgtype.Timestamptz `json:"last_command_finished_at"`
}

func (q *Queries) TouchPresenceFinished(ctx context.Context, arg TouchPresenceFinishedParams) error {
	_, err := q.db.Exec(ctx, touchPresenceFinished, arg.DeviceID, arg.LastCommandFinishedAt)
	return err
}

const upsertPresenceSeen = `-- name: UpsertPresenceSeen :exec

INSERT INTO device_control_presence (device_id, last_seen_at, last_poll_at, created_at, updated_at)
VALUES ($1, $2, $3, $2, $2)
ON CONFLICT (device_id) DO UPDATE SET
    last_seen_at = GREATEST(device_control_presence.last_seen_at, EXCLUDED.last_seen_at),
    last_poll_at = EXCLUDED.last_poll_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertPresenceSeenParams struct {
	DeviceID   pgtype.UUID        `json:"device_id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	LastPollAt pgtype.Timestamptz `json:"last_poll_at"`
}

// Phase 7C device control plane: presence + durable sync_now commands.
func (q *Queries) UpsertPresenceSeen(ctx context.Context, arg UpsertPresenceSeenParams) error {
	_, err := q.db.Exec(ctx, upsertPresenceSeen, arg.DeviceID, arg.LastSeenAt, arg.LastPollAt)
	return err
}
