// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fleet_updates.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOpenTargets = `-- name: CancelOpenTargets :execrows
UPDATE update_rollout_targets SET state = 'CANCELLED', finished_at = $1::timestamptz, updated_at = $1::timestamptz
WHERE rollout_id = $2::uuid
  AND state IN ('NOT_SELECTED','PENDING','DELIVERED','DOWNLOADING','VERIFIED','WAITING_SAFE_BOUNDARY')
`

type CancelOpenTargetsParams struct {
	Now       pgtype.Timestamptz `json:"now"`
	RolloutID pgtype.UUID        `json:"rollout_id"`
}

// Cancellation cannot reach targets already in irreversible execution.
func (q *Queries) CancelOpenTargets(ctx context.Context, arg CancelOpenTargetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOpenTargets, arg.Now, arg.RolloutID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDeviceUpdateTarget = `-- name: ClaimDeviceUpdateTarget :one
SELECT t.id AS target_id, t.rollout_id, t.state, r.mode, rel.id AS release_id, rel.manifest_digest, rel.envelope,
    rel.status AS release_status, rel.release_sequence, a.url AS artifact_url
FROM update_rollout_targets t
JOIN update_rollouts r ON r.id = t.rollout_id
JOIN releases rel ON rel.id = r.release_id
JOIN device_store_bindings b ON b.device_id = t.device_id AND b.store_id = t.store_id
JOIN release_artifacts a ON a.release_id = rel.id AND a.os = $1::text AND a.arch = $2::text AND a.package = $3::text
WHERE t.device_id = $4::uuid
  AND t.state IN ('PENDING','DELIVERED')
  AND r.status = 'ACTIVE' AND rel.status = 'ACTIVE'
  AND (t.next_attempt_at IS NULL OR t.next_attempt_at <= $5::timestamptz)
  AND (r.not_before IS NULL OR r.not_before <= $5::timestamptz)
ORDER BY rel.release_sequence DESC, t.created_at, t.id
LIMIT 1
FOR UPDATE OF t FOR SHARE OF r
`

type ClaimDeviceUpdateTargetParams struct {
	Os       string             `json:"os"`
	Arch     string             `json:"arch"`
	Package  string             `json:"package"`
	DeviceID pgtype.UUID        `json:"device_id"`
	Now      pgtype.Timestamptz `json:"now"`
}

type ClaimDeviceUpdateTargetRow struct {
	TargetID        pgtype.UUID `json:"target_id"`
	RolloutID       pgtype.UUID `json:"rollout_id"`
	State           string      `json:"state"`
	Mode            string      `json:"mode"`
	ReleaseID       pgtype.UUID `json:"release_id"`
	ManifestDigest  string      `json:"manifest_digest"`
	Envelope        string      `json:"envelope"`
	ReleaseStatus   string      `json:"release_status"`
	ReleaseSequence int64       `json:"release_sequence"`
	ArtifactUrl     string      `json:"artifact_url"`
}

// At most one deliverable target for an authenticated device: the
// device's CURRENT binding must equal the target's snapshot Store, the
// rollout must be ACTIVE (shared-locked so a concurrent pause serializes
// with delivery), the release ACTIVE, an artifact must exist for the
// device's reported platform, and the application-clock retry/not-before
// gates must have passed.
func (q *Queries) ClaimDeviceUpdateTarget(ctx context.Context, arg ClaimDeviceUpdateTargetParams) (ClaimDeviceUpdateTargetRow, error) {
	row := q.db.QueryRow(ctx, claimDeviceUpdateTarget,
		arg.Os,
		arg.Arch,
		arg.Package,
		arg.DeviceID,
		arg.Now,
	)
	var i ClaimDeviceUpdateTargetRow
	err := row.Scan(
		&i.TargetID,
		&i.RolloutID,
		&i.State,
		&i.Mode,
		&i.ReleaseID,
		&i.ManifestDigest,
		&i.Envelope,
		&i.ReleaseStatus,
		&i.ReleaseSequence,
		&i.ArtifactUrl,
	)
	return i, err
}

const countRolloutTargetStates = `-- name: CountRolloutTargetStates :many
SELECT state, count(*)::bigint AS n FROM update_rollout_targets
WHERE rollout_id = $1::uuid GROUP BY state ORDER BY state
`

type CountRolloutTargetStatesRow struct {
	State string `json:"state"`
	N     int64  `json:"n"`
}

func (q *Queries) CountRolloutTargetStates(ctx context.Context, rolloutID pgtype.UUID) ([]CountRolloutTargetStatesRow, error) {
	rows, err := q.db.Query(ctx, countRolloutTargetStates, rolloutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRolloutTargetStatesRow{}
	for rows.Next() {
		var i CountRolloutTargetStatesRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eligibleRolloutDevices = `-- name: EligibleRolloutDevices :many
SELECT d.id AS device_id, b.store_id
FROM devices d JOIN device_store_bindings b ON b.device_id = d.id
WHERE d.status = 'active'
  AND ($1::uuid IS NULL OR b.store_id = $1::uuid)
  AND ($2::uuid IS NULL OR d.id = $2::uuid)
ORDER BY d.id
LIMIT $3::int
`

type EligibleRolloutDevicesParams struct {
	StoreID  pgtype.UUID `json:"store_id"`
	DeviceID pgtype.UUID `json:"device_id"`
	RowLimit int32       `json:"row_limit"`
}

type EligibleRolloutDevicesRow struct {
	DeviceID pgtype.UUID `json:"device_id"`
	StoreID  pgtype.UUID `json:"store_id"`
}

// The immutable target snapshot: active, Store-bound devices in scope.
func (q *Queries) EligibleRolloutDevices(ctx context.Context, arg EligibleRolloutDevicesParams) ([]EligibleRolloutDevicesRow, error) {
	rows, err := q.db.Query(ctx, eligibleRolloutDevices, arg.StoreID, arg.DeviceID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EligibleRolloutDevicesRow{}
	for rows.Next() {
		var i EligibleRolloutDevicesRow
		if err := rows.Scan(&i.DeviceID, &i.StoreID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceUpdateStatus = `-- name: GetDeviceUpdateStatus :one
SELECT device_id, version, build_commit, release_sequence, os, arch, updater_protocol, updater_capable,
    unsupported_reason, update_state, update_error, reported_at
FROM device_update_status WHERE device_id = $1::uuid
`

func (q *Queries) GetDeviceUpdateStatus(ctx context.Context, deviceID pgtype.UUID) (DeviceUpdateStatus, error) {
	row := q.db.QueryRow(ctx, getDeviceUpdateStatus, deviceID)
	var i DeviceUpdateStatus
	err := row.Scan(
		&i.DeviceID,
		&i.Version,
		&i.BuildCommit,
		&i.ReleaseSequence,
		&i.Os,
		&i.Arch,
		&i.UpdaterProtocol,
		&i.UpdaterCapable,
		&i.UnsupportedReason,
		&i.UpdateState,
		&i.UpdateError,
		&i.ReportedAt,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, manifest_digest, release_sequence, version, build_commit, min_installed_sequence, key_id, envelope,
    status, imported_by, imported_at, status_changed_by, status_changed_at
FROM releases WHERE id = $1::uuid
`

func (q *Queries) GetRelease(ctx context.Context, id pgtype.UUID) (Release, error) {
	row := q.db.QueryRow(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ManifestDigest,
		&i.ReleaseSequence,
		&i.Version,
		&i.BuildCommit,
		&i.MinInstalledSequence,
		&i.KeyID,
		&i.Envelope,
		&i.Status,
		&i.ImportedBy,
		&i.ImportedAt,
		&i.StatusChangedBy,
		&i.StatusChangedAt,
	)
	return i, err
}

const getReleaseByDigest = `-- name: GetReleaseByDigest :one
SELECT id, manifest_digest, release_sequence, version, build_commit, min_installed_sequence, key_id, envelope,
    status, imported_by, imported_at, status_changed_by, status_changed_at
FROM releases WHERE manifest_digest = $1::text
`

func (q *Queries) GetReleaseByDigest(ctx context.Context, manifestDigest string) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseByDigest, manifestDigest)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ManifestDigest,
		&i.ReleaseSequence,
		&i.Version,
		&i.BuildCommit,
		&i.MinInstalledSequence,
		&i.KeyID,
		&i.Envelope,
		&i.Status,
		&i.ImportedBy,
		&i.ImportedAt,
		&i.StatusChangedBy,
		&i.StatusChangedAt,
	)
	return i, err
}

const getReleaseBySequence = `-- name: GetReleaseBySequence :one
SELECT id, manifest_digest, release_sequence, version, build_commit, min_installed_sequence, key_id, envelope,
    status, imported_by, imported_at, status_changed_by, status_changed_at
FROM releases WHERE release_sequence = $1::bigint
`

func (q *Queries) GetReleaseBySequence(ctx context.Context, releaseSequence int64) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseBySequence, releaseSequence)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ManifestDigest,
		&i.ReleaseSequence,
		&i.Version,
		&i.BuildCommit,
		&i.MinInstalledSequence,
		&i.KeyID,
		&i.Envelope,
		&i.Status,
		&i.ImportedBy,
		&i.ImportedAt,
		&i.StatusChangedBy,
		&i.StatusChangedAt,
	)
	return i, err
}

const getRollout = `-- name: GetRollout :one
SELECT id, release_id, scope, store_id, device_id, mode, percentage, status, not_before, target_count,
    created_by, created_at, updated_at
FROM update_rollouts WHERE id = $1::uuid
`

func (q *Queries) GetRollout(ctx context.Context, id pgtype.UUID) (UpdateRollout, error) {
	row := q.db.QueryRow(ctx, getRollout, id)
	var i UpdateRollout
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Scope,
		&i.StoreID,
		&i.DeviceID,
		&i.Mode,
		&i.Percentage,
		&i.Status,
		&i.NotBefore,
		&i.TargetCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRelease = `-- name: InsertRelease :exec

INSERT INTO releases (id, manifest_digest, release_sequence, version, build_commit, min_installed_sequence,
    key_id, envelope, status, imported_by, imported_at, status_changed_by, status_changed_at)
VALUES ($1::uuid, $2::text, $3::bigint, $4::text, $5::text,
    $6::bigint, $7::text, $8::text, 'ACTIVE', $9::text, $10::timestamptz,
    $9::text, $10::timestamptz)
`

type InsertReleaseParams struct {
	ID                   pgtype.UUID        `json:"id"`
	ManifestDigest       string             `json:"manifest_digest"`
	ReleaseSequence      int64              `json:"release_sequence"`
	Version              string             `json:"version"`
	BuildCommit          string             `json:"build_commit"`
	MinInstalledSequence int64              `json:"min_installed_sequence"`
	KeyID                string             `json:"key_id"`
	Envelope             string             `json:"envelope"`
	Actor                string             `json:"actor"`
	Now                  pgtype.Timestamptz `json:"now"`
}

// Phase 18 release registry and fleet rollout persistence (ADR-0051/0052).
// Every scheduling timestamp is an explicit application-clock parameter
// (@now); no state decision compares against database now().
func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) error {
	_, err := q.db.Exec(ctx, insertRelease,
		arg.ID,
		arg.ManifestDigest,
		arg.ReleaseSequence,
		arg.Version,
		arg.BuildCommit,
		arg.MinInstalledSequence,
		arg.KeyID,
		arg.Envelope,
		arg.Actor,
		arg.Now,
	)
	return err
}

const insertReleaseArtifact = `-- name: InsertReleaseArtifact :exec
INSERT INTO release_artifacts (release_id, os, arch, package, file_name, size, sha256, url)
VALUES ($1::uuid, $2::text, $3::text, $4::text, $5::text, $6::bigint, $7::text, $8::text)
`

type InsertReleaseArtifactParams struct {
	ReleaseID pgtype.UUID `json:"release_id"`
	Os        string      `json:"os"`
	Arch      string      `json:"arch"`
	Package   string      `json:"package"`
	FileName  string      `json:"file_name"`
	Size      int64       `json:"size"`
	Sha256    string      `json:"sha256"`
	Url       string      `json:"url"`
}

func (q *Queries) InsertReleaseArtifact(ctx context.Context, arg InsertReleaseArtifactParams) error {
	_, err := q.db.Exec(ctx, insertReleaseArtifact,
		arg.ReleaseID,
		arg.Os,
		arg.Arch,
		arg.Package,
		arg.FileName,
		arg.Size,
		arg.Sha256,
		arg.Url,
	)
	return err
}

const insertRollout = `-- name: InsertRollout :exec
INSERT INTO update_rollouts (id, release_id, scope, store_id, device_id, mode, percentage, status, not_before,
    target_count, created_by, created_at, updated_at)
VALUES ($1::uuid, $2::uuid, $3::text, $4::uuid, $5::uuid, $6::text,
    $7::int, 'DRAFT', $8::timestamptz, $9::int, $10::text, $11::timestamptz, $11::timestamptz)
`

type InsertRolloutParams struct {
	ID          pgtype.UUID        `json:"id"`
	ReleaseID   pgtype.UUID        `json:"release_id"`
	Scope       string             `json:"scope"`
	StoreID     pgtype.UUID        `json:"store_id"`
	DeviceID    pgtype.UUID        `json:"device_id"`
	Mode        string             `json:"mode"`
	Percentage  int32              `json:"percentage"`
	NotBefore   pgtype.Timestamptz `json:"not_before"`
	TargetCount int32              `json:"target_count"`
	Actor       string             `json:"actor"`
	Now         pgtype.Timestamptz `json:"now"`
}

func (q *Queries) InsertRollout(ctx context.Context, arg InsertRolloutParams) error {
	_, err := q.db.Exec(ctx, insertRollout,
		arg.ID,
		arg.ReleaseID,
		arg.Scope,
		arg.StoreID,
		arg.DeviceID,
		arg.Mode,
		arg.Percentage,
		arg.NotBefore,
		arg.TargetCount,
		arg.Actor,
		arg.Now,
	)
	return err
}

const insertRolloutTarget = `-- name: InsertRolloutTarget :exec
INSERT INTO update_rollout_targets (id, rollout_id, device_id, store_id, bucket, state, created_at, updated_at)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5::int, $6::text,
    $7::timestamptz, $7::timestamptz)
`

type InsertRolloutTargetParams struct {
	ID        pgtype.UUID        `json:"id"`
	RolloutID pgtype.UUID        `json:"rollout_id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	Bucket    int32              `json:"bucket"`
	State     string             `json:"state"`
	Now       pgtype.Timestamptz `json:"now"`
}

func (q *Queries) InsertRolloutTarget(ctx context.Context, arg InsertRolloutTargetParams) error {
	_, err := q.db.Exec(ctx, insertRolloutTarget,
		arg.ID,
		arg.RolloutID,
		arg.DeviceID,
		arg.StoreID,
		arg.Bucket,
		arg.State,
		arg.Now,
	)
	return err
}

const insertTargetEvent = `-- name: InsertTargetEvent :exec
INSERT INTO update_target_events (target_id, device_id, reported_state, target_state, error_code, retryable, recorded_at)
VALUES ($1::uuid, $2::uuid, $3::text, $4::text, $5::text,
    $6::bool, $7::timestamptz)
`

type InsertTargetEventParams struct {
	TargetID      pgtype.UUID        `json:"target_id"`
	DeviceID      pgtype.UUID        `json:"device_id"`
	ReportedState string             `json:"reported_state"`
	TargetState   string             `json:"target_state"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	Retryable     bool               `json:"retryable"`
	Now           pgtype.Timestamptz `json:"now"`
}

func (q *Queries) InsertTargetEvent(ctx context.Context, arg InsertTargetEventParams) error {
	_, err := q.db.Exec(ctx, insertTargetEvent,
		arg.TargetID,
		arg.DeviceID,
		arg.ReportedState,
		arg.TargetState,
		arg.ErrorCode,
		arg.Retryable,
		arg.Now,
	)
	return err
}

const insertUpdateAudit = `-- name: InsertUpdateAudit :exec
INSERT INTO update_audit_events (occurred_at, actor_kind, actor, action, release_id, rollout_id, target_id, device_id, store_id, details)
VALUES ($1::timestamptz, $2::text, $3::text, $4::text, $5::uuid,
    $6::uuid, $7::uuid, $8::uuid, $9::uuid,
    $10::jsonb)
`

type InsertUpdateAuditParams struct {
	Now       pgtype.Timestamptz `json:"now"`
	ActorKind string             `json:"actor_kind"`
	Actor     string             `json:"actor"`
	Action    string             `json:"action"`
	ReleaseID pgtype.UUID        `json:"release_id"`
	RolloutID pgtype.UUID        `json:"rollout_id"`
	TargetID  pgtype.UUID        `json:"target_id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	Details   []byte             `json:"details"`
}

func (q *Queries) InsertUpdateAudit(ctx context.Context, arg InsertUpdateAuditParams) error {
	_, err := q.db.Exec(ctx, insertUpdateAudit,
		arg.Now,
		arg.ActorKind,
		arg.Actor,
		arg.Action,
		arg.ReleaseID,
		arg.RolloutID,
		arg.TargetID,
		arg.DeviceID,
		arg.StoreID,
		arg.Details,
	)
	return err
}

const listFleet = `-- name: ListFleet :many
SELECT d.id AS device_id, d.name, d.status AS device_status, d.last_seen_at, b.store_id,
    s.version, s.build_commit, s.release_sequence, s.os, s.arch, s.updater_protocol, s.updater_capable,
    s.unsupported_reason, s.update_state, s.update_error, s.reported_at,
    lt.target_id, COALESCE(lt.target_state, '')::text AS target_state, lt.target_error,
    COALESCE(lt.target_version, '')::text AS target_version, COALESCE(lt.target_sequence, 0)::bigint AS target_sequence, lt.rollout_id
FROM devices d
JOIN device_store_bindings b ON b.device_id = d.id
LEFT JOIN device_update_status s ON s.device_id = d.id
LEFT JOIN LATERAL (
    SELECT t.id AS target_id, t.state AS target_state, t.last_error AS target_error,
        rel.version AS target_version, rel.release_sequence AS target_sequence, t.rollout_id
    FROM update_rollout_targets t
    JOIN update_rollouts r ON r.id = t.rollout_id
    JOIN releases rel ON rel.id = r.release_id
    WHERE t.device_id = d.id AND t.store_id = b.store_id
    ORDER BY t.created_at DESC, t.id DESC LIMIT 1
) lt ON TRUE
WHERE ($1::uuid IS NULL OR b.store_id = $1::uuid)
  AND ($2::uuid IS NULL OR d.id > $2::uuid)
ORDER BY d.id
LIMIT $3::int
`

type ListFleetParams struct {
	StoreID     pgtype.UUID `json:"store_id"`
	AfterDevice pgtype.UUID `json:"after_device"`
	RowLimit    int32       `json:"row_limit"`
}

type ListFleetRow struct {
	DeviceID          pgtype.UUID        `json:"device_id"`
	Name              string             `json:"name"`
	DeviceStatus      string             `json:"device_status"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	StoreID           pgtype.UUID        `json:"store_id"`
	Version           pgtype.Text        `json:"version"`
	BuildCommit       pgtype.Text        `json:"build_commit"`
	ReleaseSequence   pgtype.Int8        `json:"release_sequence"`
	Os                pgtype.Text        `json:"os"`
	Arch              pgtype.Text        `json:"arch"`
	UpdaterProtocol   pgtype.Int4        `json:"updater_protocol"`
	UpdaterCapable    pgtype.Bool        `json:"updater_capable"`
	UnsupportedReason pgtype.Text        `json:"unsupported_reason"`
	UpdateState       pgtype.Text        `json:"update_state"`
	UpdateError       pgtype.Text        `json:"update_error"`
	ReportedAt        pgtype.Timestamptz `json:"reported_at"`
	TargetID          pgtype.UUID        `json:"target_id"`
	TargetState       string             `json:"target_state"`
	TargetError       pgtype.Text        `json:"target_error"`
	TargetVersion     string             `json:"target_version"`
	TargetSequence    int64              `json:"target_sequence"`
	RolloutID         pgtype.UUID        `json:"rollout_id"`
}

// Bounded keyset page of Store-bound devices with their trusted version
// report and most recent update target (one LATERAL per row, no N+1).
func (q *Queries) ListFleet(ctx context.Context, arg ListFleetParams) ([]ListFleetRow, error) {
	rows, err := q.db.Query(ctx, listFleet, arg.StoreID, arg.AfterDevice, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFleetRow{}
	for rows.Next() {
		var i ListFleetRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Name,
			&i.DeviceStatus,
			&i.LastSeenAt,
			&i.StoreID,
			&i.Version,
			&i.BuildCommit,
			&i.ReleaseSequence,
			&i.Os,
			&i.Arch,
			&i.UpdaterProtocol,
			&i.UpdaterCapable,
			&i.UnsupportedReason,
			&i.UpdateState,
			&i.UpdateError,
			&i.ReportedAt,
			&i.TargetID,
			&i.TargetState,
			&i.TargetError,
			&i.TargetVersion,
			&i.TargetSequence,
			&i.RolloutID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseArtifacts = `-- name: ListReleaseArtifacts :many
SELECT release_id, os, arch, package, file_name, size, sha256, url
FROM release_artifacts WHERE release_id = $1::uuid
ORDER BY os, arch, package
`

func (q *Queries) ListReleaseArtifacts(ctx context.Context, releaseID pgtype.UUID) ([]ReleaseArtifact, error) {
	rows, err := q.db.Query(ctx, listReleaseArtifacts, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseArtifact{}
	for rows.Next() {
		var i ReleaseArtifact
		if err := rows.Scan(
			&i.ReleaseID,
			&i.Os,
			&i.Arch,
			&i.Package,
			&i.FileName,
			&i.Size,
			&i.Sha256,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT id, manifest_digest, release_sequence, version, build_commit, min_installed_sequence, key_id,
    status, imported_by, imported_at, status_changed_by, status_changed_at
FROM releases
WHERE ($1::bigint = 0 OR release_sequence < $1::bigint)
ORDER BY release_sequence DESC
LIMIT $2::int
`

type ListReleasesParams struct {
	BeforeSequence int64 `json:"before_sequence"`
	RowLimit       int32 `json:"row_limit"`
}

type ListReleasesRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ManifestDigest       string             `json:"manifest_digest"`
	ReleaseSequence      int64              `json:"release_sequence"`
	Version              string             `json:"version"`
	BuildCommit          string             `json:"build_commit"`
	MinInstalledSequence int64              `json:"min_installed_sequence"`
	KeyID                string             `json:"key_id"`
	Status               string             `json:"status"`
	ImportedBy           string             `json:"imported_by"`
	ImportedAt           pgtype.Timestamptz `json:"imported_at"`
	StatusChangedBy      string             `json:"status_changed_by"`
	StatusChangedAt      pgtype.Timestamptz `json:"status_changed_at"`
}

func (q *Queries) ListReleases(ctx context.Context, arg ListReleasesParams) ([]ListReleasesRow, error) {
	rows, err := q.db.Query(ctx, listReleases, arg.BeforeSequence, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleasesRow{}
	for rows.Next() {
		var i ListReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ManifestDigest,
			&i.ReleaseSequence,
			&i.Version,
			&i.BuildCommit,
			&i.MinInstalledSequence,
			&i.KeyID,
			&i.Status,
			&i.ImportedBy,
			&i.ImportedAt,
			&i.StatusChangedBy,
			&i.StatusChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolloutTargets = `-- name: ListRolloutTargets :many
SELECT t.id, t.rollout_id, t.device_id, t.store_id, t.bucket, t.state, t.attempt_count, t.next_attempt_at,
    t.last_error, t.retryable, t.delivered_at, t.finished_at, t.created_at, t.updated_at, d.name AS device_name
FROM update_rollout_targets t JOIN devices d ON d.id = t.device_id
WHERE t.rollout_id = $1::uuid
  AND ($2::uuid IS NULL OR t.store_id = $2::uuid)
  AND ($3::uuid IS NULL OR t.device_id > $3::uuid)
ORDER BY t.device_id
LIMIT $4::int
`

type ListRolloutTargetsParams struct {
	RolloutID   pgtype.UUID `json:"rollout_id"`
	StoreID     pgtype.UUID `json:"store_id"`
	AfterDevice pgtype.UUID `json:"after_device"`
	RowLimit    int32       `json:"row_limit"`
}

type ListRolloutTargetsRow struct {
	ID            pgtype.UUID        `json:"id"`
	RolloutID     pgtype.UUID        `json:"rollout_id"`
	DeviceID      pgtype.UUID        `json:"device_id"`
	StoreID       pgtype.UUID        `json:"store_id"`
	Bucket        int32              `json:"bucket"`
	State         string             `json:"state"`
	AttemptCount  int32              `json:"attempt_count"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	Retryable     bool               `json:"retryable"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeviceName    string             `json:"device_name"`
}

func (q *Queries) ListRolloutTargets(ctx context.Context, arg ListRolloutTargetsParams) ([]ListRolloutTargetsRow, error) {
	rows, err := q.db.Query(ctx, listRolloutTargets,
		arg.RolloutID,
		arg.StoreID,
		arg.AfterDevice,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolloutTargetsRow{}
	for rows.Next() {
		var i ListRolloutTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.RolloutID,
			&i.DeviceID,
			&i.StoreID,
			&i.Bucket,
			&i.State,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastError,
			&i.Retryable,
			&i.DeliveredAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollouts = `-- name: ListRollouts :many
SELECT r.id, r.release_id, r.scope, r.store_id, r.device_id, r.mode, r.percentage, r.status, r.not_before,
    r.target_count, r.created_by, r.created_at, r.updated_at, rel.version, rel.release_sequence
FROM update_rollouts r JOIN releases rel ON rel.id = r.release_id
WHERE ($1::uuid IS NULL OR r.store_id = $1::uuid)
  AND ($2::timestamptz IS NULL
       OR (r.created_at, r.id) < ($2::timestamptz, $3::uuid))
ORDER BY r.created_at DESC, r.id DESC
LIMIT $4::int
`

type ListRolloutsParams struct {
	StoreID  pgtype.UUID        `json:"store_id"`
	CursorAt pgtype.Timestamptz `json:"cursor_at"`
	CursorID pgtype.UUID        `json:"cursor_id"`
	RowLimit int32              `json:"row_limit"`
}

type ListRolloutsRow struct {
	ID              pgtype.UUID        `json:"id"`
	ReleaseID       pgtype.UUID        `json:"release_id"`
	Scope           string             `json:"scope"`
	StoreID         pgtype.UUID        `json:"store_id"`
	DeviceID        pgtype.UUID        `json:"device_id"`
	Mode            string             `json:"mode"`
	Percentage      int32              `json:"percentage"`
	Status          string             `json:"status"`
	NotBefore       pgtype.Timestamptz `json:"not_before"`
	TargetCount     int32              `json:"target_count"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Version         string             `json:"version"`
	ReleaseSequence int64              `json:"release_sequence"`
}

func (q *Queries) ListRollouts(ctx context.Context, arg ListRolloutsParams) ([]ListRolloutsRow, error) {
	rows, err := q.db.Query(ctx, listRollouts,
		arg.StoreID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolloutsRow{}
	for rows.Next() {
		var i ListRolloutsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.Scope,
			&i.StoreID,
			&i.DeviceID,
			&i.Mode,
			&i.Percentage,
			&i.Status,
			&i.NotBefore,
			&i.TargetCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.ReleaseSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetEvents = `-- name: ListTargetEvents :many
SELECT id, target_id, device_id, reported_state, target_state, error_code, retryable, recorded_at
FROM update_target_events WHERE target_id = $1::uuid
ORDER BY id DESC LIMIT $2::int
`

type ListTargetEventsParams struct {
	TargetID pgtype.UUID `json:"target_id"`
	RowLimit int32       `json:"row_limit"`
}

func (q *Queries) ListTargetEvents(ctx context.Context, arg ListTargetEventsParams) ([]UpdateTargetEvent, error) {
	rows, err := q.db.Query(ctx, listTargetEvents, arg.TargetID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdateTargetEvent{}
	for rows.Next() {
		var i UpdateTargetEvent
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.DeviceID,
			&i.ReportedState,
			&i.TargetState,
			&i.ErrorCode,
			&i.Retryable,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpdateAudit = `-- name: ListUpdateAudit :many
SELECT id, occurred_at, actor_kind, actor, action, release_id, rollout_id, target_id, device_id, store_id, details
FROM update_audit_events
WHERE ($1::uuid IS NULL OR store_id = $1::uuid)
  AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3::int
`

type ListUpdateAuditParams struct {
	StoreID  pgtype.UUID `json:"store_id"`
	BeforeID int64       `json:"before_id"`
	RowLimit int32       `json:"row_limit"`
}

func (q *Queries) ListUpdateAudit(ctx context.Context, arg ListUpdateAuditParams) ([]UpdateAuditEvent, error) {
	rows, err := q.db.Query(ctx, listUpdateAudit, arg.StoreID, arg.BeforeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdateAuditEvent{}
	for rows.Next() {
		var i UpdateAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorKind,
			&i.Actor,
			&i.Action,
			&i.ReleaseID,
			&i.RolloutID,
			&i.TargetID,
			&i.DeviceID,
			&i.StoreID,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeviceTarget = `-- name: LockDeviceTarget :one
SELECT t.id, t.rollout_id, t.device_id, t.store_id, t.state, t.attempt_count, t.last_error,
    rel.id AS release_id, rel.release_sequence, rel.manifest_digest, rel.status AS release_status, r.status AS rollout_status
FROM update_rollout_targets t
JOIN update_rollouts r ON r.id = t.rollout_id
JOIN releases rel ON rel.id = r.release_id
WHERE t.id = $1::uuid AND t.device_id = $2::uuid
FOR UPDATE OF t
`

type LockDeviceTargetParams struct {
	ID       pgtype.UUID `json:"id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

type LockDeviceTargetRow struct {
	ID              pgtype.UUID `json:"id"`
	RolloutID       pgtype.UUID `json:"rollout_id"`
	DeviceID        pgtype.UUID `json:"device_id"`
	StoreID         pgtype.UUID `json:"store_id"`
	State           string      `json:"state"`
	AttemptCount    int32       `json:"attempt_count"`
	LastError       pgtype.Text `json:"last_error"`
	ReleaseID       pgtype.UUID `json:"release_id"`
	ReleaseSequence int64       `json:"release_sequence"`
	ManifestDigest  string      `json:"manifest_digest"`
	ReleaseStatus   string      `json:"release_status"`
	RolloutStatus   string      `json:"rollout_status"`
}

func (q *Queries) LockDeviceTarget(ctx context.Context, arg LockDeviceTargetParams) (LockDeviceTargetRow, error) {
	row := q.db.QueryRow(ctx, lockDeviceTarget, arg.ID, arg.DeviceID)
	var i LockDeviceTargetRow
	err := row.Scan(
		&i.ID,
		&i.RolloutID,
		&i.DeviceID,
		&i.StoreID,
		&i.State,
		&i.AttemptCount,
		&i.LastError,
		&i.ReleaseID,
		&i.ReleaseSequence,
		&i.ManifestDigest,
		&i.ReleaseStatus,
		&i.RolloutStatus,
	)
	return i, err
}

const lockRollout = `-- name: LockRollout :one
SELECT id, release_id, scope, store_id, device_id, mode, percentage, status, not_before, target_count,
    created_by, created_at, updated_at
FROM update_rollouts WHERE id = $1::uuid FOR UPDATE
`

func (q *Queries) LockRollout(ctx context.Context, id pgtype.UUID) (UpdateRollout, error) {
	row := q.db.QueryRow(ctx, lockRollout, id)
	var i UpdateRollout
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Scope,
		&i.StoreID,
		&i.DeviceID,
		&i.Mode,
		&i.Percentage,
		&i.Status,
		&i.NotBefore,
		&i.TargetCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markIncapableDeviceTargets = `-- name: MarkIncapableDeviceTargets :execrows
UPDATE update_rollout_targets SET state = 'UNSUPPORTED', last_error = $1::text,
    finished_at = $2::timestamptz, updated_at = $2::timestamptz
WHERE device_id = $3::uuid AND state = 'PENDING'
`

type MarkIncapableDeviceTargetsParams struct {
	Reason   string             `json:"reason"`
	Now      pgtype.Timestamptz `json:"now"`
	DeviceID pgtype.UUID        `json:"device_id"`
}

func (q *Queries) MarkIncapableDeviceTargets(ctx context.Context, arg MarkIncapableDeviceTargetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, markIncapableDeviceTargets, arg.Reason, arg.Now, arg.DeviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNewerDeviceTargets = `-- name: MarkNewerDeviceTargets :execrows
UPDATE update_rollout_targets t
SET state = CASE WHEN rel.release_sequence = $1::bigint THEN 'ALREADY_COMPLIANT' ELSE 'SKIPPED_NEWER' END,
    finished_at = $2::timestamptz, updated_at = $2::timestamptz
FROM update_rollouts r JOIN releases rel ON rel.id = r.release_id
WHERE r.id = t.rollout_id AND t.device_id = $3::uuid AND t.state = 'PENDING'
  AND (rel.release_sequence < $1::bigint
       OR (rel.release_sequence = $1::bigint AND rel.build_commit = $4::text))
`

type MarkNewerDeviceTargetsParams struct {
	ReleaseSequence int64              `json:"release_sequence"`
	Now             pgtype.Timestamptz `json:"now"`
	DeviceID        pgtype.UUID        `json:"device_id"`
	BuildCommit     string             `json:"build_commit"`
}

// A device already at or past the target never downgrades (§58-§59).
func (q *Queries) MarkNewerDeviceTargets(ctx context.Context, arg MarkNewerDeviceTargetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNewerDeviceTargets,
		arg.ReleaseSequence,
		arg.Now,
		arg.DeviceID,
		arg.BuildCommit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTargetDelivered = `-- name: MarkTargetDelivered :exec
UPDATE update_rollout_targets SET state = 'DELIVERED', delivered_at = COALESCE(delivered_at, $1::timestamptz),
    updated_at = $1::timestamptz
WHERE id = $2::uuid AND state IN ('PENDING','DELIVERED')
`

type MarkTargetDeliveredParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

func (q *Queries) MarkTargetDelivered(ctx context.Context, arg MarkTargetDeliveredParams) error {
	_, err := q.db.Exec(ctx, markTargetDelivered, arg.Now, arg.ID)
	return err
}

const markUnsupportedPlatformTargets = `-- name: MarkUnsupportedPlatformTargets :execrows
UPDATE update_rollout_targets t SET state = 'UNSUPPORTED', last_error = 'UPDATE_PLATFORM_UNSUPPORTED',
    finished_at = $1::timestamptz, updated_at = $1::timestamptz
FROM update_rollouts r
WHERE r.id = t.rollout_id AND t.device_id = $2::uuid AND t.state = 'PENDING'
  AND NOT EXISTS (SELECT 1 FROM release_artifacts a WHERE a.release_id = r.release_id
                  AND a.os = $3::text AND a.arch = $4::text AND a.package = $5::text)
`

type MarkUnsupportedPlatformTargetsParams struct {
	Now      pgtype.Timestamptz `json:"now"`
	DeviceID pgtype.UUID        `json:"device_id"`
	Os       string             `json:"os"`
	Arch     string             `json:"arch"`
	Package  string             `json:"package"`
}

// Targets whose release has no artifact for the device platform can never
// be delivered: terminal UNSUPPORTED instead of permanent retry (§131).
func (q *Queries) MarkUnsupportedPlatformTargets(ctx context.Context, arg MarkUnsupportedPlatformTargetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUnsupportedPlatformTargets,
		arg.Now,
		arg.DeviceID,
		arg.Os,
		arg.Arch,
		arg.Package,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const openRolloutTargetCount = `-- name: OpenRolloutTargetCount :one
SELECT count(*)::bigint FROM update_rollout_targets
WHERE rollout_id = $1::uuid
  AND state IN ('NOT_SELECTED','PENDING','DELIVERED','DOWNLOADING','VERIFIED','WAITING_SAFE_BOUNDARY','INSTALLING','AWAITING_HEALTH')
`

func (q *Queries) OpenRolloutTargetCount(ctx context.Context, rolloutID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, openRolloutTargetCount, rolloutID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const promoteSelectedTargets = `-- name: PromoteSelectedTargets :execrows
UPDATE update_rollout_targets SET state = 'PENDING', updated_at = $1::timestamptz
WHERE rollout_id = $2::uuid AND state = 'NOT_SELECTED' AND bucket < $3::int
`

type PromoteSelectedTargetsParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	RolloutID  pgtype.UUID        `json:"rollout_id"`
	Percentage int32              `json:"percentage"`
}

func (q *Queries) PromoteSelectedTargets(ctx context.Context, arg PromoteSelectedTargetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteSelectedTargets, arg.Now, arg.RolloutID, arg.Percentage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setReleaseStatus = `-- name: SetReleaseStatus :execrows
UPDATE releases SET status = $1::text, status_changed_by = $2::text, status_changed_at = $3::timestamptz
WHERE id = $4::uuid AND status <> $1::text
`

type SetReleaseStatusParams struct {
	Status string             `json:"status"`
	Actor  string             `json:"actor"`
	Now    pgtype.Timestamptz `json:"now"`
	ID     pgtype.UUID        `json:"id"`
}

func (q *Queries) SetReleaseStatus(ctx context.Context, arg SetReleaseStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReleaseStatus,
		arg.Status,
		arg.Actor,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRolloutPercentage = `-- name: SetRolloutPercentage :execrows
UPDATE update_rollouts SET percentage = $1::int, updated_at = $2::timestamptz
WHERE id = $3::uuid AND percentage < $1::int AND status IN ('DRAFT','ACTIVE','PAUSED')
`

type SetRolloutPercentageParams struct {
	Percentage int32              `json:"percentage"`
	Now        pgtype.Timestamptz `json:"now"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) SetRolloutPercentage(ctx context.Context, arg SetRolloutPercentageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRolloutPercentage, arg.Percentage, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRolloutStatus = `-- name: SetRolloutStatus :execrows
UPDATE update_rollouts SET status = $1::text, updated_at = $2::timestamptz
WHERE id = $3::uuid AND status = ANY($4::text[])
`

type SetRolloutStatusParams struct {
	ToStatus     string             `json:"to_status"`
	Now          pgtype.Timestamptz `json:"now"`
	ID           pgtype.UUID        `json:"id"`
	FromStatuses []string           `json:"from_statuses"`
}

func (q *Queries) SetRolloutStatus(ctx context.Context, arg SetRolloutStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRolloutStatus,
		arg.ToStatus,
		arg.Now,
		arg.ID,
		arg.FromStatuses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTargetState = `-- name: UpdateTargetState :exec
UPDATE update_rollout_targets SET state = $1::text, last_error = $2::text,
    retryable = $3::bool, attempt_count = $4::int,
    next_attempt_at = $5::timestamptz, finished_at = $6::timestamptz,
    updated_at = $7::timestamptz
WHERE id = $8::uuid
`

type UpdateTargetStateParams struct {
	State         string             `json:"state"`
	LastError     pgtype.Text        `json:"last_error"`
	Retryable     bool               `json:"retryable"`
	AttemptCount  int32              `json:"attempt_count"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Now           pgtype.Timestamptz `json:"now"`
	ID            pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateTargetState(ctx context.Context, arg UpdateTargetStateParams) error {
	_, err := q.db.Exec(ctx, updateTargetState,
		arg.State,
		arg.LastError,
		arg.Retryable,
		arg.AttemptCount,
		arg.NextAttemptAt,
		arg.FinishedAt,
		arg.Now,
		arg.ID,
	)
	return err
}

const upsertDeviceUpdateStatus = `-- name: UpsertDeviceUpdateStatus :exec
INSERT INTO device_update_status (device_id, version, build_commit, release_sequence, os, arch, updater_protocol,
    updater_capable, unsupported_reason, update_state, update_error, reported_at)
VALUES ($1::uuid, $2::text, $3::text, $4::bigint, $5::text, $6::text,
    $7::int, $8::bool, $9::text, $10::text,
    $11::text, $12::timestamptz)
ON CONFLICT (device_id) DO UPDATE SET version = EXCLUDED.version, build_commit = EXCLUDED.build_commit,
    release_sequence = EXCLUDED.release_sequence, os = EXCLUDED.os, arch = EXCLUDED.arch,
    updater_protocol = EXCLUDED.updater_protocol, updater_capable = EXCLUDED.updater_capable,
    unsupported_reason = EXCLUDED.unsupported_reason, update_state = EXCLUDED.update_state,
    update_error = EXCLUDED.update_error, reported_at = EXCLUDED.reported_at
`

type UpsertDeviceUpdateStatusParams struct {
	DeviceID          pgtype.UUID        `json:"device_id"`
	Version           string             `json:"version"`
	BuildCommit       string             `json:"build_commit"`
	ReleaseSequence   int64              `json:"release_sequence"`
	Os                string             `json:"os"`
	Arch              string             `json:"arch"`
	UpdaterProtocol   int32              `json:"updater_protocol"`
	UpdaterCapable    bool               `json:"updater_capable"`
	UnsupportedReason pgtype.Text        `json:"unsupported_reason"`
	UpdateState       string             `json:"update_state"`
	UpdateError       pgtype.Text        `json:"update_error"`
	Now               pgtype.Timestamptz `json:"now"`
}

func (q *Queries) UpsertDeviceUpdateStatus(ctx context.Context, arg UpsertDeviceUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceUpdateStatus,
		arg.DeviceID,
		arg.Version,
		arg.BuildCommit,
		arg.ReleaseSequence,
		arg.Os,
		arg.Arch,
		arg.UpdaterProtocol,
		arg.UpdaterCapable,
		arg.UnsupportedReason,
		arg.UpdateState,
		arg.UpdateError,
		arg.Now,
	)
	return err
}
