// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotification = `-- name: ClaimNotification :one
WITH candidate AS (
    SELECT id
    FROM notification_messages
    WHERE dispatch_status IN ('pending', 'retry')
      AND (next_attempt_at IS NULL OR next_attempt_at <= now())
      AND (lease_until IS NULL OR lease_until <= now())
    ORDER BY next_attempt_at NULLS FIRST, created_at, id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE notification_messages AS message
SET lease_owner = $1, lease_until = $2,
    lease_generation = message.lease_generation + 1,
    attempt_count = message.attempt_count + 1, updated_at = now()
FROM candidate
WHERE message.id = candidate.id
RETURNING message.id, message.provider_key, message.idempotency_key,
    message.recipient, message.template_key, message.locale, message.parameters,
    message.ext_template_name, message.ext_language_code, message.ext_parameter_order,
    message.dispatch_status, message.attempt_count, message.send_started_at,
    message.lease_owner, message.lease_generation
`

type ClaimNotificationParams struct {
	LeaseOwner pgtype.Text        `json:"lease_owner"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
}

type ClaimNotificationRow struct {
	ID                pgtype.UUID        `json:"id"`
	ProviderKey       string             `json:"provider_key"`
	IdempotencyKey    string             `json:"idempotency_key"`
	Recipient         string             `json:"recipient"`
	TemplateKey       string             `json:"template_key"`
	Locale            string             `json:"locale"`
	Parameters        []byte             `json:"parameters"`
	ExtTemplateName   string             `json:"ext_template_name"`
	ExtLanguageCode   string             `json:"ext_language_code"`
	ExtParameterOrder []string           `json:"ext_parameter_order"`
	DispatchStatus    string             `json:"dispatch_status"`
	AttemptCount      int32              `json:"attempt_count"`
	SendStartedAt     pgtype.Timestamptz `json:"send_started_at"`
	LeaseOwner        pgtype.Text        `json:"lease_owner"`
	LeaseGeneration   int64              `json:"lease_generation"`
}

func (q *Queries) ClaimNotification(ctx context.Context, arg ClaimNotificationParams) (ClaimNotificationRow, error) {
	row := q.db.QueryRow(ctx, claimNotification, arg.LeaseOwner, arg.LeaseUntil)
	var i ClaimNotificationRow
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.IdempotencyKey,
		&i.Recipient,
		&i.TemplateKey,
		&i.Locale,
		&i.Parameters,
		&i.ExtTemplateName,
		&i.ExtLanguageCode,
		&i.ExtParameterOrder,
		&i.DispatchStatus,
		&i.AttemptCount,
		&i.SendStartedAt,
		&i.LeaseOwner,
		&i.LeaseGeneration,
	)
	return i, err
}

const finishNotificationAccepted = `-- name: FinishNotificationAccepted :execrows
UPDATE notification_messages
SET dispatch_status = 'accepted', provider_message_id = $4,
    delivery_status = 'ACCEPTED', delivery_status_at = now(),
    last_error_code = NULL, lease_owner = NULL, lease_until = NULL,
    updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND lease_generation = $3
  AND dispatch_status IN ('pending', 'retry')
`

type FinishNotificationAcceptedParams struct {
	ID                pgtype.UUID `json:"id"`
	LeaseOwner        pgtype.Text `json:"lease_owner"`
	LeaseGeneration   int64       `json:"lease_generation"`
	ProviderMessageID pgtype.Text `json:"provider_message_id"`
}

func (q *Queries) FinishNotificationAccepted(ctx context.Context, arg FinishNotificationAcceptedParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishNotificationAccepted,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.ProviderMessageID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishNotificationAmbiguous = `-- name: FinishNotificationAmbiguous :execrows
UPDATE notification_messages
SET dispatch_status = 'ambiguous',
    last_error_code = $4, lease_owner = NULL, lease_until = NULL,
    updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND lease_generation = $3
  AND dispatch_status IN ('pending', 'retry')
`

type FinishNotificationAmbiguousParams struct {
	ID              pgtype.UUID `json:"id"`
	LeaseOwner      pgtype.Text `json:"lease_owner"`
	LeaseGeneration int64       `json:"lease_generation"`
	LastErrorCode   pgtype.Text `json:"last_error_code"`
}

func (q *Queries) FinishNotificationAmbiguous(ctx context.Context, arg FinishNotificationAmbiguousParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishNotificationAmbiguous,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.LastErrorCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishNotificationBlocked = `-- name: FinishNotificationBlocked :execrows
UPDATE notification_messages
SET dispatch_status = 'blocked',
    last_error_code = $4, lease_owner = NULL, lease_until = NULL,
    updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND lease_generation = $3
  AND dispatch_status IN ('pending', 'retry')
`

type FinishNotificationBlockedParams struct {
	ID              pgtype.UUID `json:"id"`
	LeaseOwner      pgtype.Text `json:"lease_owner"`
	LeaseGeneration int64       `json:"lease_generation"`
	LastErrorCode   pgtype.Text `json:"last_error_code"`
}

func (q *Queries) FinishNotificationBlocked(ctx context.Context, arg FinishNotificationBlockedParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishNotificationBlocked,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.LastErrorCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishNotificationRetry = `-- name: FinishNotificationRetry :execrows
UPDATE notification_messages
SET dispatch_status = 'retry', next_attempt_at = $4,
    last_error_code = $5, send_started_at = NULL,
    lease_owner = NULL, lease_until = NULL, updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND lease_generation = $3
  AND dispatch_status IN ('pending', 'retry')
`

type FinishNotificationRetryParams struct {
	ID              pgtype.UUID        `json:"id"`
	LeaseOwner      pgtype.Text        `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	NextAttemptAt   pgtype.Timestamptz `json:"next_attempt_at"`
	LastErrorCode   pgtype.Text        `json:"last_error_code"`
}

func (q *Queries) FinishNotificationRetry(ctx context.Context, arg FinishNotificationRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishNotificationRetry,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.NextAttemptAt,
		arg.LastErrorCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, provider_key, idempotency_key, semantic_fingerprint,
    recipient, template_key, locale, parameters,
    ext_template_name, ext_language_code, ext_parameter_order,
    dispatch_status, attempt_count, next_attempt_at,
    lease_owner, lease_until, lease_generation, send_started_at,
    provider_message_id, delivery_status, delivery_status_at,
    last_error_code, created_at, updated_at
FROM notification_messages
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (NotificationMessage, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i NotificationMessage
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.IdempotencyKey,
		&i.SemanticFingerprint,
		&i.Recipient,
		&i.TemplateKey,
		&i.Locale,
		&i.Parameters,
		&i.ExtTemplateName,
		&i.ExtLanguageCode,
		&i.ExtParameterOrder,
		&i.DispatchStatus,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.SendStartedAt,
		&i.ProviderMessageID,
		&i.DeliveryStatus,
		&i.DeliveryStatusAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationByIDForUpdate = `-- name: GetNotificationByIDForUpdate :one
SELECT id, provider_key, idempotency_key, semantic_fingerprint,
    recipient, template_key, locale, parameters,
    ext_template_name, ext_language_code, ext_parameter_order,
    dispatch_status, attempt_count, next_attempt_at,
    lease_owner, lease_until, lease_generation, send_started_at,
    provider_message_id, delivery_status, delivery_status_at,
    last_error_code, created_at, updated_at
FROM notification_messages
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetNotificationByIDForUpdate(ctx context.Context, id pgtype.UUID) (NotificationMessage, error) {
	row := q.db.QueryRow(ctx, getNotificationByIDForUpdate, id)
	var i NotificationMessage
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.IdempotencyKey,
		&i.SemanticFingerprint,
		&i.Recipient,
		&i.TemplateKey,
		&i.Locale,
		&i.Parameters,
		&i.ExtTemplateName,
		&i.ExtLanguageCode,
		&i.ExtParameterOrder,
		&i.DispatchStatus,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LeaseGeneration,
		&i.SendStartedAt,
		&i.ProviderMessageID,
		&i.DeliveryStatus,
		&i.DeliveryStatusAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationByIdempotency = `-- name: GetNotificationByIdempotency :one
SELECT id, provider_key, idempotency_key, semantic_fingerprint,
    recipient, template_key, locale, parameters,
    ext_template_name, ext_language_code, ext_parameter_order,
    dispatch_status, attempt_count, provider_message_id, delivery_status
FROM notification_messages
WHERE provider_key = $1 AND idempotency_key = $2
`

type GetNotificationByIdempotencyParams struct {
	ProviderKey    string `json:"provider_key"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetNotificationByIdempotencyRow struct {
	ID                  pgtype.UUID `json:"id"`
	ProviderKey         string      `json:"provider_key"`
	IdempotencyKey      string      `json:"idempotency_key"`
	SemanticFingerprint []byte      `json:"semantic_fingerprint"`
	Recipient           string      `json:"recipient"`
	TemplateKey         string      `json:"template_key"`
	Locale              string      `json:"locale"`
	Parameters          []byte      `json:"parameters"`
	ExtTemplateName     string      `json:"ext_template_name"`
	ExtLanguageCode     string      `json:"ext_language_code"`
	ExtParameterOrder   []string    `json:"ext_parameter_order"`
	DispatchStatus      string      `json:"dispatch_status"`
	AttemptCount        int32       `json:"attempt_count"`
	ProviderMessageID   pgtype.Text `json:"provider_message_id"`
	DeliveryStatus      string      `json:"delivery_status"`
}

func (q *Queries) GetNotificationByIdempotency(ctx context.Context, arg GetNotificationByIdempotencyParams) (GetNotificationByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getNotificationByIdempotency, arg.ProviderKey, arg.IdempotencyKey)
	var i GetNotificationByIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.IdempotencyKey,
		&i.SemanticFingerprint,
		&i.Recipient,
		&i.TemplateKey,
		&i.Locale,
		&i.Parameters,
		&i.ExtTemplateName,
		&i.ExtLanguageCode,
		&i.ExtParameterOrder,
		&i.DispatchStatus,
		&i.AttemptCount,
		&i.ProviderMessageID,
		&i.DeliveryStatus,
	)
	return i, err
}

const getNotificationByProviderMessage = `-- name: GetNotificationByProviderMessage :one
SELECT id, provider_key, idempotency_key,
    dispatch_status, delivery_status, delivery_status_at
FROM notification_messages
WHERE provider_key = $1 AND provider_message_id = $2
`

type GetNotificationByProviderMessageParams struct {
	ProviderKey       string      `json:"provider_key"`
	ProviderMessageID pgtype.Text `json:"provider_message_id"`
}

type GetNotificationByProviderMessageRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProviderKey      string             `json:"provider_key"`
	IdempotencyKey   string             `json:"idempotency_key"`
	DispatchStatus   string             `json:"dispatch_status"`
	DeliveryStatus   string             `json:"delivery_status"`
	DeliveryStatusAt pgtype.Timestamptz `json:"delivery_status_at"`
}

func (q *Queries) GetNotificationByProviderMessage(ctx context.Context, arg GetNotificationByProviderMessageParams) (GetNotificationByProviderMessageRow, error) {
	row := q.db.QueryRow(ctx, getNotificationByProviderMessage, arg.ProviderKey, arg.ProviderMessageID)
	var i GetNotificationByProviderMessageRow
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.IdempotencyKey,
		&i.DispatchStatus,
		&i.DeliveryStatus,
		&i.DeliveryStatusAt,
	)
	return i, err
}

const getTemplateMapping = `-- name: GetTemplateMapping :one
SELECT provider_key, template_key, locale,
    external_template_name, external_language_code, parameter_names, enabled
FROM notification_template_mappings
WHERE provider_key = $1 AND template_key = $2 AND locale = $3
`

type GetTemplateMappingParams struct {
	ProviderKey string `json:"provider_key"`
	TemplateKey string `json:"template_key"`
	Locale      string `json:"locale"`
}

type GetTemplateMappingRow struct {
	ProviderKey          string   `json:"provider_key"`
	TemplateKey          string   `json:"template_key"`
	Locale               string   `json:"locale"`
	ExternalTemplateName string   `json:"external_template_name"`
	ExternalLanguageCode string   `json:"external_language_code"`
	ParameterNames       []string `json:"parameter_names"`
	Enabled              bool     `json:"enabled"`
}

func (q *Queries) GetTemplateMapping(ctx context.Context, arg GetTemplateMappingParams) (GetTemplateMappingRow, error) {
	row := q.db.QueryRow(ctx, getTemplateMapping, arg.ProviderKey, arg.TemplateKey, arg.Locale)
	var i GetTemplateMappingRow
	err := row.Scan(
		&i.ProviderKey,
		&i.TemplateKey,
		&i.Locale,
		&i.ExternalTemplateName,
		&i.ExternalLanguageCode,
		&i.ParameterNames,
		&i.Enabled,
	)
	return i, err
}

const insertDeliveryStatusHistory = `-- name: InsertDeliveryStatusHistory :one
INSERT INTO notification_delivery_status_history (
    notification_id, provider_key, provider_message_id,
    provider_status_raw, canonical_status, provider_timestamp,
    event_fingerprint, provider_error_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (notification_id, event_fingerprint) DO NOTHING
RETURNING notification_id
`

type InsertDeliveryStatusHistoryParams struct {
	NotificationID    pgtype.UUID        `json:"notification_id"`
	ProviderKey       string             `json:"provider_key"`
	ProviderMessageID string             `json:"provider_message_id"`
	ProviderStatusRaw string             `json:"provider_status_raw"`
	CanonicalStatus   string             `json:"canonical_status"`
	ProviderTimestamp pgtype.Timestamptz `json:"provider_timestamp"`
	EventFingerprint  []byte             `json:"event_fingerprint"`
	ProviderErrorCode pgtype.Text        `json:"provider_error_code"`
}

func (q *Queries) InsertDeliveryStatusHistory(ctx context.Context, arg InsertDeliveryStatusHistoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDeliveryStatusHistory,
		arg.NotificationID,
		arg.ProviderKey,
		arg.ProviderMessageID,
		arg.ProviderStatusRaw,
		arg.CanonicalStatus,
		arg.ProviderTimestamp,
		arg.EventFingerprint,
		arg.ProviderErrorCode,
	)
	var notification_id pgtype.UUID
	err := row.Scan(&notification_id)
	return notification_id, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notification_messages (
    id, provider_key, idempotency_key, semantic_fingerprint,
    recipient, template_key, locale, parameters,
    ext_template_name, ext_language_code, ext_parameter_order
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (provider_key, idempotency_key) DO NOTHING
RETURNING id
`

type InsertNotificationParams struct {
	ID                  pgtype.UUID `json:"id"`
	ProviderKey         string      `json:"provider_key"`
	IdempotencyKey      string      `json:"idempotency_key"`
	SemanticFingerprint []byte      `json:"semantic_fingerprint"`
	Recipient           string      `json:"recipient"`
	TemplateKey         string      `json:"template_key"`
	Locale              string      `json:"locale"`
	Parameters          []byte      `json:"parameters"`
	ExtTemplateName     string      `json:"ext_template_name"`
	ExtLanguageCode     string      `json:"ext_language_code"`
	ExtParameterOrder   []string    `json:"ext_parameter_order"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.ID,
		arg.ProviderKey,
		arg.IdempotencyKey,
		arg.SemanticFingerprint,
		arg.Recipient,
		arg.TemplateKey,
		arg.Locale,
		arg.Parameters,
		arg.ExtTemplateName,
		arg.ExtLanguageCode,
		arg.ExtParameterOrder,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listTemplateMappings = `-- name: ListTemplateMappings :many
SELECT provider_key, template_key, locale,
    external_template_name, external_language_code, parameter_names, enabled
FROM notification_template_mappings
WHERE (NULLIF($1::text, '') IS NULL OR provider_key = $1)
ORDER BY provider_key, template_key, locale
`

type ListTemplateMappingsRow struct {
	ProviderKey          string   `json:"provider_key"`
	TemplateKey          string   `json:"template_key"`
	Locale               string   `json:"locale"`
	ExternalTemplateName string   `json:"external_template_name"`
	ExternalLanguageCode string   `json:"external_language_code"`
	ParameterNames       []string `json:"parameter_names"`
	Enabled              bool     `json:"enabled"`
}

func (q *Queries) ListTemplateMappings(ctx context.Context, dollar_1 string) ([]ListTemplateMappingsRow, error) {
	rows, err := q.db.Query(ctx, listTemplateMappings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateMappingsRow{}
	for rows.Next() {
		var i ListTemplateMappingsRow
		if err := rows.Scan(
			&i.ProviderKey,
			&i.TemplateKey,
			&i.Locale,
			&i.ExternalTemplateName,
			&i.ExternalLanguageCode,
			&i.ParameterNames,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationSendStarted = `-- name: MarkNotificationSendStarted :execrows
UPDATE notification_messages
SET send_started_at = now(), updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND lease_generation = $3
  AND dispatch_status IN ('pending', 'retry')
`

type MarkNotificationSendStartedParams struct {
	ID              pgtype.UUID `json:"id"`
	LeaseOwner      pgtype.Text `json:"lease_owner"`
	LeaseGeneration int64       `json:"lease_generation"`
}

func (q *Queries) MarkNotificationSendStarted(ctx context.Context, arg MarkNotificationSendStartedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationSendStarted, arg.ID, arg.LeaseOwner, arg.LeaseGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notificationQueueStats = `-- name: NotificationQueueStats :one
SELECT
    count(*) FILTER (WHERE dispatch_status = 'pending')::bigint AS pending,
    count(*) FILTER (WHERE dispatch_status = 'retry')::bigint AS retry,
    count(*) FILTER (WHERE dispatch_status = 'accepted')::bigint AS accepted,
    count(*) FILTER (WHERE dispatch_status = 'blocked')::bigint AS blocked,
    count(*) FILTER (WHERE dispatch_status = 'ambiguous')::bigint AS ambiguous,
    min(created_at) FILTER (WHERE dispatch_status IN ('pending', 'retry'))::timestamptz AS oldest_pending
FROM notification_messages
`

type NotificationQueueStatsRow struct {
	Pending       int64              `json:"pending"`
	Retry         int64              `json:"retry"`
	Accepted      int64              `json:"accepted"`
	Blocked       int64              `json:"blocked"`
	Ambiguous     int64              `json:"ambiguous"`
	OldestPending pgtype.Timestamptz `json:"oldest_pending"`
}

func (q *Queries) NotificationQueueStats(ctx context.Context) (NotificationQueueStatsRow, error) {
	row := q.db.QueryRow(ctx, notificationQueueStats)
	var i NotificationQueueStatsRow
	err := row.Scan(
		&i.Pending,
		&i.Retry,
		&i.Accepted,
		&i.Blocked,
		&i.Ambiguous,
		&i.OldestPending,
	)
	return i, err
}

const updateNotificationDelivery = `-- name: UpdateNotificationDelivery :execrows
UPDATE notification_messages
SET delivery_status = $2, delivery_status_at = $3, updated_at = now()
WHERE id = $1
`

type UpdateNotificationDeliveryParams struct {
	ID               pgtype.UUID        `json:"id"`
	DeliveryStatus   string             `json:"delivery_status"`
	DeliveryStatusAt pgtype.Timestamptz `json:"delivery_status_at"`
}

func (q *Queries) UpdateNotificationDelivery(ctx context.Context, arg UpdateNotificationDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNotificationDelivery, arg.ID, arg.DeliveryStatus, arg.DeliveryStatusAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertTemplateMapping = `-- name: UpsertTemplateMapping :exec

INSERT INTO notification_template_mappings AS mapping (
    provider_key, template_key, locale,
    external_template_name, external_language_code, parameter_names, enabled, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (provider_key, template_key, locale) DO UPDATE SET
    external_template_name = EXCLUDED.external_template_name,
    external_language_code = EXCLUDED.external_language_code,
    parameter_names = EXCLUDED.parameter_names,
    enabled = EXCLUDED.enabled,
    updated_at = now()
`

type UpsertTemplateMappingParams struct {
	ProviderKey          string   `json:"provider_key"`
	TemplateKey          string   `json:"template_key"`
	Locale               string   `json:"locale"`
	ExternalTemplateName string   `json:"external_template_name"`
	ExternalLanguageCode string   `json:"external_language_code"`
	ParameterNames       []string `json:"parameter_names"`
	Enabled              bool     `json:"enabled"`
}

// Notification template mappings, idempotent outbox, and delivery
// history (Phase 7A). One statement per query: sqlc :exec drops
// trailing statements silently.
func (q *Queries) UpsertTemplateMapping(ctx context.Context, arg UpsertTemplateMappingParams) error {
	_, err := q.db.Exec(ctx, upsertTemplateMapping,
		arg.ProviderKey,
		arg.TemplateKey,
		arg.Locale,
		arg.ExternalTemplateName,
		arg.ExternalLanguageCode,
		arg.ParameterNames,
		arg.Enabled,
	)
	return err
}
