// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeIncident = `-- name: AcknowledgeIncident :one
UPDATE operational_incidents
SET state = 'acknowledged', acknowledged_at = COALESCE(acknowledged_at, $2), updated_at = $2
WHERE id = $1 AND state = 'open'
RETURNING id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
`

type AcknowledgeIncidentParams struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AcknowledgeIncident(ctx context.Context, arg AcknowledgeIncidentParams) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, acknowledgeIncident, arg.ID, arg.UpdatedAt)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const checkDeviceActive = `-- name: CheckDeviceActive :one
SELECT status
FROM devices
WHERE id = $1
`

func (q *Queries) CheckDeviceActive(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, checkDeviceActive, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const claimAlertDelivery = `-- name: ClaimAlertDelivery :one
SELECT id, incident_id, recipient_id, event_type, provider_key_snapshot, recipient_snapshot,
    locale_snapshot, template_key, body_snapshot, body_fingerprint, notification_id, notification_idempotency_key,
    status, last_error_code, created_at, updated_at
FROM operational_alert_deliveries
WHERE status = 'pending'
ORDER BY created_at, id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimAlertDelivery(ctx context.Context) (OperationalAlertDelivery, error) {
	row := q.db.QueryRow(ctx, claimAlertDelivery)
	var i OperationalAlertDelivery
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.RecipientID,
		&i.EventType,
		&i.ProviderKeySnapshot,
		&i.RecipientSnapshot,
		&i.LocaleSnapshot,
		&i.TemplateKey,
		&i.BodySnapshot,
		&i.BodyFingerprint,
		&i.NotificationID,
		&i.NotificationIdempotencyKey,
		&i.Status,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimRecoveryAction = `-- name: ClaimRecoveryAction :one
SELECT id, incident_id, action_type, state, idempotency_key, target_entity_id, result_code,
    attempt_count, next_attempt_at, last_error_code, created_at, updated_at
FROM operational_recovery_actions
WHERE state = 'pending' AND (next_attempt_at IS NULL OR next_attempt_at <= $1)
ORDER BY created_at, id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimRecoveryAction(ctx context.Context, nextAttemptAt pgtype.Timestamptz) (OperationalRecoveryAction, error) {
	row := q.db.QueryRow(ctx, claimRecoveryAction, nextAttemptAt)
	var i OperationalRecoveryAction
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.ActionType,
		&i.State,
		&i.IdempotencyKey,
		&i.TargetEntityID,
		&i.ResultCode,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveIncidentsByDevice = `-- name: CountActiveIncidentsByDevice :many
SELECT subject_id AS device_id, count(*)::INTEGER AS open_count,
    MAX(CASE severity WHEN 'urgent' THEN 2 ELSE 1 END)::INTEGER AS max_severity
FROM operational_incidents
WHERE subject_type = 'device' AND state IN ('open', 'acknowledged')
GROUP BY subject_id
`

type CountActiveIncidentsByDeviceRow struct {
	DeviceID    string `json:"device_id"`
	OpenCount   int32  `json:"open_count"`
	MaxSeverity int32  `json:"max_severity"`
}

func (q *Queries) CountActiveIncidentsByDevice(ctx context.Context) ([]CountActiveIncidentsByDeviceRow, error) {
	rows, err := q.db.Query(ctx, countActiveIncidentsByDevice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveIncidentsByDeviceRow{}
	for rows.Next() {
		var i CountActiveIncidentsByDeviceRow
		if err := rows.Scan(&i.DeviceID, &i.OpenCount, &i.MaxSeverity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAlertDelivery = `-- name: CreateAlertDelivery :one
INSERT INTO operational_alert_deliveries (id, incident_id, recipient_id, event_type, provider_key_snapshot, recipient_snapshot,
    locale_snapshot, template_key, body_snapshot, body_fingerprint, notification_idempotency_key, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'pending', $12, $12)
RETURNING id, incident_id, recipient_id, event_type, provider_key_snapshot, recipient_snapshot,
    locale_snapshot, template_key, body_snapshot, body_fingerprint, notification_id, notification_idempotency_key,
    status, last_error_code, created_at, updated_at
`

type CreateAlertDeliveryParams struct {
	ID                         pgtype.UUID        `json:"id"`
	IncidentID                 pgtype.UUID        `json:"incident_id"`
	RecipientID                pgtype.UUID        `json:"recipient_id"`
	EventType                  string             `json:"event_type"`
	ProviderKeySnapshot        string             `json:"provider_key_snapshot"`
	RecipientSnapshot          string             `json:"recipient_snapshot"`
	LocaleSnapshot             string             `json:"locale_snapshot"`
	TemplateKey                string             `json:"template_key"`
	BodySnapshot               string             `json:"body_snapshot"`
	BodyFingerprint            []byte             `json:"body_fingerprint"`
	NotificationIdempotencyKey string             `json:"notification_idempotency_key"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAlertDelivery(ctx context.Context, arg CreateAlertDeliveryParams) (OperationalAlertDelivery, error) {
	row := q.db.QueryRow(ctx, createAlertDelivery,
		arg.ID,
		arg.IncidentID,
		arg.RecipientID,
		arg.EventType,
		arg.ProviderKeySnapshot,
		arg.RecipientSnapshot,
		arg.LocaleSnapshot,
		arg.TemplateKey,
		arg.BodySnapshot,
		arg.BodyFingerprint,
		arg.NotificationIdempotencyKey,
		arg.CreatedAt,
	)
	var i OperationalAlertDelivery
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.RecipientID,
		&i.EventType,
		&i.ProviderKeySnapshot,
		&i.RecipientSnapshot,
		&i.LocaleSnapshot,
		&i.TemplateKey,
		&i.BodySnapshot,
		&i.BodyFingerprint,
		&i.NotificationID,
		&i.NotificationIdempotencyKey,
		&i.Status,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAlertDeliveryIdempotent = `-- name: CreateAlertDeliveryIdempotent :one
INSERT INTO operational_alert_deliveries (id, incident_id, recipient_id, event_type, provider_key_snapshot, recipient_snapshot,
    locale_snapshot, template_key, body_snapshot, body_fingerprint, notification_idempotency_key, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'pending', $12, $12)
ON CONFLICT (incident_id, event_type, recipient_id) DO NOTHING
RETURNING id, incident_id, recipient_id, event_type, provider_key_snapshot, recipient_snapshot,
    locale_snapshot, template_key, body_snapshot, body_fingerprint, notification_id, notification_idempotency_key,
    status, last_error_code, created_at, updated_at
`

type CreateAlertDeliveryIdempotentParams struct {
	ID                         pgtype.UUID        `json:"id"`
	IncidentID                 pgtype.UUID        `json:"incident_id"`
	RecipientID                pgtype.UUID        `json:"recipient_id"`
	EventType                  string             `json:"event_type"`
	ProviderKeySnapshot        string             `json:"provider_key_snapshot"`
	RecipientSnapshot          string             `json:"recipient_snapshot"`
	LocaleSnapshot             string             `json:"locale_snapshot"`
	TemplateKey                string             `json:"template_key"`
	BodySnapshot               string             `json:"body_snapshot"`
	BodyFingerprint            []byte             `json:"body_fingerprint"`
	NotificationIdempotencyKey string             `json:"notification_idempotency_key"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAlertDeliveryIdempotent(ctx context.Context, arg CreateAlertDeliveryIdempotentParams) (OperationalAlertDelivery, error) {
	row := q.db.QueryRow(ctx, createAlertDeliveryIdempotent,
		arg.ID,
		arg.IncidentID,
		arg.RecipientID,
		arg.EventType,
		arg.ProviderKeySnapshot,
		arg.RecipientSnapshot,
		arg.LocaleSnapshot,
		arg.TemplateKey,
		arg.BodySnapshot,
		arg.BodyFingerprint,
		arg.NotificationIdempotencyKey,
		arg.CreatedAt,
	)
	var i OperationalAlertDelivery
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.RecipientID,
		&i.EventType,
		&i.ProviderKeySnapshot,
		&i.RecipientSnapshot,
		&i.LocaleSnapshot,
		&i.TemplateKey,
		&i.BodySnapshot,
		&i.BodyFingerprint,
		&i.NotificationID,
		&i.NotificationIdempotencyKey,
		&i.Status,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAlertRecipient = `-- name: CreateAlertRecipient :one

INSERT INTO operational_alert_recipients (id, label, provider_key, recipient, locale, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, TRUE, $6, $6)
RETURNING id, label, provider_key, recipient, locale, enabled, created_at, updated_at
`

type CreateAlertRecipientParams struct {
	ID          pgtype.UUID        `json:"id"`
	Label       string             `json:"label"`
	ProviderKey string             `json:"provider_key"`
	Recipient   string             `json:"recipient"`
	Locale      string             `json:"locale"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Phase 7D operational incidents, alert deliveries, recovery actions.
func (q *Queries) CreateAlertRecipient(ctx context.Context, arg CreateAlertRecipientParams) (OperationalAlertRecipient, error) {
	row := q.db.QueryRow(ctx, createAlertRecipient,
		arg.ID,
		arg.Label,
		arg.ProviderKey,
		arg.Recipient,
		arg.Locale,
		arg.CreatedAt,
	)
	var i OperationalAlertRecipient
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.ProviderKey,
		&i.Recipient,
		&i.Locale,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecoveryAction = `-- name: CreateRecoveryAction :one
INSERT INTO operational_recovery_actions (id, incident_id, action_type, state, idempotency_key, created_at, updated_at)
VALUES ($1, $2, $3, 'pending', $4, $5, $5)
ON CONFLICT (incident_id, action_type) DO NOTHING
RETURNING id, incident_id, action_type, state, idempotency_key, target_entity_id, result_code,
    attempt_count, next_attempt_at, last_error_code, created_at, updated_at
`

type CreateRecoveryActionParams struct {
	ID             pgtype.UUID        `json:"id"`
	IncidentID     pgtype.UUID        `json:"incident_id"`
	ActionType     string             `json:"action_type"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRecoveryAction(ctx context.Context, arg CreateRecoveryActionParams) (OperationalRecoveryAction, error) {
	row := q.db.QueryRow(ctx, createRecoveryAction,
		arg.ID,
		arg.IncidentID,
		arg.ActionType,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i OperationalRecoveryAction
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.ActionType,
		&i.State,
		&i.IdempotencyKey,
		&i.TargetEntityID,
		&i.ResultCode,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableAlertRecipient = `-- name: DisableAlertRecipient :execrows
UPDATE operational_alert_recipients SET enabled = FALSE, updated_at = $2 WHERE id = $1 AND enabled
`

type DisableAlertRecipientParams struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DisableAlertRecipient(ctx context.Context, arg DisableAlertRecipientParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableAlertRecipient, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishAlertDeliveryBlocked = `-- name: FinishAlertDeliveryBlocked :execrows
UPDATE operational_alert_deliveries
SET status = 'blocked', last_error_code = $2, updated_at = $3
WHERE id = $1 AND status = 'pending'
`

type FinishAlertDeliveryBlockedParams struct {
	ID            pgtype.UUID        `json:"id"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FinishAlertDeliveryBlocked(ctx context.Context, arg FinishAlertDeliveryBlockedParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAlertDeliveryBlocked, arg.ID, arg.LastErrorCode, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishAlertDeliverySent = `-- name: FinishAlertDeliverySent :execrows
UPDATE operational_alert_deliveries
SET status = 'sent', notification_id = $2, updated_at = $3
WHERE id = $1 AND status = 'pending'
`

type FinishAlertDeliverySentParams struct {
	ID             pgtype.UUID        `json:"id"`
	NotificationID pgtype.UUID        `json:"notification_id"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FinishAlertDeliverySent(ctx context.Context, arg FinishAlertDeliverySentParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAlertDeliverySent, arg.ID, arg.NotificationID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishRecoveryBlocked = `-- name: FinishRecoveryBlocked :execrows
UPDATE operational_recovery_actions
SET state = 'blocked', last_error_code = $2, updated_at = $3
WHERE id = $1 AND state = 'pending'
`

type FinishRecoveryBlockedParams struct {
	ID            pgtype.UUID        `json:"id"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FinishRecoveryBlocked(ctx context.Context, arg FinishRecoveryBlockedParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRecoveryBlocked, arg.ID, arg.LastErrorCode, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishRecoveryCompleted = `-- name: FinishRecoveryCompleted :execrows
UPDATE operational_recovery_actions
SET state = 'completed', target_entity_id = $2, result_code = $3, updated_at = $4
WHERE id = $1 AND state = 'pending'
`

type FinishRecoveryCompletedParams struct {
	ID             pgtype.UUID        `json:"id"`
	TargetEntityID pgtype.Text        `json:"target_entity_id"`
	ResultCode     pgtype.Text        `json:"result_code"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FinishRecoveryCompleted(ctx context.Context, arg FinishRecoveryCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRecoveryCompleted,
		arg.ID,
		arg.TargetEntityID,
		arg.ResultCode,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveIncident = `-- name: GetActiveIncident :one
SELECT id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
FROM operational_incidents
WHERE rule_key = $1 AND subject_type = $2 AND subject_id = $3
  AND state IN ('open', 'acknowledged')
ORDER BY opened_at DESC, id DESC
LIMIT 1
`

type GetActiveIncidentParams struct {
	RuleKey     string `json:"rule_key"`
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
}

func (q *Queries) GetActiveIncident(ctx context.Context, arg GetActiveIncidentParams) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, getActiveIncident, arg.RuleKey, arg.SubjectType, arg.SubjectID)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const getCommandTerminal = `-- name: GetCommandTerminal :one
SELECT status
FROM device_control_commands
WHERE id = $1
`

func (q *Queries) GetCommandTerminal(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getCommandTerminal, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getDeliveryByIdentity = `-- name: GetDeliveryByIdentity :one
SELECT id, incident_id, recipient_id, event_type, provider_key_snapshot, recipient_snapshot,
    locale_snapshot, template_key, body_snapshot, body_fingerprint, notification_id, notification_idempotency_key,
    status, last_error_code, created_at, updated_at
FROM operational_alert_deliveries
WHERE incident_id = $1 AND event_type = $2 AND recipient_id = $3
`

type GetDeliveryByIdentityParams struct {
	IncidentID  pgtype.UUID `json:"incident_id"`
	EventType   string      `json:"event_type"`
	RecipientID pgtype.UUID `json:"recipient_id"`
}

func (q *Queries) GetDeliveryByIdentity(ctx context.Context, arg GetDeliveryByIdentityParams) (OperationalAlertDelivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByIdentity, arg.IncidentID, arg.EventType, arg.RecipientID)
	var i OperationalAlertDelivery
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.RecipientID,
		&i.EventType,
		&i.ProviderKeySnapshot,
		&i.RecipientSnapshot,
		&i.LocaleSnapshot,
		&i.TemplateKey,
		&i.BodySnapshot,
		&i.BodyFingerprint,
		&i.NotificationID,
		&i.NotificationIdempotencyKey,
		&i.Status,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncident = `-- name: GetIncident :one
SELECT id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
FROM operational_incidents
WHERE id = $1
`

func (q *Queries) GetIncident(ctx context.Context, id pgtype.UUID) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const getIncidentByEventKey = `-- name: GetIncidentByEventKey :one
SELECT id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
FROM operational_incidents
WHERE source_event_key = $1
ORDER BY opened_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetIncidentByEventKey(ctx context.Context, sourceEventKey pgtype.Text) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, getIncidentByEventKey, sourceEventKey)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const getNotificationDispatch = `-- name: GetNotificationDispatch :one
SELECT dispatch_status
FROM notification_messages
WHERE id = $1
`

func (q *Queries) GetNotificationDispatch(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getNotificationDispatch, id)
	var dispatch_status string
	err := row.Scan(&dispatch_status)
	return dispatch_status, err
}

const getRecoveryAction = `-- name: GetRecoveryAction :one
SELECT id, incident_id, action_type, state, idempotency_key, target_entity_id, result_code,
    attempt_count, next_attempt_at, last_error_code, created_at, updated_at
FROM operational_recovery_actions
WHERE incident_id = $1 AND action_type = $2
`

type GetRecoveryActionParams struct {
	IncidentID pgtype.UUID `json:"incident_id"`
	ActionType string      `json:"action_type"`
}

func (q *Queries) GetRecoveryAction(ctx context.Context, arg GetRecoveryActionParams) (OperationalRecoveryAction, error) {
	row := q.db.QueryRow(ctx, getRecoveryAction, arg.IncidentID, arg.ActionType)
	var i OperationalRecoveryAction
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.ActionType,
		&i.State,
		&i.IdempotencyKey,
		&i.TargetEntityID,
		&i.ResultCode,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunTerminal = `-- name: GetRunTerminal :one
SELECT status
FROM business_report_runs
WHERE id = $1
`

func (q *Queries) GetRunTerminal(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getRunTerminal, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listActiveByRule = `-- name: ListActiveByRule :many
SELECT id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
FROM operational_incidents
WHERE rule_key = $1 AND state IN ('open', 'acknowledged')
ORDER BY last_observed_at, id
LIMIT $2
`

type ListActiveByRuleParams struct {
	RuleKey string `json:"rule_key"`
	Limit   int32  `json:"limit"`
}

// Least-recently-checked first: resolution loops touch every checked
// row, so no head-of-line batch can starve later rows indefinitely.
func (q *Queries) ListActiveByRule(ctx context.Context, arg ListActiveByRuleParams) ([]OperationalIncident, error) {
	rows, err := q.db.Query(ctx, listActiveByRule, arg.RuleKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationalIncident{}
	for rows.Next() {
		var i OperationalIncident
		if err := rows.Scan(
			&i.ID,
			&i.RuleKey,
			&i.SubjectType,
			&i.SubjectID,
			&i.Severity,
			&i.State,
			&i.Episode,
			&i.SourceEventKey,
			&i.OpenedAt,
			&i.LastObservedAt,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
			&i.ResolutionCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OpenIntentMaterialized,
			&i.ResolvedIntentMaterialized,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRecipients = `-- name: ListAlertRecipients :many
SELECT id, label, provider_key, recipient, locale, enabled, created_at, updated_at
FROM operational_alert_recipients
ORDER BY created_at, id
`

func (q *Queries) ListAlertRecipients(ctx context.Context) ([]OperationalAlertRecipient, error) {
	rows, err := q.db.Query(ctx, listAlertRecipients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationalAlertRecipient{}
	for rows.Next() {
		var i OperationalAlertRecipient
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.ProviderKey,
			&i.Recipient,
			&i.Locale,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesForIncident = `-- name: ListDeliveriesForIncident :many
SELECT d.id, d.incident_id, d.recipient_id, d.event_type, d.provider_key_snapshot, d.recipient_snapshot,
    d.locale_snapshot, d.template_key, d.body_snapshot, d.body_fingerprint, d.notification_id, d.notification_idempotency_key,
    d.status, d.last_error_code, d.created_at, d.updated_at,
    n.dispatch_status AS notification_dispatch, n.delivery_status AS notification_delivery
FROM operational_alert_deliveries d
LEFT JOIN notification_messages n ON n.id = d.notification_id
WHERE d.incident_id = $1
ORDER BY d.created_at, d.id
`

type ListDeliveriesForIncidentRow struct {
	ID                         pgtype.UUID        `json:"id"`
	IncidentID                 pgtype.UUID        `json:"incident_id"`
	RecipientID                pgtype.UUID        `json:"recipient_id"`
	EventType                  string             `json:"event_type"`
	ProviderKeySnapshot        string             `json:"provider_key_snapshot"`
	RecipientSnapshot          string             `json:"recipient_snapshot"`
	LocaleSnapshot             string             `json:"locale_snapshot"`
	TemplateKey                string             `json:"template_key"`
	BodySnapshot               string             `json:"body_snapshot"`
	BodyFingerprint            []byte             `json:"body_fingerprint"`
	NotificationID             pgtype.UUID        `json:"notification_id"`
	NotificationIdempotencyKey string             `json:"notification_idempotency_key"`
	Status                     string             `json:"status"`
	LastErrorCode              pgtype.Text        `json:"last_error_code"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	NotificationDispatch       pgtype.Text        `json:"notification_dispatch"`
	NotificationDelivery       pgtype.Text        `json:"notification_delivery"`
}

func (q *Queries) ListDeliveriesForIncident(ctx context.Context, incidentID pgtype.UUID) ([]ListDeliveriesForIncidentRow, error) {
	rows, err := q.db.Query(ctx, listDeliveriesForIncident, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveriesForIncidentRow{}
	for rows.Next() {
		var i ListDeliveriesForIncidentRow
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.RecipientID,
			&i.EventType,
			&i.ProviderKeySnapshot,
			&i.RecipientSnapshot,
			&i.LocaleSnapshot,
			&i.TemplateKey,
			&i.BodySnapshot,
			&i.BodyFingerprint,
			&i.NotificationID,
			&i.NotificationIdempotencyKey,
			&i.Status,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NotificationDispatch,
			&i.NotificationDelivery,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRecipients = `-- name: ListEnabledAlertRecipients :many
SELECT id, label, provider_key, recipient, locale, enabled, created_at, updated_at
FROM operational_alert_recipients
WHERE enabled
ORDER BY created_at, id
`

func (q *Queries) ListEnabledAlertRecipients(ctx context.Context) ([]OperationalAlertRecipient, error) {
	rows, err := q.db.Query(ctx, listEnabledAlertRecipients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationalAlertRecipient{}
	for rows.Next() {
		var i OperationalAlertRecipient
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.ProviderKey,
			&i.Recipient,
			&i.Locale,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsPage = `-- name: ListIncidentsPage :many
SELECT id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
FROM operational_incidents
WHERE ($1::text = '' OR state = $1::text)
  AND ($2::text = '' OR severity = $2::text)
  AND ($3::text = '' OR rule_key = $3::text)
  AND ($4::timestamptz IS NULL OR opened_at < $4::timestamptz OR (opened_at = $4::timestamptz AND id < $5::uuid))
ORDER BY opened_at DESC, id DESC
LIMIT $6
`

type ListIncidentsPageParams struct {
	Column1 string             `json:"column_1"`
	Column2 string             `json:"column_2"`
	Column3 string             `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Column5 pgtype.UUID        `json:"column_5"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) ListIncidentsPage(ctx context.Context, arg ListIncidentsPageParams) ([]OperationalIncident, error) {
	rows, err := q.db.Query(ctx, listIncidentsPage,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationalIncident{}
	for rows.Next() {
		var i OperationalIncident
		if err := rows.Scan(
			&i.ID,
			&i.RuleKey,
			&i.SubjectType,
			&i.SubjectID,
			&i.Severity,
			&i.State,
			&i.Episode,
			&i.SourceEventKey,
			&i.OpenedAt,
			&i.LastObservedAt,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
			&i.ResolutionCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OpenIntentMaterialized,
			&i.ResolvedIntentMaterialized,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoveryForIncident = `-- name: ListRecoveryForIncident :many
SELECT id, incident_id, action_type, state, idempotency_key, target_entity_id, result_code,
    attempt_count, next_attempt_at, last_error_code, created_at, updated_at
FROM operational_recovery_actions
WHERE incident_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListRecoveryForIncident(ctx context.Context, incidentID pgtype.UUID) ([]OperationalRecoveryAction, error) {
	rows, err := q.db.Query(ctx, listRecoveryForIncident, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationalRecoveryAction{}
	for rows.Next() {
		var i OperationalRecoveryAction
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.ActionType,
			&i.State,
			&i.IdempotencyKey,
			&i.TargetEntityID,
			&i.ResultCode,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCommandRow = `-- name: LockCommandRow :one
SELECT id FROM device_control_commands WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCommandRow(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockCommandRow, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockIncidentRow = `-- name: LockIncidentRow :one

SELECT id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
FROM operational_incidents
WHERE id = $1 FOR UPDATE
`

// Incident-row lock for guarded manual resolution. Lock ordering across
// the codebase is incident row first, predicate row second; no other
// path holds these locks in reverse order, so this cannot deadlock.
func (q *Queries) LockIncidentRow(ctx context.Context, id pgtype.UUID) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, lockIncidentRow, id)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const lockNotificationRow = `-- name: LockNotificationRow :one
SELECT id FROM notification_messages WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockNotificationRow(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockNotificationRow, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockPresenceRow = `-- name: LockPresenceRow :one

SELECT device_id FROM device_control_presence WHERE device_id = $1 FOR UPDATE
`

// Manual-resolution predicate locks: held for the duration of the
// guarded-resolve transaction so a concurrent predicate write cannot
// commit between validation and resolution. EvalPlanQual only rechecks
// when the incident row itself changes, so without these locks a
// predicate flip landing mid-flight would be invisible. Missing subject
// rows lock nothing (matching StillActive: absent reads as clear).
// Writers always touch these same rows, so lock ordering is consistent
// (predicate row, then incident row) and cannot deadlock against
// detector paths, which never take explicit row locks.
func (q *Queries) LockPresenceRow(ctx context.Context, deviceID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockPresenceRow, deviceID)
	var device_id pgtype.UUID
	err := row.Scan(&device_id)
	return device_id, err
}

const lockRunRow = `-- name: LockRunRow :one
SELECT id FROM business_report_runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockRunRow(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockRunRow, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const markOpenIntentMaterialized = `-- name: MarkOpenIntentMaterialized :execrows
UPDATE operational_incidents SET open_intent_materialized = TRUE, updated_at = $2 WHERE id = $1
`

type MarkOpenIntentMaterializedParams struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkOpenIntentMaterialized(ctx context.Context, arg MarkOpenIntentMaterializedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOpenIntentMaterialized, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markResolvedIntentMaterialized = `-- name: MarkResolvedIntentMaterialized :execrows
UPDATE operational_incidents SET resolved_intent_materialized = TRUE, updated_at = $2 WHERE id = $1
`

type MarkResolvedIntentMaterializedParams struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkResolvedIntentMaterialized(ctx context.Context, arg MarkResolvedIntentMaterializedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markResolvedIntentMaterialized, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const maxEpisodeForSubject = `-- name: MaxEpisodeForSubject :one
SELECT COALESCE(MAX(episode), 0)::INTEGER AS max_episode
FROM operational_incidents
WHERE rule_key = $1 AND subject_type = $2 AND subject_id = $3
`

type MaxEpisodeForSubjectParams struct {
	RuleKey     string `json:"rule_key"`
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
}

func (q *Queries) MaxEpisodeForSubject(ctx context.Context, arg MaxEpisodeForSubjectParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxEpisodeForSubject, arg.RuleKey, arg.SubjectType, arg.SubjectID)
	var max_episode int32
	err := row.Scan(&max_episode)
	return max_episode, err
}

const openEventIncident = `-- name: OpenEventIncident :one
INSERT INTO operational_incidents (id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key, opened_at, last_observed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 'open', 1, $6, $7, $7, $7, $7)
ON CONFLICT (source_event_key) WHERE source_event_key IS NOT NULL DO NOTHING
RETURNING id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
`

type OpenEventIncidentParams struct {
	ID             pgtype.UUID        `json:"id"`
	RuleKey        string             `json:"rule_key"`
	SubjectType    string             `json:"subject_type"`
	SubjectID      string             `json:"subject_id"`
	Severity       string             `json:"severity"`
	SourceEventKey pgtype.Text        `json:"source_event_key"`
	OpenedAt       pgtype.Timestamptz `json:"opened_at"`
}

func (q *Queries) OpenEventIncident(ctx context.Context, arg OpenEventIncidentParams) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, openEventIncident,
		arg.ID,
		arg.RuleKey,
		arg.SubjectType,
		arg.SubjectID,
		arg.Severity,
		arg.SourceEventKey,
		arg.OpenedAt,
	)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const openIncident = `-- name: OpenIncident :one
INSERT INTO operational_incidents (id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key, opened_at, last_observed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 'open', $6, $7, $8, $8, $8, $8)
ON CONFLICT (rule_key, subject_type, subject_id) WHERE state IN ('open', 'acknowledged') DO NOTHING
RETURNING id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
`

type OpenIncidentParams struct {
	ID             pgtype.UUID        `json:"id"`
	RuleKey        string             `json:"rule_key"`
	SubjectType    string             `json:"subject_type"`
	SubjectID      string             `json:"subject_id"`
	Severity       string             `json:"severity"`
	Episode        int32              `json:"episode"`
	SourceEventKey pgtype.Text        `json:"source_event_key"`
	OpenedAt       pgtype.Timestamptz `json:"opened_at"`
}

func (q *Queries) OpenIncident(ctx context.Context, arg OpenIncidentParams) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, openIncident,
		arg.ID,
		arg.RuleKey,
		arg.SubjectType,
		arg.SubjectID,
		arg.Severity,
		arg.Episode,
		arg.SourceEventKey,
		arg.OpenedAt,
	)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const opsPresence = `-- name: OpsPresence :one
SELECT last_seen_at
FROM device_control_presence
WHERE device_id = $1
`

func (q *Queries) OpsPresence(ctx context.Context, deviceID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, opsPresence, deviceID)
	var last_seen_at pgtype.Timestamptz
	err := row.Scan(&last_seen_at)
	return last_seen_at, err
}

const resolveIfNotificationClear = `-- name: ResolveIfNotificationClear :one
UPDATE operational_incidents i
SET state = 'resolved', resolved_at = $2, resolution_code = $3, updated_at = $2
WHERE i.id = $1 AND i.state IN ('open', 'acknowledged')
  AND NOT EXISTS (
    SELECT 1 FROM notification_messages n
    WHERE n.id = i.subject_id::uuid AND n.dispatch_status IN ('pending', 'retry'))
RETURNING id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
`

type ResolveIfNotificationClearParams struct {
	ID             pgtype.UUID        `json:"id"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	ResolutionCode pgtype.Text        `json:"resolution_code"`
}

func (q *Queries) ResolveIfNotificationClear(ctx context.Context, arg ResolveIfNotificationClearParams) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, resolveIfNotificationClear, arg.ID, arg.ResolvedAt, arg.ResolutionCode)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const resolveIfOfflineClear = `-- name: ResolveIfOfflineClear :one

UPDATE operational_incidents i
SET state = 'resolved', resolved_at = $3, resolution_code = $4, updated_at = $3
WHERE i.id = $1 AND i.state IN ('open', 'acknowledged')
  AND NOT EXISTS (
    SELECT 1 FROM device_control_presence p
    WHERE p.device_id = i.subject_id::uuid AND p.last_seen_at <= $2)
RETURNING id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
`

type ResolveIfOfflineClearParams struct {
	ID             pgtype.UUID        `json:"id"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	ResolutionCode pgtype.Text        `json:"resolution_code"`
}

// Manual-resolution guarded transitions (single statement each): the
// resolve commits only when the stateful predicate currently reads
// clear, closing the check/write race. Callers distinguish "already
// resolved" (no-op success) from "still active" (409) by re-reading.
// Subject IDs are UUIDs; callers pre-validate and fail closed otherwise.
func (q *Queries) ResolveIfOfflineClear(ctx context.Context, arg ResolveIfOfflineClearParams) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, resolveIfOfflineClear,
		arg.ID,
		arg.LastSeenAt,
		arg.ResolvedAt,
		arg.ResolutionCode,
	)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const resolveIfReportClear = `-- name: ResolveIfReportClear :one
UPDATE operational_incidents i
SET state = 'resolved', resolved_at = $2, resolution_code = $3, updated_at = $2
WHERE i.id = $1 AND i.state IN ('open', 'acknowledged')
  AND NOT EXISTS (
    SELECT 1 FROM business_report_runs r
    WHERE r.id = i.subject_id::uuid AND r.status IN ('pending', 'retry'))
RETURNING id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
`

type ResolveIfReportClearParams struct {
	ID             pgtype.UUID        `json:"id"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	ResolutionCode pgtype.Text        `json:"resolution_code"`
}

func (q *Queries) ResolveIfReportClear(ctx context.Context, arg ResolveIfReportClearParams) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, resolveIfReportClear, arg.ID, arg.ResolvedAt, arg.ResolutionCode)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const resolveIfSyncClear = `-- name: ResolveIfSyncClear :one
UPDATE operational_incidents i
SET state = 'resolved', resolved_at = $2, resolution_code = $3, updated_at = $2
WHERE i.id = $1 AND i.state IN ('open', 'acknowledged')
  AND NOT EXISTS (
    SELECT 1 FROM device_control_commands c
    WHERE c.id = i.subject_id::uuid AND c.status NOT IN ('completed', 'failed'))
RETURNING id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
`

type ResolveIfSyncClearParams struct {
	ID             pgtype.UUID        `json:"id"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	ResolutionCode pgtype.Text        `json:"resolution_code"`
}

func (q *Queries) ResolveIfSyncClear(ctx context.Context, arg ResolveIfSyncClearParams) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, resolveIfSyncClear, arg.ID, arg.ResolvedAt, arg.ResolutionCode)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const resolveIncident = `-- name: ResolveIncident :one
UPDATE operational_incidents
SET state = 'resolved', resolved_at = $2, resolution_code = $3, updated_at = $2
WHERE id = $1 AND state IN ('open', 'acknowledged')
RETURNING id, rule_key, subject_type, subject_id, severity, state, episode, source_event_key,
    opened_at, last_observed_at, acknowledged_at, resolved_at, resolution_code, created_at, updated_at, open_intent_materialized, resolved_intent_materialized
`

type ResolveIncidentParams struct {
	ID             pgtype.UUID        `json:"id"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	ResolutionCode pgtype.Text        `json:"resolution_code"`
}

func (q *Queries) ResolveIncident(ctx context.Context, arg ResolveIncidentParams) (OperationalIncident, error) {
	row := q.db.QueryRow(ctx, resolveIncident, arg.ID, arg.ResolvedAt, arg.ResolutionCode)
	var i OperationalIncident
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.SubjectType,
		&i.SubjectID,
		&i.Severity,
		&i.State,
		&i.Episode,
		&i.SourceEventKey,
		&i.OpenedAt,
		&i.LastObservedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.ResolutionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenIntentMaterialized,
		&i.ResolvedIntentMaterialized,
	)
	return i, err
}

const retryRecoveryLater = `-- name: RetryRecoveryLater :execrows
UPDATE operational_recovery_actions
SET attempt_count = attempt_count + 1, next_attempt_at = $2, last_error_code = $3, updated_at = $4
WHERE id = $1 AND state = 'pending'
`

type RetryRecoveryLaterParams struct {
	ID            pgtype.UUID        `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RetryRecoveryLater(ctx context.Context, arg RetryRecoveryLaterParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryRecoveryLater,
		arg.ID,
		arg.NextAttemptAt,
		arg.LastErrorCode,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scanAmbiguousNotifications = `-- name: ScanAmbiguousNotifications :many
SELECT id, template_key, locale, created_at
FROM notification_messages
WHERE dispatch_status = 'ambiguous'
  AND idempotency_key NOT LIKE 'ops-alert:%'
  AND template_key NOT LIKE 'operational\_alert\_%'
  AND NOT EXISTS (
    SELECT 1 FROM operational_incidents i
    WHERE i.source_event_key = 'notification-ambiguous:' || notification_messages.id::text)
ORDER BY notification_messages.created_at, notification_messages.id
LIMIT $1
`

type ScanAmbiguousNotificationsRow struct {
	ID          pgtype.UUID        `json:"id"`
	TemplateKey string             `json:"template_key"`
	Locale      string             `json:"locale"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ScanAmbiguousNotifications(ctx context.Context, limit int32) ([]ScanAmbiguousNotificationsRow, error) {
	rows, err := q.db.Query(ctx, scanAmbiguousNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanAmbiguousNotificationsRow{}
	for rows.Next() {
		var i ScanAmbiguousNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateKey,
			&i.Locale,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanBlockedNotifications = `-- name: ScanBlockedNotifications :many
SELECT id, template_key, locale, created_at
FROM notification_messages
WHERE dispatch_status = 'blocked'
  AND idempotency_key NOT LIKE 'ops-alert:%'
  AND template_key NOT LIKE 'operational\_alert\_%'
  AND NOT EXISTS (
    SELECT 1 FROM operational_incidents i
    WHERE i.source_event_key = 'notification-blocked:' || notification_messages.id::text)
ORDER BY notification_messages.created_at, notification_messages.id
LIMIT $1
`

type ScanBlockedNotificationsRow struct {
	ID          pgtype.UUID        `json:"id"`
	TemplateKey string             `json:"template_key"`
	Locale      string             `json:"locale"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ScanBlockedNotifications(ctx context.Context, limit int32) ([]ScanBlockedNotificationsRow, error) {
	rows, err := q.db.Query(ctx, scanBlockedNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanBlockedNotificationsRow{}
	for rows.Next() {
		var i ScanBlockedNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateKey,
			&i.Locale,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanBlockedRuns = `-- name: ScanBlockedRuns :many
SELECT id, schedule_id, run_kind, slot_local_date, created_at
FROM business_report_runs
WHERE status = 'blocked'
  AND NOT EXISTS (
    SELECT 1 FROM operational_incidents i
    WHERE i.source_event_key = 'report-blocked:' || business_report_runs.id::text)
ORDER BY business_report_runs.created_at, business_report_runs.id
LIMIT $1
`

type ScanBlockedRunsRow struct {
	ID            pgtype.UUID        `json:"id"`
	ScheduleID    pgtype.UUID        `json:"schedule_id"`
	RunKind       string             `json:"run_kind"`
	SlotLocalDate pgtype.Date        `json:"slot_local_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ScanBlockedRuns(ctx context.Context, limit int32) ([]ScanBlockedRunsRow, error) {
	rows, err := q.db.Query(ctx, scanBlockedRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanBlockedRunsRow{}
	for rows.Next() {
		var i ScanBlockedRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.RunKind,
			&i.SlotLocalDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanFailedCommands = `-- name: ScanFailedCommands :many
SELECT id, device_id, command_type, command_version, result_code, finished_at
FROM device_control_commands
WHERE status = 'failed'
  AND NOT EXISTS (
    SELECT 1 FROM operational_incidents i
    WHERE i.source_event_key = 'sync-command:' || device_control_commands.id::text)
ORDER BY device_control_commands.finished_at, device_control_commands.id
LIMIT $1
`

type ScanFailedCommandsRow struct {
	ID             pgtype.UUID        `json:"id"`
	DeviceID       pgtype.UUID        `json:"device_id"`
	CommandType    string             `json:"command_type"`
	CommandVersion int32              `json:"command_version"`
	ResultCode     pgtype.Text        `json:"result_code"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) ScanFailedCommands(ctx context.Context, limit int32) ([]ScanFailedCommandsRow, error) {
	rows, err := q.db.Query(ctx, scanFailedCommands, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanFailedCommandsRow{}
	for rows.Next() {
		var i ScanFailedCommandsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.CommandType,
			&i.CommandVersion,
			&i.ResultCode,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanOfflineDevices = `-- name: ScanOfflineDevices :many

SELECT d.id, d.name, d.status, p.last_seen_at
FROM devices d
JOIN device_control_presence p ON p.device_id = d.id
WHERE d.status = 'active'
  AND p.last_seen_at IS NOT NULL
  AND p.last_seen_at < $1
  AND NOT EXISTS (
    SELECT 1 FROM operational_incidents i
    WHERE i.rule_key = 'DEVICE_OFFLINE' AND i.subject_type = 'device'
      AND i.subject_id = d.id::text AND i.state IN ('open', 'acknowledged'))
ORDER BY p.last_seen_at, d.id
LIMIT $2
`

type ScanOfflineDevicesParams struct {
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	Limit      int32              `json:"limit"`
}

type ScanOfflineDevicesRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

// Detector scans: bounded, indexed, server-time based. ----------
func (q *Queries) ScanOfflineDevices(ctx context.Context, arg ScanOfflineDevicesParams) ([]ScanOfflineDevicesRow, error) {
	rows, err := q.db.Query(ctx, scanOfflineDevices, arg.LastSeenAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanOfflineDevicesRow{}
	for rows.Next() {
		var i ScanOfflineDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanRetryStaleNotifications = `-- name: ScanRetryStaleNotifications :many
SELECT id, template_key, locale, created_at
FROM notification_messages
WHERE dispatch_status = 'retry'
  AND notification_messages.created_at < $1
  AND idempotency_key NOT LIKE 'ops-alert:%'
  AND template_key NOT LIKE 'operational\_alert\_%'
  AND NOT EXISTS (
    SELECT 1 FROM operational_incidents i
    WHERE i.rule_key = 'NOTIFICATION_RETRY_STALE' AND i.subject_type = 'notification'
      AND i.subject_id = notification_messages.id::text AND i.state IN ('open', 'acknowledged'))
ORDER BY notification_messages.created_at, notification_messages.id
LIMIT $2
`

type ScanRetryStaleNotificationsParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

type ScanRetryStaleNotificationsRow struct {
	ID          pgtype.UUID        `json:"id"`
	TemplateKey string             `json:"template_key"`
	Locale      string             `json:"locale"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ScanRetryStaleNotifications(ctx context.Context, arg ScanRetryStaleNotificationsParams) ([]ScanRetryStaleNotificationsRow, error) {
	rows, err := q.db.Query(ctx, scanRetryStaleNotifications, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanRetryStaleNotificationsRow{}
	for rows.Next() {
		var i ScanRetryStaleNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateKey,
			&i.Locale,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanStaleCommands = `-- name: ScanStaleCommands :many
SELECT id, device_id, command_type, command_version, status, requested_at
FROM device_control_commands
WHERE ((status = 'pending' AND requested_at < $1)
   OR (status IN ('leased', 'accepted', 'running') AND requested_at < $2))
  AND NOT EXISTS (
    SELECT 1 FROM operational_incidents i
    WHERE i.rule_key = 'DEVICE_SYNC_STALE' AND i.subject_type = 'sync_command'
      AND i.subject_id = device_control_commands.id::text AND i.state IN ('open', 'acknowledged'))
ORDER BY device_control_commands.requested_at, device_control_commands.id
LIMIT $3
`

type ScanStaleCommandsParams struct {
	RequestedAt   pgtype.Timestamptz `json:"requested_at"`
	RequestedAt_2 pgtype.Timestamptz `json:"requested_at_2"`
	Limit         int32              `json:"limit"`
}

type ScanStaleCommandsRow struct {
	ID             pgtype.UUID        `json:"id"`
	DeviceID       pgtype.UUID        `json:"device_id"`
	CommandType    string             `json:"command_type"`
	CommandVersion int32              `json:"command_version"`
	Status         string             `json:"status"`
	RequestedAt    pgtype.Timestamptz `json:"requested_at"`
}

func (q *Queries) ScanStaleCommands(ctx context.Context, arg ScanStaleCommandsParams) ([]ScanStaleCommandsRow, error) {
	rows, err := q.db.Query(ctx, scanStaleCommands, arg.RequestedAt, arg.RequestedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanStaleCommandsRow{}
	for rows.Next() {
		var i ScanStaleCommandsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.CommandType,
			&i.CommandVersion,
			&i.Status,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanStaleRuns = `-- name: ScanStaleRuns :many
SELECT id, schedule_id, run_kind, slot_local_date, status, created_at
FROM business_report_runs
WHERE status IN ('pending', 'retry')
  AND business_report_runs.created_at < $1
  AND NOT EXISTS (
    SELECT 1 FROM operational_incidents i
    WHERE i.rule_key = 'BUSINESS_REPORT_STALE' AND i.subject_type = 'report_run'
      AND i.subject_id = business_report_runs.id::text AND i.state IN ('open', 'acknowledged'))
ORDER BY business_report_runs.created_at, business_report_runs.id
LIMIT $2
`

type ScanStaleRunsParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

type ScanStaleRunsRow struct {
	ID            pgtype.UUID        `json:"id"`
	ScheduleID    pgtype.UUID        `json:"schedule_id"`
	RunKind       string             `json:"run_kind"`
	SlotLocalDate pgtype.Date        `json:"slot_local_date"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ScanStaleRuns(ctx context.Context, arg ScanStaleRunsParams) ([]ScanStaleRunsRow, error) {
	rows, err := q.db.Query(ctx, scanStaleRuns, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanStaleRunsRow{}
	for rows.Next() {
		var i ScanStaleRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.RunKind,
			&i.SlotLocalDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchIncidentObserved = `-- name: TouchIncidentObserved :execrows
UPDATE operational_incidents SET last_observed_at = $2, updated_at = $2
WHERE id = $1 AND state IN ('open', 'acknowledged')
`

type TouchIncidentObservedParams struct {
	ID             pgtype.UUID        `json:"id"`
	LastObservedAt pgtype.Timestamptz `json:"last_observed_at"`
}

func (q *Queries) TouchIncidentObserved(ctx context.Context, arg TouchIncidentObservedParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchIncidentObserved, arg.ID, arg.LastObservedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
