// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reportFreshness = `-- name: ReportFreshness :one
SELECT
    (SELECT max(received_at)::timestamptz FROM sync_events WHERE event_type = 'sale.finalized.v1') AS latest_received,
    (SELECT max(occurred_at)::timestamptz FROM sales_projection) AS latest_occurred,
    (SELECT count(*) FROM sync_events e WHERE e.event_type = 'sale.finalized.v1'
        AND NOT EXISTS (SELECT 1 FROM sync_event_processing p
            WHERE p.event_id = e.event_id AND p.processor = $1::text
              AND p.status IN ('processed', 'blocked'))) AS backlog,
    (SELECT count(*) FROM sync_event_processing
        WHERE processor = $1::text AND status = 'blocked') AS blocked
`

type ReportFreshnessRow struct {
	LatestReceived pgtype.Timestamptz `json:"latest_received"`
	LatestOccurred pgtype.Timestamptz `json:"latest_occurred"`
	Backlog        int64              `json:"backlog"`
	Blocked        int64              `json:"blocked"`
}

func (q *Queries) ReportFreshness(ctx context.Context, processor string) (ReportFreshnessRow, error) {
	row := q.db.QueryRow(ctx, reportFreshness, processor)
	var i ReportFreshnessRow
	err := row.Scan(
		&i.LatestReceived,
		&i.LatestOccurred,
		&i.Backlog,
		&i.Blocked,
	)
	return i, err
}

const reportSalesByCashier = `-- name: ReportSalesByCashier :many
SELECT s.cashier_id, s.cashier_name, s.currency,
    count(*)::bigint AS transactions,
    COALESCE(SUM(s.subtotal_minor), 0)::bigint AS subtotal,
    COALESCE(SUM(s.discount_minor), 0)::bigint AS discount,
    COALESCE(SUM(s.tax_minor), 0)::bigint AS tax,
    COALESCE(SUM(s.total_minor), 0)::bigint AS sales_total,
    COALESCE(SUM(l.units), 0)::bigint AS units
FROM sales_projection s
LEFT JOIN (
    SELECT sale_id, COALESCE(SUM(quantity), 0)::bigint AS units
    FROM sale_lines_projection
    GROUP BY sale_id
) l ON l.sale_id = s.sale_id
WHERE s.occurred_at >= $1 AND s.occurred_at < $2
  AND ($3::text = '' OR s.currency = $3::text)
GROUP BY s.cashier_id, s.cashier_name, s.currency
`

type ReportSalesByCashierParams struct {
	StartUtc pgtype.Timestamptz `json:"start_utc"`
	EndUtc   pgtype.Timestamptz `json:"end_utc"`
	Currency string             `json:"currency"`
}

type ReportSalesByCashierRow struct {
	CashierID    pgtype.Text `json:"cashier_id"`
	CashierName  pgtype.Text `json:"cashier_name"`
	Currency     string      `json:"currency"`
	Transactions int64       `json:"transactions"`
	Subtotal     int64       `json:"subtotal"`
	Discount     int64       `json:"discount"`
	Tax          int64       `json:"tax"`
	SalesTotal   int64       `json:"sales_total"`
	Units        int64       `json:"units"`
}

func (q *Queries) ReportSalesByCashier(ctx context.Context, arg ReportSalesByCashierParams) ([]ReportSalesByCashierRow, error) {
	rows, err := q.db.Query(ctx, reportSalesByCashier, arg.StartUtc, arg.EndUtc, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSalesByCashierRow{}
	for rows.Next() {
		var i ReportSalesByCashierRow
		if err := rows.Scan(
			&i.CashierID,
			&i.CashierName,
			&i.Currency,
			&i.Transactions,
			&i.Subtotal,
			&i.Discount,
			&i.Tax,
			&i.SalesTotal,
			&i.Units,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSalesByCategory = `-- name: ReportSalesByCategory :many
SELECT c.classification_kind AS kind, c.classification_id AS id,
    c.name_ar, c.name_en, l.line_currency AS currency,
    COALESCE(SUM(l.quantity), 0)::bigint AS units,
    COALESCE(SUM(l.line_total_minor), 0)::bigint AS sales,
    COALESCE(SUM(l.cost_minor), 0)::bigint AS cost
FROM sale_line_classifications_projection c
JOIN sale_lines_projection l
  ON l.sale_id = c.sale_id AND l.sale_item_id = c.sale_item_id
JOIN sales_projection s ON s.sale_id = c.sale_id
WHERE s.occurred_at >= $1 AND s.occurred_at < $2
  AND c.classification_kind = $3::text
  AND ($4::text = '' OR l.line_currency = $4::text)
GROUP BY c.classification_kind, c.classification_id, c.name_ar, c.name_en, l.line_currency
`

type ReportSalesByCategoryParams struct {
	StartUtc pgtype.Timestamptz `json:"start_utc"`
	EndUtc   pgtype.Timestamptz `json:"end_utc"`
	Kind     string             `json:"kind"`
	Currency string             `json:"currency"`
}

type ReportSalesByCategoryRow struct {
	Kind     string      `json:"kind"`
	ID       pgtype.UUID `json:"id"`
	NameAr   string      `json:"name_ar"`
	NameEn   string      `json:"name_en"`
	Currency string      `json:"currency"`
	Units    int64       `json:"units"`
	Sales    int64       `json:"sales"`
	Cost     int64       `json:"cost"`
}

func (q *Queries) ReportSalesByCategory(ctx context.Context, arg ReportSalesByCategoryParams) ([]ReportSalesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, reportSalesByCategory,
		arg.StartUtc,
		arg.EndUtc,
		arg.Kind,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSalesByCategoryRow{}
	for rows.Next() {
		var i ReportSalesByCategoryRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.NameAr,
			&i.NameEn,
			&i.Currency,
			&i.Units,
			&i.Sales,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSalesByChannel = `-- name: ReportSalesByChannel :many
SELECT s.channel, s.currency,
    count(*)::bigint AS transactions,
    COALESCE(SUM(s.subtotal_minor), 0)::bigint AS subtotal,
    COALESCE(SUM(s.discount_minor), 0)::bigint AS discount,
    COALESCE(SUM(s.tax_minor), 0)::bigint AS tax,
    COALESCE(SUM(s.total_minor), 0)::bigint AS sales_total,
    COALESCE(SUM(l.units), 0)::bigint AS units
FROM sales_projection s
LEFT JOIN (
    SELECT sale_id, COALESCE(SUM(quantity), 0)::bigint AS units
    FROM sale_lines_projection
    GROUP BY sale_id
) l ON l.sale_id = s.sale_id
WHERE s.occurred_at >= $1 AND s.occurred_at < $2
  AND ($3::text = '' OR s.currency = $3::text)
GROUP BY s.channel, s.currency
`

type ReportSalesByChannelParams struct {
	StartUtc pgtype.Timestamptz `json:"start_utc"`
	EndUtc   pgtype.Timestamptz `json:"end_utc"`
	Currency string             `json:"currency"`
}

type ReportSalesByChannelRow struct {
	Channel      string `json:"channel"`
	Currency     string `json:"currency"`
	Transactions int64  `json:"transactions"`
	Subtotal     int64  `json:"subtotal"`
	Discount     int64  `json:"discount"`
	Tax          int64  `json:"tax"`
	SalesTotal   int64  `json:"sales_total"`
	Units        int64  `json:"units"`
}

func (q *Queries) ReportSalesByChannel(ctx context.Context, arg ReportSalesByChannelParams) ([]ReportSalesByChannelRow, error) {
	rows, err := q.db.Query(ctx, reportSalesByChannel, arg.StartUtc, arg.EndUtc, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSalesByChannelRow{}
	for rows.Next() {
		var i ReportSalesByChannelRow
		if err := rows.Scan(
			&i.Channel,
			&i.Currency,
			&i.Transactions,
			&i.Subtotal,
			&i.Discount,
			&i.Tax,
			&i.SalesTotal,
			&i.Units,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSalesByProduct = `-- name: ReportSalesByProduct :many
SELECT l.product_id, l.sku, l.product_name, l.line_currency AS currency,
    COALESCE(SUM(l.quantity), 0)::bigint AS units,
    COALESCE(SUM(l.line_total_minor), 0)::bigint AS line_sales,
    COALESCE(SUM(l.cost_minor), 0)::bigint AS line_cost
FROM sale_lines_projection l
JOIN sales_projection s ON s.sale_id = l.sale_id
WHERE s.occurred_at >= $1 AND s.occurred_at < $2
  AND ($3::text = '' OR l.line_currency = $3::text)
GROUP BY l.product_id, l.sku, l.product_name, l.line_currency
`

type ReportSalesByProductParams struct {
	StartUtc pgtype.Timestamptz `json:"start_utc"`
	EndUtc   pgtype.Timestamptz `json:"end_utc"`
	Currency string             `json:"currency"`
}

type ReportSalesByProductRow struct {
	ProductID   pgtype.UUID `json:"product_id"`
	Sku         string      `json:"sku"`
	ProductName string      `json:"product_name"`
	Currency    string      `json:"currency"`
	Units       int64       `json:"units"`
	LineSales   int64       `json:"line_sales"`
	LineCost    int64       `json:"line_cost"`
}

func (q *Queries) ReportSalesByProduct(ctx context.Context, arg ReportSalesByProductParams) ([]ReportSalesByProductRow, error) {
	rows, err := q.db.Query(ctx, reportSalesByProduct, arg.StartUtc, arg.EndUtc, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSalesByProductRow{}
	for rows.Next() {
		var i ReportSalesByProductRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Sku,
			&i.ProductName,
			&i.Currency,
			&i.Units,
			&i.LineSales,
			&i.LineCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSalesDaily = `-- name: ReportSalesDaily :many
SELECT ((s.occurred_at AT TIME ZONE $1::text)::date)::text AS day,
    s.currency,
    count(*)::bigint AS transactions,
    COALESCE(SUM(s.subtotal_minor), 0)::bigint AS subtotal,
    COALESCE(SUM(s.discount_minor), 0)::bigint AS discount,
    COALESCE(SUM(s.tax_minor), 0)::bigint AS tax,
    COALESCE(SUM(s.total_minor), 0)::bigint AS sales_total,
    COALESCE(SUM(l.units), 0)::bigint AS units,
    COALESCE(SUM(l.cost), 0)::bigint AS line_cost
FROM sales_projection s
LEFT JOIN (
    SELECT sale_id,
        COALESCE(SUM(quantity), 0)::bigint AS units,
        COALESCE(SUM(cost_minor), 0)::bigint AS cost
    FROM sale_lines_projection
    GROUP BY sale_id
) l ON l.sale_id = s.sale_id
WHERE s.occurred_at >= $2 AND s.occurred_at < $3
  AND ($4::text = '' OR s.currency = $4::text)
GROUP BY 1, s.currency
ORDER BY 1, s.currency
`

type ReportSalesDailyParams struct {
	Timezone string             `json:"timezone"`
	StartUtc pgtype.Timestamptz `json:"start_utc"`
	EndUtc   pgtype.Timestamptz `json:"end_utc"`
	Currency string             `json:"currency"`
}

type ReportSalesDailyRow struct {
	Day          string `json:"day"`
	Currency     string `json:"currency"`
	Transactions int64  `json:"transactions"`
	Subtotal     int64  `json:"subtotal"`
	Discount     int64  `json:"discount"`
	Tax          int64  `json:"tax"`
	SalesTotal   int64  `json:"sales_total"`
	Units        int64  `json:"units"`
	LineCost     int64  `json:"line_cost"`
}

func (q *Queries) ReportSalesDaily(ctx context.Context, arg ReportSalesDailyParams) ([]ReportSalesDailyRow, error) {
	rows, err := q.db.Query(ctx, reportSalesDaily,
		arg.Timezone,
		arg.StartUtc,
		arg.EndUtc,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSalesDailyRow{}
	for rows.Next() {
		var i ReportSalesDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.Currency,
			&i.Transactions,
			&i.Subtotal,
			&i.Discount,
			&i.Tax,
			&i.SalesTotal,
			&i.Units,
			&i.LineCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSalesPayments = `-- name: ReportSalesPayments :many
SELECT p.method, p.amount_currency AS currency,
    COALESCE(SUM(p.amount_minor), 0)::bigint AS amount,
    COALESCE(SUM(p.change_minor), 0)::bigint AS change
FROM sale_payments_projection p
JOIN sales_projection s ON s.sale_id = p.sale_id
WHERE s.occurred_at >= $1 AND s.occurred_at < $2
  AND ($3::text = '' OR p.amount_currency = $3::text)
GROUP BY p.method, p.amount_currency
ORDER BY p.method, p.amount_currency
`

type ReportSalesPaymentsParams struct {
	StartUtc pgtype.Timestamptz `json:"start_utc"`
	EndUtc   pgtype.Timestamptz `json:"end_utc"`
	Currency string             `json:"currency"`
}

type ReportSalesPaymentsRow struct {
	Method   string `json:"method"`
	Currency string `json:"currency"`
	Amount   int64  `json:"amount"`
	Change   int64  `json:"change"`
}

func (q *Queries) ReportSalesPayments(ctx context.Context, arg ReportSalesPaymentsParams) ([]ReportSalesPaymentsRow, error) {
	rows, err := q.db.Query(ctx, reportSalesPayments, arg.StartUtc, arg.EndUtc, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSalesPaymentsRow{}
	for rows.Next() {
		var i ReportSalesPaymentsRow
		if err := rows.Scan(
			&i.Method,
			&i.Currency,
			&i.Amount,
			&i.Change,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSalesSummary = `-- name: ReportSalesSummary :many

SELECT s.currency,
    count(*)::bigint AS transactions,
    COALESCE(SUM(s.subtotal_minor), 0)::bigint AS subtotal,
    COALESCE(SUM(s.discount_minor), 0)::bigint AS discount,
    COALESCE(SUM(s.tax_minor), 0)::bigint AS tax,
    COALESCE(SUM(s.total_minor), 0)::bigint AS sales_total,
    COALESCE(SUM(l.units), 0)::bigint AS units,
    COALESCE(SUM(l.cost), 0)::bigint AS line_cost
FROM sales_projection s
LEFT JOIN (
    SELECT sale_id,
        COALESCE(SUM(quantity), 0)::bigint AS units,
        COALESCE(SUM(cost_minor), 0)::bigint AS cost
    FROM sale_lines_projection
    GROUP BY sale_id
) l ON l.sale_id = s.sale_id
WHERE s.occurred_at >= $1 AND s.occurred_at < $2
  AND ($3::text = '' OR s.currency = $3::text)
GROUP BY s.currency
ORDER BY s.currency
`

type ReportSalesSummaryParams struct {
	StartUtc pgtype.Timestamptz `json:"start_utc"`
	EndUtc   pgtype.Timestamptz `json:"end_utc"`
	Currency string             `json:"currency"`
}

type ReportSalesSummaryRow struct {
	Currency     string `json:"currency"`
	Transactions int64  `json:"transactions"`
	Subtotal     int64  `json:"subtotal"`
	Discount     int64  `json:"discount"`
	Tax          int64  `json:"tax"`
	SalesTotal   int64  `json:"sales_total"`
	Units        int64  `json:"units"`
	LineCost     int64  `json:"line_cost"`
}

// Reporting queries (Phase 3A). Read-only aggregates over the frozen
// sale.finalized.v1 projection. Every time filter is the half-open window
// [start, end) on sales_projection.occurred_at (business time, never
// transport time). Money aggregates cast numeric SUM to bigint so overflow
// fails explicitly instead of wrapping or floating. No dynamic SQL: one
// static query per report need; currency ” means all currencies (bucketed,
// never summed across currencies).
func (q *Queries) ReportSalesSummary(ctx context.Context, arg ReportSalesSummaryParams) ([]ReportSalesSummaryRow, error) {
	rows, err := q.db.Query(ctx, reportSalesSummary, arg.StartUtc, arg.EndUtc, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSalesSummaryRow{}
	for rows.Next() {
		var i ReportSalesSummaryRow
		if err := rows.Scan(
			&i.Currency,
			&i.Transactions,
			&i.Subtotal,
			&i.Discount,
			&i.Tax,
			&i.SalesTotal,
			&i.Units,
			&i.LineCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
