// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: return_projection.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cumulativeRefundedForSale = `-- name: CumulativeRefundedForSale :one
SELECT COALESCE(SUM(l.refund_minor), 0)::bigint AS total
FROM return_refund_lines_projection l
JOIN return_refund_projection r ON r.return_refund_id = l.return_refund_id
WHERE r.sale_id = $1
`

// Sum of authoritative line refunds already committed for one sale, for the
// cumulative-refund guard (telescoping-exact under frozen allocation:
// partial sums never exceed the sale total).
func (q *Queries) CumulativeRefundedForSale(ctx context.Context, saleID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, cumulativeRefundedForSale, saleID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const cumulativeReturnedQty = `-- name: CumulativeReturnedQty :one
SELECT COALESCE(SUM(quantity), 0)::bigint AS total
FROM return_refund_lines_projection
WHERE sale_id = $1 AND original_sale_line_id = $2
`

type CumulativeReturnedQtyParams struct {
	SaleID             pgtype.UUID `json:"sale_id"`
	OriginalSaleLineID pgtype.UUID `json:"original_sale_line_id"`
}

// Committed authoritative returns only: projection rows exist solely for
// ownership winners (rivals are blocked before writing), so no ownership
// join is needed.
func (q *Queries) CumulativeReturnedQty(ctx context.Context, arg CumulativeReturnedQtyParams) (int64, error) {
	row := q.db.QueryRow(ctx, cumulativeReturnedQty, arg.SaleID, arg.OriginalSaleLineID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const insertReturnLine = `-- name: InsertReturnLine :exec
INSERT INTO return_refund_lines_projection (
    return_refund_id, sale_id, original_sale_line_id, position, product_id,
    quantity, restocked,
    gross_minor, gross_currency, discount_minor, discount_currency,
    tax_minor, tax_currency, refund_minor, refund_currency,
    cost_minor, cost_currency
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
ON CONFLICT (return_refund_id, original_sale_line_id) DO NOTHING
`

type InsertReturnLineParams struct {
	ReturnRefundID     pgtype.UUID `json:"return_refund_id"`
	SaleID             pgtype.UUID `json:"sale_id"`
	OriginalSaleLineID pgtype.UUID `json:"original_sale_line_id"`
	Position           int32       `json:"position"`
	ProductID          pgtype.UUID `json:"product_id"`
	Quantity           int32       `json:"quantity"`
	Restocked          bool        `json:"restocked"`
	GrossMinor         int64       `json:"gross_minor"`
	GrossCurrency      string      `json:"gross_currency"`
	DiscountMinor      int64       `json:"discount_minor"`
	DiscountCurrency   string      `json:"discount_currency"`
	TaxMinor           int64       `json:"tax_minor"`
	TaxCurrency        string      `json:"tax_currency"`
	RefundMinor        int64       `json:"refund_minor"`
	RefundCurrency     string      `json:"refund_currency"`
	CostMinor          pgtype.Int8 `json:"cost_minor"`
	CostCurrency       pgtype.Text `json:"cost_currency"`
}

func (q *Queries) InsertReturnLine(ctx context.Context, arg InsertReturnLineParams) error {
	_, err := q.db.Exec(ctx, insertReturnLine,
		arg.ReturnRefundID,
		arg.SaleID,
		arg.OriginalSaleLineID,
		arg.Position,
		arg.ProductID,
		arg.Quantity,
		arg.Restocked,
		arg.GrossMinor,
		arg.GrossCurrency,
		arg.DiscountMinor,
		arg.DiscountCurrency,
		arg.TaxMinor,
		arg.TaxCurrency,
		arg.RefundMinor,
		arg.RefundCurrency,
		arg.CostMinor,
		arg.CostCurrency,
	)
	return err
}

const insertReturnPayment = `-- name: InsertReturnPayment :exec
INSERT INTO return_refund_payments_projection (
    return_refund_id, position, method, amount_minor, amount_currency,
    transaction_ref
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (return_refund_id, position) DO NOTHING
`

type InsertReturnPaymentParams struct {
	ReturnRefundID pgtype.UUID `json:"return_refund_id"`
	Position       int32       `json:"position"`
	Method         string      `json:"method"`
	AmountMinor    int64       `json:"amount_minor"`
	AmountCurrency string      `json:"amount_currency"`
	TransactionRef pgtype.Text `json:"transaction_ref"`
}

func (q *Queries) InsertReturnPayment(ctx context.Context, arg InsertReturnPaymentParams) error {
	_, err := q.db.Exec(ctx, insertReturnPayment,
		arg.ReturnRefundID,
		arg.Position,
		arg.Method,
		arg.AmountMinor,
		arg.AmountCurrency,
		arg.TransactionRef,
	)
	return err
}

const insertReturnProjection = `-- name: InsertReturnProjection :one
INSERT INTO return_refund_projection (
    return_refund_id, source_event_id, source_device_id, return_number, kind,
    reason, note, sale_id, sale_number, sale_event_id, channel,
    occurred_at, currency,
    gross_refunded_minor, discount_refunded_minor, tax_refunded_minor, refund_total_minor,
    fx_base, fx_quote, fx_rate, fx_rate_microrate,
    shop_name_ar, shop_name_en, shop_address_ar, shop_address_en, shop_phone,
    shop_receipt_footer_ar, shop_receipt_footer_en,
    actor_user_id, actor_user_name,
    received_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25,
    $26, $27, $28, $29, $30, $31
)
ON CONFLICT (return_refund_id) DO NOTHING
RETURNING return_refund_id, source_event_id
`

type InsertReturnProjectionParams struct {
	ReturnRefundID        pgtype.UUID        `json:"return_refund_id"`
	SourceEventID         pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID        pgtype.UUID        `json:"source_device_id"`
	ReturnNumber          string             `json:"return_number"`
	Kind                  string             `json:"kind"`
	Reason                string             `json:"reason"`
	Note                  pgtype.Text        `json:"note"`
	SaleID                pgtype.UUID        `json:"sale_id"`
	SaleNumber            string             `json:"sale_number"`
	SaleEventID           pgtype.UUID        `json:"sale_event_id"`
	Channel               string             `json:"channel"`
	OccurredAt            pgtype.Timestamptz `json:"occurred_at"`
	Currency              string             `json:"currency"`
	GrossRefundedMinor    int64              `json:"gross_refunded_minor"`
	DiscountRefundedMinor int64              `json:"discount_refunded_minor"`
	TaxRefundedMinor      int64              `json:"tax_refunded_minor"`
	RefundTotalMinor      int64              `json:"refund_total_minor"`
	FxBase                pgtype.Text        `json:"fx_base"`
	FxQuote               pgtype.Text        `json:"fx_quote"`
	FxRate                pgtype.Text        `json:"fx_rate"`
	FxRateMicrorate       pgtype.Int8        `json:"fx_rate_microrate"`
	ShopNameAr            string             `json:"shop_name_ar"`
	ShopNameEn            string             `json:"shop_name_en"`
	ShopAddressAr         string             `json:"shop_address_ar"`
	ShopAddressEn         string             `json:"shop_address_en"`
	ShopPhone             string             `json:"shop_phone"`
	ShopReceiptFooterAr   string             `json:"shop_receipt_footer_ar"`
	ShopReceiptFooterEn   string             `json:"shop_receipt_footer_en"`
	ActorUserID           pgtype.UUID        `json:"actor_user_id"`
	ActorUserName         pgtype.Text        `json:"actor_user_name"`
	ReceivedAt            pgtype.Timestamptz `json:"received_at"`
}

type InsertReturnProjectionRow struct {
	ReturnRefundID pgtype.UUID `json:"return_refund_id"`
	SourceEventID  pgtype.UUID `json:"source_event_id"`
}

func (q *Queries) InsertReturnProjection(ctx context.Context, arg InsertReturnProjectionParams) (InsertReturnProjectionRow, error) {
	row := q.db.QueryRow(ctx, insertReturnProjection,
		arg.ReturnRefundID,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.ReturnNumber,
		arg.Kind,
		arg.Reason,
		arg.Note,
		arg.SaleID,
		arg.SaleNumber,
		arg.SaleEventID,
		arg.Channel,
		arg.OccurredAt,
		arg.Currency,
		arg.GrossRefundedMinor,
		arg.DiscountRefundedMinor,
		arg.TaxRefundedMinor,
		arg.RefundTotalMinor,
		arg.FxBase,
		arg.FxQuote,
		arg.FxRate,
		arg.FxRateMicrorate,
		arg.ShopNameAr,
		arg.ShopNameEn,
		arg.ShopAddressAr,
		arg.ShopAddressEn,
		arg.ShopPhone,
		arg.ShopReceiptFooterAr,
		arg.ShopReceiptFooterEn,
		arg.ActorUserID,
		arg.ActorUserName,
		arg.ReceivedAt,
	)
	var i InsertReturnProjectionRow
	err := row.Scan(&i.ReturnRefundID, &i.SourceEventID)
	return i, err
}

const lockSaleProjectionForReturn = `-- name: LockSaleProjectionForReturn :one
SELECT sale_id, source_event_id, sale_number, channel, occurred_at, paid_at,
    currency, subtotal_minor, discount_minor, tax_minor, total_minor,
    fx_base, fx_quote, fx_rate, fx_rate_microrate
FROM sales_projection WHERE sale_id = $1
FOR UPDATE
`

type LockSaleProjectionForReturnRow struct {
	SaleID          pgtype.UUID        `json:"sale_id"`
	SourceEventID   pgtype.UUID        `json:"source_event_id"`
	SaleNumber      string             `json:"sale_number"`
	Channel         string             `json:"channel"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	Currency        string             `json:"currency"`
	SubtotalMinor   int64              `json:"subtotal_minor"`
	DiscountMinor   int64              `json:"discount_minor"`
	TaxMinor        int64              `json:"tax_minor"`
	TotalMinor      int64              `json:"total_minor"`
	FxBase          pgtype.Text        `json:"fx_base"`
	FxQuote         pgtype.Text        `json:"fx_quote"`
	FxRate          pgtype.Text        `json:"fx_rate"`
	FxRateMicrorate pgtype.Int8        `json:"fx_rate_microrate"`
}

// Parent-row lock serializing all return projections for one sale, so the
// cumulative quantity/economic guards below cannot write-skew under
// concurrency. Returns the authoritative sale economics for cross-checks.
func (q *Queries) LockSaleProjectionForReturn(ctx context.Context, saleID pgtype.UUID) (LockSaleProjectionForReturnRow, error) {
	row := q.db.QueryRow(ctx, lockSaleProjectionForReturn, saleID)
	var i LockSaleProjectionForReturnRow
	err := row.Scan(
		&i.SaleID,
		&i.SourceEventID,
		&i.SaleNumber,
		&i.Channel,
		&i.OccurredAt,
		&i.PaidAt,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxMinor,
		&i.TotalMinor,
		&i.FxBase,
		&i.FxQuote,
		&i.FxRate,
		&i.FxRateMicrorate,
	)
	return i, err
}

const pendingReturnEvents = `-- name: PendingReturnEvents :many
SELECT e.event_id
FROM sync_events e
LEFT JOIN sync_event_processing p
  ON p.event_id = e.event_id AND p.processor = $1
WHERE e.event_type = 'sale.return_refund.finalized.v1'
  AND (p.event_id IS NULL
       OR p.status = 'pending'
       OR (p.status = 'retry' AND (p.next_attempt_at IS NULL OR p.next_attempt_at <= now())))
ORDER BY e.received_at, e.event_id
LIMIT $2
`

type PendingReturnEventsParams struct {
	Processor string `json:"processor"`
	Limit     int32  `json:"limit"`
}

// Durable discovery: accepted return events with no processing row (missing),
// a pending row, or a due retry. Blocked and processed rows are never
// returned; retry rows only when next_attempt_at <= now (NULL counts as
// due). Ordered deterministically by received_at, event_id.
func (q *Queries) PendingReturnEvents(ctx context.Context, arg PendingReturnEventsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, pendingReturnEvents, arg.Processor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var event_id pgtype.UUID
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnProjectionByEventID = `-- name: ReturnProjectionByEventID :one
SELECT return_refund_id FROM return_refund_projection WHERE source_event_id = $1
`

func (q *Queries) ReturnProjectionByEventID(ctx context.Context, sourceEventID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, returnProjectionByEventID, sourceEventID)
	var return_refund_id pgtype.UUID
	err := row.Scan(&return_refund_id)
	return return_refund_id, err
}

const returnProjectionByID = `-- name: ReturnProjectionByID :one
SELECT return_refund_id, source_event_id, source_device_id, return_number, kind,
    reason, sale_id, sale_number, channel, occurred_at, currency,
    gross_refunded_minor, discount_refunded_minor, tax_refunded_minor, refund_total_minor
FROM return_refund_projection WHERE return_refund_id = $1
`

type ReturnProjectionByIDRow struct {
	ReturnRefundID        pgtype.UUID        `json:"return_refund_id"`
	SourceEventID         pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID        pgtype.UUID        `json:"source_device_id"`
	ReturnNumber          string             `json:"return_number"`
	Kind                  string             `json:"kind"`
	Reason                string             `json:"reason"`
	SaleID                pgtype.UUID        `json:"sale_id"`
	SaleNumber            string             `json:"sale_number"`
	Channel               string             `json:"channel"`
	OccurredAt            pgtype.Timestamptz `json:"occurred_at"`
	Currency              string             `json:"currency"`
	GrossRefundedMinor    int64              `json:"gross_refunded_minor"`
	DiscountRefundedMinor int64              `json:"discount_refunded_minor"`
	TaxRefundedMinor      int64              `json:"tax_refunded_minor"`
	RefundTotalMinor      int64              `json:"refund_total_minor"`
}

func (q *Queries) ReturnProjectionByID(ctx context.Context, returnRefundID pgtype.UUID) (ReturnProjectionByIDRow, error) {
	row := q.db.QueryRow(ctx, returnProjectionByID, returnRefundID)
	var i ReturnProjectionByIDRow
	err := row.Scan(
		&i.ReturnRefundID,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.ReturnNumber,
		&i.Kind,
		&i.Reason,
		&i.SaleID,
		&i.SaleNumber,
		&i.Channel,
		&i.OccurredAt,
		&i.Currency,
		&i.GrossRefundedMinor,
		&i.DiscountRefundedMinor,
		&i.TaxRefundedMinor,
		&i.RefundTotalMinor,
	)
	return i, err
}

const saleLineForReturn = `-- name: SaleLineForReturn :one
SELECT sale_id, sale_item_id, quantity, line_total_minor
FROM sale_lines_projection WHERE sale_id = $1 AND sale_item_id = $2
`

type SaleLineForReturnParams struct {
	SaleID     pgtype.UUID `json:"sale_id"`
	SaleItemID pgtype.UUID `json:"sale_item_id"`
}

type SaleLineForReturnRow struct {
	SaleID         pgtype.UUID `json:"sale_id"`
	SaleItemID     pgtype.UUID `json:"sale_item_id"`
	Quantity       int32       `json:"quantity"`
	LineTotalMinor int64       `json:"line_total_minor"`
}

// Authoritative sold quantity for one sale line. Missing row means the
// referenced line is not part of the sale projection.
func (q *Queries) SaleLineForReturn(ctx context.Context, arg SaleLineForReturnParams) (SaleLineForReturnRow, error) {
	row := q.db.QueryRow(ctx, saleLineForReturn, arg.SaleID, arg.SaleItemID)
	var i SaleLineForReturnRow
	err := row.Scan(
		&i.SaleID,
		&i.SaleItemID,
		&i.Quantity,
		&i.LineTotalMinor,
	)
	return i, err
}
