// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: return_ownership.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimReturnOwnership = `-- name: ClaimReturnOwnership :one
INSERT INTO return_refund_ownership (return_refund_id, winning_event_id, winning_device_id, decided_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING winning_event_id
`

type ClaimReturnOwnershipParams struct {
	ReturnRefundID  pgtype.UUID        `json:"return_refund_id"`
	WinningEventID  pgtype.UUID        `json:"winning_event_id"`
	WinningDeviceID pgtype.UUID        `json:"winning_device_id"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
}

// Durable arbitration (ADR-0027): the INSERT decides the permanent winner
// for a return_refund_id. The bare ON CONFLICT absorbs either uniqueness
// race — business-ID rivals on return_refund_id, and same-event replays on
// winning_event_id — returning no row in both cases. Callers then read
// explicit state instead of assuming failure. Never delete this table on
// rebuild: projections are disposable, ownership is not.
func (q *Queries) ClaimReturnOwnership(ctx context.Context, arg ClaimReturnOwnershipParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimReturnOwnership,
		arg.ReturnRefundID,
		arg.WinningEventID,
		arg.WinningDeviceID,
		arg.DecidedAt,
	)
	var winning_event_id pgtype.UUID
	err := row.Scan(&winning_event_id)
	return winning_event_id, err
}

const returnOwnershipByID = `-- name: ReturnOwnershipByID :one
SELECT return_refund_id, winning_event_id, winning_device_id, decided_at
FROM return_refund_ownership WHERE return_refund_id = $1
FOR UPDATE
`

// Read the durable winner inside the arbitration transaction (row lock keeps
// concurrent arbiters serialized on the same return_refund_id).
func (q *Queries) ReturnOwnershipByID(ctx context.Context, returnRefundID pgtype.UUID) (ReturnRefundOwnership, error) {
	row := q.db.QueryRow(ctx, returnOwnershipByID, returnRefundID)
	var i ReturnRefundOwnership
	err := row.Scan(
		&i.ReturnRefundID,
		&i.WinningEventID,
		&i.WinningDeviceID,
		&i.DecidedAt,
	)
	return i, err
}

const returnOwnershipByWinner = `-- name: ReturnOwnershipByWinner :one
SELECT return_refund_id, winning_event_id, winning_device_id, decided_at
FROM return_refund_ownership WHERE winning_event_id = $1
`

// Reverse lookup for the impossible-invariant check: a winning event may
// own exactly one return_refund_id. A hit here with a different business
// ID is a deterministic integrity failure, never idempotent success.
func (q *Queries) ReturnOwnershipByWinner(ctx context.Context, winningEventID pgtype.UUID) (ReturnRefundOwnership, error) {
	row := q.db.QueryRow(ctx, returnOwnershipByWinner, winningEventID)
	var i ReturnRefundOwnership
	err := row.Scan(
		&i.ReturnRefundID,
		&i.WinningEventID,
		&i.WinningDeviceID,
		&i.DecidedAt,
	)
	return i, err
}

const returnOwnershipIntegrityMismatches = `-- name: ReturnOwnershipIntegrityMismatches :many
SELECT r.return_refund_id, r.source_event_id AS projected_source, o.winning_event_id
FROM return_refund_projection r
JOIN return_refund_ownership o USING (return_refund_id)
WHERE r.source_event_id <> o.winning_event_id
`

type ReturnOwnershipIntegrityMismatchesRow struct {
	ReturnRefundID  pgtype.UUID `json:"return_refund_id"`
	ProjectedSource pgtype.UUID `json:"projected_source"`
	WinningEventID  pgtype.UUID `json:"winning_event_id"`
}

// Operational integrity check: any projected return whose source event
// differs from the durable winner is an integrity failure.
func (q *Queries) ReturnOwnershipIntegrityMismatches(ctx context.Context) ([]ReturnOwnershipIntegrityMismatchesRow, error) {
	rows, err := q.db.Query(ctx, returnOwnershipIntegrityMismatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReturnOwnershipIntegrityMismatchesRow{}
	for rows.Next() {
		var i ReturnOwnershipIntegrityMismatchesRow
		if err := rows.Scan(&i.ReturnRefundID, &i.ProjectedSource, &i.WinningEventID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
