// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sale_projection.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSaleClassification = `-- name: InsertSaleClassification :exec
INSERT INTO sale_line_classifications_projection (
    sale_id, sale_item_id, classification_kind, classification_id,
    name_ar, name_en, position
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (sale_id, sale_item_id, classification_kind, classification_id) DO NOTHING
`

type InsertSaleClassificationParams struct {
	SaleID             pgtype.UUID `json:"sale_id"`
	SaleItemID         pgtype.UUID `json:"sale_item_id"`
	ClassificationKind string      `json:"classification_kind"`
	ClassificationID   pgtype.UUID `json:"classification_id"`
	NameAr             string      `json:"name_ar"`
	NameEn             string      `json:"name_en"`
	Position           int32       `json:"position"`
}

func (q *Queries) InsertSaleClassification(ctx context.Context, arg InsertSaleClassificationParams) error {
	_, err := q.db.Exec(ctx, insertSaleClassification,
		arg.SaleID,
		arg.SaleItemID,
		arg.ClassificationKind,
		arg.ClassificationID,
		arg.NameAr,
		arg.NameEn,
		arg.Position,
	)
	return err
}

const insertSaleLine = `-- name: InsertSaleLine :exec
INSERT INTO sale_lines_projection (
    sale_id, sale_item_id, position, product_id, variant_id, sku, product_name,
    width_cm, height_cm, quantity,
    unit_price_minor, unit_currency, cost_minor, cost_currency,
    line_total_minor, line_currency
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (sale_id, sale_item_id) DO NOTHING
`

type InsertSaleLineParams struct {
	SaleID         pgtype.UUID `json:"sale_id"`
	SaleItemID     pgtype.UUID `json:"sale_item_id"`
	Position       int32       `json:"position"`
	ProductID      pgtype.UUID `json:"product_id"`
	VariantID      pgtype.UUID `json:"variant_id"`
	Sku            string      `json:"sku"`
	ProductName    string      `json:"product_name"`
	WidthCm        pgtype.Int4 `json:"width_cm"`
	HeightCm       pgtype.Int4 `json:"height_cm"`
	Quantity       int32       `json:"quantity"`
	UnitPriceMinor int64       `json:"unit_price_minor"`
	UnitCurrency   string      `json:"unit_currency"`
	CostMinor      pgtype.Int8 `json:"cost_minor"`
	CostCurrency   pgtype.Text `json:"cost_currency"`
	LineTotalMinor int64       `json:"line_total_minor"`
	LineCurrency   string      `json:"line_currency"`
}

func (q *Queries) InsertSaleLine(ctx context.Context, arg InsertSaleLineParams) error {
	_, err := q.db.Exec(ctx, insertSaleLine,
		arg.SaleID,
		arg.SaleItemID,
		arg.Position,
		arg.ProductID,
		arg.VariantID,
		arg.Sku,
		arg.ProductName,
		arg.WidthCm,
		arg.HeightCm,
		arg.Quantity,
		arg.UnitPriceMinor,
		arg.UnitCurrency,
		arg.CostMinor,
		arg.CostCurrency,
		arg.LineTotalMinor,
		arg.LineCurrency,
	)
	return err
}

const insertSalePayment = `-- name: InsertSalePayment :exec
INSERT INTO sale_payments_projection (
    sale_id, position, method, amount_minor, amount_currency,
    change_minor, change_currency, transaction_ref
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (sale_id, position) DO NOTHING
`

type InsertSalePaymentParams struct {
	SaleID         pgtype.UUID `json:"sale_id"`
	Position       int32       `json:"position"`
	Method         string      `json:"method"`
	AmountMinor    int64       `json:"amount_minor"`
	AmountCurrency string      `json:"amount_currency"`
	ChangeMinor    int64       `json:"change_minor"`
	ChangeCurrency string      `json:"change_currency"`
	TransactionRef pgtype.Text `json:"transaction_ref"`
}

func (q *Queries) InsertSalePayment(ctx context.Context, arg InsertSalePaymentParams) error {
	_, err := q.db.Exec(ctx, insertSalePayment,
		arg.SaleID,
		arg.Position,
		arg.Method,
		arg.AmountMinor,
		arg.AmountCurrency,
		arg.ChangeMinor,
		arg.ChangeCurrency,
		arg.TransactionRef,
	)
	return err
}

const insertSaleProjection = `-- name: InsertSaleProjection :exec
INSERT INTO sales_projection (
    sale_id, source_event_id, source_device_id, sale_number, channel,
    occurred_at, paid_at,
    shop_name_ar, shop_name_en, shop_address_ar, shop_address_en, shop_phone,
    shop_receipt_footer_ar, shop_receipt_footer_en,
    cashier_id, cashier_name, currency,
    subtotal_minor, discount_minor, tax_minor, total_minor,
    fx_base, fx_quote, fx_rate, fx_rate_microrate,
    received_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26
)
ON CONFLICT (sale_id) DO NOTHING
`

type InsertSaleProjectionParams struct {
	SaleID              pgtype.UUID        `json:"sale_id"`
	SourceEventID       pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID      pgtype.UUID        `json:"source_device_id"`
	SaleNumber          string             `json:"sale_number"`
	Channel             string             `json:"channel"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
	PaidAt              pgtype.Timestamptz `json:"paid_at"`
	ShopNameAr          string             `json:"shop_name_ar"`
	ShopNameEn          string             `json:"shop_name_en"`
	ShopAddressAr       string             `json:"shop_address_ar"`
	ShopAddressEn       string             `json:"shop_address_en"`
	ShopPhone           string             `json:"shop_phone"`
	ShopReceiptFooterAr string             `json:"shop_receipt_footer_ar"`
	ShopReceiptFooterEn string             `json:"shop_receipt_footer_en"`
	CashierID           pgtype.Text        `json:"cashier_id"`
	CashierName         pgtype.Text        `json:"cashier_name"`
	Currency            string             `json:"currency"`
	SubtotalMinor       int64              `json:"subtotal_minor"`
	DiscountMinor       int64              `json:"discount_minor"`
	TaxMinor            int64              `json:"tax_minor"`
	TotalMinor          int64              `json:"total_minor"`
	FxBase              pgtype.Text        `json:"fx_base"`
	FxQuote             pgtype.Text        `json:"fx_quote"`
	FxRate              pgtype.Text        `json:"fx_rate"`
	FxRateMicrorate     pgtype.Int8        `json:"fx_rate_microrate"`
	ReceivedAt          pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) InsertSaleProjection(ctx context.Context, arg InsertSaleProjectionParams) error {
	_, err := q.db.Exec(ctx, insertSaleProjection,
		arg.SaleID,
		arg.SourceEventID,
		arg.SourceDeviceID,
		arg.SaleNumber,
		arg.Channel,
		arg.OccurredAt,
		arg.PaidAt,
		arg.ShopNameAr,
		arg.ShopNameEn,
		arg.ShopAddressAr,
		arg.ShopAddressEn,
		arg.ShopPhone,
		arg.ShopReceiptFooterAr,
		arg.ShopReceiptFooterEn,
		arg.CashierID,
		arg.CashierName,
		arg.Currency,
		arg.SubtotalMinor,
		arg.DiscountMinor,
		arg.TaxMinor,
		arg.TotalMinor,
		arg.FxBase,
		arg.FxQuote,
		arg.FxRate,
		arg.FxRateMicrorate,
		arg.ReceivedAt,
	)
	return err
}

const saleProjectionByEventID = `-- name: SaleProjectionByEventID :one
SELECT sale_id FROM sales_projection WHERE source_event_id = $1
`

func (q *Queries) SaleProjectionByEventID(ctx context.Context, sourceEventID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saleProjectionByEventID, sourceEventID)
	var sale_id pgtype.UUID
	err := row.Scan(&sale_id)
	return sale_id, err
}

const saleProjectionBySaleID = `-- name: SaleProjectionBySaleID :one
SELECT sale_id, source_event_id, source_device_id, sale_number, channel,
    occurred_at, paid_at, currency, subtotal_minor, discount_minor, tax_minor, total_minor
FROM sales_projection WHERE sale_id = $1
`

type SaleProjectionBySaleIDRow struct {
	SaleID         pgtype.UUID        `json:"sale_id"`
	SourceEventID  pgtype.UUID        `json:"source_event_id"`
	SourceDeviceID pgtype.UUID        `json:"source_device_id"`
	SaleNumber     string             `json:"sale_number"`
	Channel        string             `json:"channel"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	Currency       string             `json:"currency"`
	SubtotalMinor  int64              `json:"subtotal_minor"`
	DiscountMinor  int64              `json:"discount_minor"`
	TaxMinor       int64              `json:"tax_minor"`
	TotalMinor     int64              `json:"total_minor"`
}

func (q *Queries) SaleProjectionBySaleID(ctx context.Context, saleID pgtype.UUID) (SaleProjectionBySaleIDRow, error) {
	row := q.db.QueryRow(ctx, saleProjectionBySaleID, saleID)
	var i SaleProjectionBySaleIDRow
	err := row.Scan(
		&i.SaleID,
		&i.SourceEventID,
		&i.SourceDeviceID,
		&i.SaleNumber,
		&i.Channel,
		&i.OccurredAt,
		&i.PaidAt,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxMinor,
		&i.TotalMinor,
	)
	return i, err
}
