// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sale_ownership.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimSaleOwnership = `-- name: ClaimSaleOwnership :one
INSERT INTO sale_event_ownership (sale_id, winning_event_id, winning_device_id, decided_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING winning_event_id
`

type ClaimSaleOwnershipParams struct {
	SaleID          pgtype.UUID        `json:"sale_id"`
	WinningEventID  pgtype.UUID        `json:"winning_event_id"`
	WinningDeviceID pgtype.UUID        `json:"winning_device_id"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
}

// Durable arbitration (P2D-HIGH-02, P2E-MED-01): the INSERT decides the
// permanent winner for a sale_id. The bare ON CONFLICT absorbs either
// uniqueness race — same-sale rivals on sale_id, and same-event replays on
// winning_event_id — returning no row in both cases. Callers must then
// read explicit state (by sale, then by winner) instead of assuming
// failure. Never delete this table on rebuild: projections are disposable,
// ownership is not.
func (q *Queries) ClaimSaleOwnership(ctx context.Context, arg ClaimSaleOwnershipParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimSaleOwnership,
		arg.SaleID,
		arg.WinningEventID,
		arg.WinningDeviceID,
		arg.DecidedAt,
	)
	var winning_event_id pgtype.UUID
	err := row.Scan(&winning_event_id)
	return winning_event_id, err
}

const ownershipIntegrityMismatches = `-- name: OwnershipIntegrityMismatches :many
SELECT s.sale_id, s.source_event_id AS projected_source, o.winning_event_id
FROM sales_projection s
JOIN sale_event_ownership o USING (sale_id)
WHERE s.source_event_id <> o.winning_event_id
`

type OwnershipIntegrityMismatchesRow struct {
	SaleID          pgtype.UUID `json:"sale_id"`
	ProjectedSource pgtype.UUID `json:"projected_source"`
	WinningEventID  pgtype.UUID `json:"winning_event_id"`
}

// Operational integrity check (§53): any projected sale whose source event
// differs from the durable winner is an integrity failure.
func (q *Queries) OwnershipIntegrityMismatches(ctx context.Context) ([]OwnershipIntegrityMismatchesRow, error) {
	rows, err := q.db.Query(ctx, ownershipIntegrityMismatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OwnershipIntegrityMismatchesRow{}
	for rows.Next() {
		var i OwnershipIntegrityMismatchesRow
		if err := rows.Scan(&i.SaleID, &i.ProjectedSource, &i.WinningEventID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saleOwnershipBySaleID = `-- name: SaleOwnershipBySaleID :one
SELECT sale_id, winning_event_id, winning_device_id, decided_at
FROM sale_event_ownership WHERE sale_id = $1
FOR UPDATE
`

// Read the durable winner inside the arbitration transaction (row lock keeps
// concurrent arbiters serialized on the same sale_id).
func (q *Queries) SaleOwnershipBySaleID(ctx context.Context, saleID pgtype.UUID) (SaleEventOwnership, error) {
	row := q.db.QueryRow(ctx, saleOwnershipBySaleID, saleID)
	var i SaleEventOwnership
	err := row.Scan(
		&i.SaleID,
		&i.WinningEventID,
		&i.WinningDeviceID,
		&i.DecidedAt,
	)
	return i, err
}

const saleOwnershipByWinner = `-- name: SaleOwnershipByWinner :one
SELECT sale_id, winning_event_id, winning_device_id, decided_at
FROM sale_event_ownership WHERE winning_event_id = $1
`

// Reverse lookup for the impossible-invariant check: a winning event may
// own exactly one sale_id. A hit here with a different sale_id is a
// deterministic integrity failure, never idempotent success.
func (q *Queries) SaleOwnershipByWinner(ctx context.Context, winningEventID pgtype.UUID) (SaleEventOwnership, error) {
	row := q.db.QueryRow(ctx, saleOwnershipByWinner, winningEventID)
	var i SaleEventOwnership
	err := row.Scan(
		&i.SaleID,
		&i.WinningEventID,
		&i.WinningDeviceID,
		&i.DecidedAt,
	)
	return i, err
}
