// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_identity.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindingByDevice = `-- name: BindingByDevice :one
SELECT device_id, store_id, created_at
FROM device_store_bindings
WHERE device_id = $1
`

func (q *Queries) BindingByDevice(ctx context.Context, deviceID pgtype.UUID) (DeviceStoreBinding, error) {
	row := q.db.QueryRow(ctx, bindingByDevice, deviceID)
	var i DeviceStoreBinding
	err := row.Scan(&i.DeviceID, &i.StoreID, &i.CreatedAt)
	return i, err
}

const devicesByStore = `-- name: DevicesByStore :many
SELECT device_id
FROM device_store_bindings
WHERE store_id = $1
ORDER BY device_id
`

func (q *Queries) DevicesByStore(ctx context.Context, storeID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, devicesByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var device_id pgtype.UUID
		if err := rows.Scan(&device_id); err != nil {
			return nil, err
		}
		items = append(items, device_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeviceBinding = `-- name: InsertDeviceBinding :exec
INSERT INTO device_store_bindings (device_id, store_id)
VALUES ($1, $2)
ON CONFLICT (device_id) DO NOTHING
`

type InsertDeviceBindingParams struct {
	DeviceID pgtype.UUID `json:"device_id"`
	StoreID  pgtype.UUID `json:"store_id"`
}

func (q *Queries) InsertDeviceBinding(ctx context.Context, arg InsertDeviceBindingParams) error {
	_, err := q.db.Exec(ctx, insertDeviceBinding, arg.DeviceID, arg.StoreID)
	return err
}

const insertStore = `-- name: InsertStore :execrows

INSERT INTO stores (id, display_name, timezone)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type InsertStoreParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Timezone    string      `json:"timezone"`
}

// Phase 9A store registry + device bindings. Bindings are immutable:
// inserts only, conflicts stay conflicts; enforced by PRIMARY KEY on
// device_id (at most one binding per device).
func (q *Queries) InsertStore(ctx context.Context, arg InsertStoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertStore, arg.ID, arg.DisplayName, arg.Timezone)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBindingsWithStores = `-- name: ListBindingsWithStores :many
SELECT b.device_id, b.store_id, s.display_name, s.status
FROM device_store_bindings b
JOIN stores s ON s.id = b.store_id
ORDER BY b.device_id
`

type ListBindingsWithStoresRow struct {
	DeviceID    pgtype.UUID `json:"device_id"`
	StoreID     pgtype.UUID `json:"store_id"`
	DisplayName string      `json:"display_name"`
	Status      string      `json:"status"`
}

func (q *Queries) ListBindingsWithStores(ctx context.Context) ([]ListBindingsWithStoresRow, error) {
	rows, err := q.db.Query(ctx, listBindingsWithStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBindingsWithStoresRow{}
	for rows.Next() {
		var i ListBindingsWithStoresRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.StoreID,
			&i.DisplayName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStores = `-- name: ListStores :many
SELECT s.id, s.display_name, s.timezone, s.status, s.created_at, s.updated_at,
    COUNT(b.device_id)::bigint AS device_count
FROM stores s
LEFT JOIN device_store_bindings b ON b.store_id = s.id
GROUP BY s.id
ORDER BY s.created_at, s.id
`

type ListStoresRow struct {
	ID          pgtype.UUID        `json:"id"`
	DisplayName string             `json:"display_name"`
	Timezone    string             `json:"timezone"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeviceCount int64              `json:"device_count"`
}

func (q *Queries) ListStores(ctx context.Context) ([]ListStoresRow, error) {
	rows, err := q.db.Query(ctx, listStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoresRow{}
	for rows.Next() {
		var i ListStoresRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Timezone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStoreRegistrationDevice = `-- name: LockStoreRegistrationDevice :one
SELECT status FROM devices WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockStoreRegistrationDevice(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lockStoreRegistrationDevice, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const storeByID = `-- name: StoreByID :one
SELECT id, display_name, timezone, status, created_at, updated_at
FROM stores
WHERE id = $1
`

func (q *Queries) StoreByID(ctx context.Context, id pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, storeByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStoreMetadata = `-- name: UpdateStoreMetadata :exec
UPDATE stores
SET display_name = $2, timezone = $3, updated_at = now()
WHERE id = $1
`

type UpdateStoreMetadataParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Timezone    string      `json:"timezone"`
}

func (q *Queries) UpdateStoreMetadata(ctx context.Context, arg UpdateStoreMetadataParams) error {
	_, err := q.db.Exec(ctx, updateStoreMetadata, arg.ID, arg.DisplayName, arg.Timezone)
	return err
}
