// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSyncEvent = `-- name: InsertSyncEvent :one
INSERT INTO sync_events
    (event_id, device_id, credential_id, event_type, occurred_at, received_at, payload, payload_hash, payload_hash_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

type InsertSyncEventParams struct {
	EventID            pgtype.UUID        `json:"event_id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	CredentialID       pgtype.UUID        `json:"credential_id"`
	EventType          string             `json:"event_type"`
	OccurredAt         pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	Payload            []byte             `json:"payload"`
	PayloadHash        []byte             `json:"payload_hash"`
	PayloadHashVersion int32              `json:"payload_hash_version"`
}

func (q *Queries) InsertSyncEvent(ctx context.Context, arg InsertSyncEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertSyncEvent,
		arg.EventID,
		arg.DeviceID,
		arg.CredentialID,
		arg.EventType,
		arg.OccurredAt,
		arg.ReceivedAt,
		arg.Payload,
		arg.PayloadHash,
		arg.PayloadHashVersion,
	)
	var event_id pgtype.UUID
	err := row.Scan(&event_id)
	return event_id, err
}

const saleEventByID = `-- name: SaleEventByID :one
SELECT event_id, device_id, credential_id, event_type, occurred_at, received_at, payload
FROM sync_events WHERE event_id = $1
`

type SaleEventByIDRow struct {
	EventID      pgtype.UUID        `json:"event_id"`
	DeviceID     pgtype.UUID        `json:"device_id"`
	CredentialID pgtype.UUID        `json:"credential_id"`
	EventType    string             `json:"event_type"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	Payload      []byte             `json:"payload"`
}

func (q *Queries) SaleEventByID(ctx context.Context, eventID pgtype.UUID) (SaleEventByIDRow, error) {
	row := q.db.QueryRow(ctx, saleEventByID, eventID)
	var i SaleEventByIDRow
	err := row.Scan(
		&i.EventID,
		&i.DeviceID,
		&i.CredentialID,
		&i.EventType,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.Payload,
	)
	return i, err
}

const syncEventByID = `-- name: SyncEventByID :one
SELECT event_id, device_id, event_type, occurred_at, payload, payload_hash, payload_hash_version
FROM sync_events WHERE event_id = $1
`

type SyncEventByIDRow struct {
	EventID            pgtype.UUID        `json:"event_id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	EventType          string             `json:"event_type"`
	OccurredAt         pgtype.Timestamptz `json:"occurred_at"`
	Payload            []byte             `json:"payload"`
	PayloadHash        []byte             `json:"payload_hash"`
	PayloadHashVersion int32              `json:"payload_hash_version"`
}

// Full immutable identity for idempotency: device, type, instant, payload.
// Credential identity and batch correlation are never part of event
// identity. The stored immutable payload (not the v1 hash) is the
// authoritative duplicate proof for pre-fix rows (fail-closed, ADR-0017+).
func (q *Queries) SyncEventByID(ctx context.Context, eventID pgtype.UUID) (SyncEventByIDRow, error) {
	row := q.db.QueryRow(ctx, syncEventByID, eventID)
	var i SyncEventByIDRow
	err := row.Scan(
		&i.EventID,
		&i.DeviceID,
		&i.EventType,
		&i.OccurredAt,
		&i.Payload,
		&i.PayloadHash,
		&i.PayloadHashVersion,
	)
	return i, err
}

const upgradeSyncEventHash = `-- name: UpgradeSyncEventHash :exec
UPDATE sync_events
SET payload_hash = $2, payload_hash_version = 2
WHERE event_id = $1 AND payload_hash_version = 1
`

type UpgradeSyncEventHashParams struct {
	EventID     pgtype.UUID `json:"event_id"`
	PayloadHash []byte      `json:"payload_hash"`
}

// Opportunistic v1→v2 convergence after an exact stored-payload match:
// only hash metadata changes, never the immutable payload. Guarded to v1
// rows so concurrent upgrades write identical values idempotently.
func (q *Queries) UpgradeSyncEventHash(ctx context.Context, arg UpgradeSyncEventHashParams) error {
	_, err := q.db.Exec(ctx, upgradeSyncEventHash, arg.EventID, arg.PayloadHash)
	return err
}
